minimumReleaseAge: 1440
allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  '@posthog/cli': true
  '@sentry/cli': true
  browser-tabs-lock: true
  core-js: false
  esbuild: true
  maplibre-gl: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
overrides:
  '@graphql-tools/utils@<=12.0.0': ^12.0.1
  '@grpc/grpc-js@<1.13.6': ^1.13.6
  '@simple-git/argv-parser@<2.0.1': ^2.0.1
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  immutable@<3.8.4: ^3.8.4
  lodash@<=4.17.23: ^4.18.1
  postcss-selector-parser@<7.1.6: ^7.1.6
  simple-git@<=3.36.0: ^4.0.0
  simple-git@>=3.15.0 <4.0.1: ^4.0.1
  source-map-js@>=1.0.0 <1.2.2: ^1.2.2
