query StandingsGlobalPage(
  $entityType: LeaderboardEntityType!
  $filter: LeaderboardFilter
  $first: Int
) {
  myCurrentProject {
    id
    leaderboard(entityType: $entityType, filter: $filter, first: $first) {
      edges {
        node {
          ...LeaderboardEntryWithDescriptionFields
        }
      }
      me {
        ...LeaderboardEntryWithDescriptionFields
      }
    }
  }
}
