query StandingsLocalPage($filter: LeaderboardFilter) {
  me {
    church {
      id
      name
    }
  }
  myCurrentProject {
    id
    personLeaderboard: leaderboard(entityType: PERSONS, filter: $filter) {
      totalCount
      edges {
        node {
          ...LeaderboardEntryFields
        }
      }
      me {
        ...LeaderboardEntryFields
      }
    }
    unitLeaderboard: leaderboard(entityType: TEAMS, filter: $filter) {
      totalCount
      edges {
        node {
          ...LeaderboardEntryFields
        }
      }
      me {
        ...LeaderboardEntryFields
      }
    }
  }
}
