query StandingsLocalPage($filter: LeaderboardFilter, $first: Int) {
  me {
    church {
      id
      name
    }
  }
  myCurrentProject {
    id
    personLeaderboard: leaderboard(
      entityType: PERSONS
      filter: $filter
      first: $first
    ) {
      totalCount
      edges {
        node {
          ...LeaderboardEntryFields
        }
      }
      me {
        ...LeaderboardEntryFields
      }
    }
    unitLeaderboard: leaderboard(
      entityType: TEAMS
      filter: $filter
      first: $first
    ) {
      totalCount
      edges {
        node {
          ...LeaderboardEntryFields
        }
      }
      me {
        ...LeaderboardEntryFields
      }
    }
  }
}
