package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"time"

	"github.com/bcc-media/wayfarer/internal/cache"
	"github.com/bcc-media/wayfarer/internal/database/sqlc"
	"github.com/bcc-media/wayfarer/internal/graph/api/model"
	"github.com/bcc-media/wayfarer/internal/graph/pagination"
	"github.com/bcc-media/wayfarer/internal/graph/scalars"
	"github.com/bcc-media/wayfarer/internal/middleware"
	"github.com/bcc-media/wayfarer/internal/ulid"
	"github.com/jackc/pgx/v5/pgtype"
)

// CreateChallenge is the resolver for the createChallenge field.
func (r *mutationResolver) CreateChallenge(ctx context.Context, projectID string, eventID string, input model.CreateChallengeInput) (*model.Challenge, error) {
	// Get authenticated user ID from context
	userID, ok := middleware.GetUserID(ctx)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Check authorization (admins, superadmins, and project admins for their own projects)
	if !r.RoleService.CanManageProject(ctx, userID, projectID) {
		return nil, fmt.Errorf("unauthorized to create challenges in this project")
	}

	// Generate new challenge ID
	challengeID := ulid.NewChallengeID()

	// Build params for database
	params := sqlc.CreateChallengeParams{
		ID:         challengeID,
		Projectid:  projectID,
		Name:       input.Name,
		Buttontext: input.ButtonText,
	}

	// Set optional description (default to empty string if not provided)
	if input.Description != nil {
		params.Description = string(*input.Description)
	}

	// Set optional image and URL
	params.Imageurl = input.Image
	params.Url = input.URL

	// Set required eventID
	params.Eventid = eventID

	// Set optional endTime
	if input.EndTime != nil {
		params.Endtime = pgtype.Timestamptz{Time: input.EndTime.Time, Valid: true}
	}

	// Create challenge in database
	row, err := r.DB.Queries.CreateChallenge(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to create challenge: %w", err)
	}

	// Invalidate project cache to reflect new challenge in lists
	r.Cache.InvalidateProject(projectID)

	// Convert to GraphQL model
	return convertCreateChallengeRowToChallenge(row), nil
}

// UpdateChallenge is the resolver for the updateChallenge field.
func (r *mutationResolver) UpdateChallenge(ctx context.Context, id string, input model.UpdateChallengeInput) (*model.Challenge, error) {
	// Get authenticated user ID from context
	userID, ok := middleware.GetUserID(ctx)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Load existing challenge to verify it exists and get project ID
	thunk := r.Loaders.ChallengeByIDLoader.Load(ctx, id)
	existingChallenge, err := thunk()
	if err != nil {
		return nil, fmt.Errorf("failed to load challenge: %w", err)
	}

	// Check authorization (admins, superadmins, and project admins for their own projects)
	if !r.RoleService.CanManageProject(ctx, userID, existingChallenge.ProjectID) {
		return nil, fmt.Errorf("unauthorized to update this challenge")
	}

	// Build update parameters
	params := sqlc.UpdateChallengeParams{
		ID: id,
	}

	// Only set fields that are provided
	if input.Name != nil {
		params.Name = input.Name
	}
	if input.Description != nil {
		desc := string(*input.Description)
		params.Description = &desc
	}
	if input.Image != nil {
		params.Imageurl = input.Image
	}
	if input.URL != nil {
		params.Url = input.URL
	}
	if input.ButtonText != nil {
		params.Buttontext = input.ButtonText
	}
	if input.EventID != nil {
		params.Eventid = input.EventID
	}
	if input.EndTime != nil {
		params.Endtime = pgtype.Timestamptz{Time: input.EndTime.Time, Valid: true}
	}

	// Update challenge in database
	row, err := r.DB.Queries.UpdateChallenge(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to update challenge: %w", err)
	}

	// Invalidate cache
	r.Cache.InvalidateChallenge(id)

	// Delete translations when translatable fields are updated
	if input.Name != nil || input.Description != nil || input.ButtonText != nil {
		_ = r.DB.Queries.DeleteChallengeTranslations(ctx, id)
		r.Cache.DeletePrefix(cache.PrefixTranslation + "challenge:" + id)
	}

	// If eventID is being changed, invalidate both old and new events
	if input.EventID != nil {
		// Invalidate old event if it exists
		if existingChallenge.EventID != nil {
			r.Cache.InvalidateEvent(*existingChallenge.EventID)
		}
		// Invalidate new event if it's being set to a value
		if *input.EventID != "" {
			r.Cache.InvalidateEvent(*input.EventID)
		}
	}

	// Convert to GraphQL model
	return convertUpdateChallengeRowToChallenge(row), nil
}

// DeleteChallenge is the resolver for the deleteChallenge field.
func (r *mutationResolver) DeleteChallenge(ctx context.Context, id string) (bool, error) {
	// Get authenticated user ID from context
	userID, ok := middleware.GetUserID(ctx)
	if !ok || userID == "" {
		return false, fmt.Errorf("user not authenticated")
	}

	// Load existing challenge to verify it exists and get project ID
	thunk := r.Loaders.ChallengeByIDLoader.Load(ctx, id)
	existingChallenge, err := thunk()
	if err != nil {
		return false, fmt.Errorf("failed to load challenge: %w", err)
	}

	// Check authorization (admins, superadmins, and project admins for their own projects)
	if !r.RoleService.CanManageProject(ctx, userID, existingChallenge.ProjectID) {
		return false, fmt.Errorf("unauthorized to delete this challenge")
	}

	// Delete challenge from database
	err = r.DB.Queries.DeleteChallenge(ctx, id)
	if err != nil {
		return false, fmt.Errorf("failed to delete challenge: %w", err)
	}

	// Invalidate cache
	r.Cache.InvalidateChallenge(id)
	r.Cache.InvalidateProject(existingChallenge.ProjectID)

	return true, nil
}

// PublishChallenge is the resolver for the publishChallenge field.
func (r *mutationResolver) PublishChallenge(ctx context.Context, id string, publishedAt scalars.DateTime) (*model.Challenge, error) {
	// Get authenticated user ID from context
	userID, ok := middleware.GetUserID(ctx)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Load existing challenge to verify it exists and get project ID
	thunk := r.Loaders.ChallengeByIDLoader.Load(ctx, id)
	existingChallenge, err := thunk()
	if err != nil {
		return nil, fmt.Errorf("failed to load challenge: %w", err)
	}

	// Check authorization (admins, superadmins, and project admins for their own projects)
	if !r.RoleService.CanManageProject(ctx, userID, existingChallenge.ProjectID) {
		return nil, fmt.Errorf("unauthorized to publish this challenge")
	}

	// Publish challenge in database
	row, err := r.DB.Queries.PublishChallenge(ctx, sqlc.PublishChallengeParams{
		ID:          id,
		Publishedat: pgtype.Timestamptz{Time: publishedAt.Time, Valid: true},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to publish challenge: %w", err)
	}

	// Invalidate cache
	r.Cache.InvalidateChallenge(id)

	// Convert to GraphQL model
	return convertPublishChallengeRowToChallenge(row), nil
}

// AssignChallengeToEvent is the resolver for the assignChallengeToEvent field.
func (r *mutationResolver) AssignChallengeToEvent(ctx context.Context, challengeID string, eventID string) (*model.Challenge, error) {
	// Get authenticated user ID from context
	userID, ok := middleware.GetUserID(ctx)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Load existing challenge to verify it exists and get project ID
	challengeThunk := r.Loaders.ChallengeByIDLoader.Load(ctx, challengeID)
	existingChallenge, err := challengeThunk()
	if err != nil {
		return nil, fmt.Errorf("failed to load challenge: %w", err)
	}

	// Load event to verify it exists and belongs to the same project
	eventThunk := r.Loaders.EventByIDLoader.Load(ctx, eventID)
	event, err := eventThunk()
	if err != nil {
		return nil, fmt.Errorf("failed to load event: %w", err)
	}

	// Verify event belongs to the same project as the challenge
	if event.ProjectID != existingChallenge.ProjectID {
		return nil, fmt.Errorf("event must belong to the same project as the challenge")
	}

	// Check authorization (admins, superadmins, and project admins for their own projects)
	if !r.RoleService.CanManageProject(ctx, userID, existingChallenge.ProjectID) {
		return nil, fmt.Errorf("unauthorized to modify this challenge")
	}

	// Assign challenge to event in database
	row, err := r.DB.Queries.AssignChallengeToEvent(ctx, sqlc.AssignChallengeToEventParams{
		ID:      challengeID,
		Eventid: eventID,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to assign challenge to event: %w", err)
	}

	// Invalidate cache
	r.Cache.InvalidateChallenge(challengeID)

	// Invalidate old event if it exists
	if existingChallenge.EventID != nil {
		r.Cache.InvalidateEvent(*existingChallenge.EventID)
	}
	// Invalidate new event
	r.Cache.InvalidateEvent(eventID)

	// Convert to GraphQL model
	return convertAssignChallengeToEventRowToChallenge(row), nil
}

// BulkPublishChallenges is the resolver for the bulkPublishChallenges field.
func (r *mutationResolver) BulkPublishChallenges(ctx context.Context, ids []string, publishedAt scalars.DateTime) ([]model.Challenge, error) {
	// Get authenticated user ID from context
	userID, ok := middleware.GetUserID(ctx)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Load all challenges to verify they exist and check authorization
	challenges := make([]*model.Challenge, 0, len(ids))
	for _, id := range ids {
		thunk := r.Loaders.ChallengeByIDLoader.Load(ctx, id)
		challenge, err := thunk()
		if err != nil {
			return nil, fmt.Errorf("failed to load challenge %s: %w", id, err)
		}

		// Check authorization for each challenge
		if !r.RoleService.CanManageProject(ctx, userID, challenge.ProjectID) {
			return nil, fmt.Errorf("unauthorized to publish challenge %s", id)
		}

		challenges = append(challenges, challenge)
	}

	// Publish challenges in database
	rows, err := r.DB.Queries.BulkPublishChallenges(ctx, sqlc.BulkPublishChallengesParams{
		Ids:         ids,
		Publishedat: pgtype.Timestamptz{Time: publishedAt.Time, Valid: true},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to bulk publish challenges: %w", err)
	}

	// Invalidate cache for all challenges
	for _, id := range ids {
		r.Cache.InvalidateChallenge(id)
	}

	// Convert to GraphQL models
	result := make([]model.Challenge, len(rows))
	for i, row := range rows {
		result[i] = *convertBulkPublishChallengesRowToChallenge(row)
	}

	return result, nil
}

// BulkCreateChallenges is the resolver for the bulkCreateChallenges field.
func (r *mutationResolver) BulkCreateChallenges(ctx context.Context, projectID string, eventID string, inputs []model.CreateChallengeInput) ([]model.Challenge, error) {
	// Get authenticated user ID from context
	userID, ok := middleware.GetUserID(ctx)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Check authorization for the project
	if !r.RoleService.CanManageProject(ctx, userID, projectID) {
		return nil, fmt.Errorf("unauthorized to create challenges in project %s", projectID)
	}

	// Prepare data for bulk insert
	ids := make([]string, len(inputs))
	projectIDs := make([]string, len(inputs))
	eventIDs := make([]string, len(inputs))
	names := make([]string, len(inputs))
	descriptions := make([]string, len(inputs))
	imageURLs := make([]string, len(inputs))
	urls := make([]string, len(inputs))
	buttonTexts := make([]string, len(inputs))
	publishedAts := make([]pgtype.Timestamptz, len(inputs))
	endTimes := make([]pgtype.Timestamptz, len(inputs))

	for i, input := range inputs {
		// Generate ID for each challenge
		ids[i] = ulid.NewChallengeID()
		projectIDs[i] = projectID
		names[i] = input.Name
		if input.URL != nil {
			urls[i] = *input.URL
		}
		buttonTexts[i] = input.ButtonText

		// Set optional description
		if input.Description != nil {
			descriptions[i] = string(*input.Description)
		}

		// Set optional image
		if input.Image != nil {
			imageURLs[i] = *input.Image
		}

		// Set required eventID (use the top-level eventID parameter for all)
		eventIDs[i] = eventID

		// Set optional endTime
		if input.EndTime != nil {
			endTimes[i] = pgtype.Timestamptz{Time: input.EndTime.Time, Valid: true}
		}
	}

	// Create challenges in database
	rows, err := r.DB.Queries.BulkCreateChallenges(ctx, sqlc.BulkCreateChallengesParams{
		Ids:          ids,
		Projectids:   projectIDs,
		Eventids:     eventIDs,
		Names:        names,
		Descriptions: descriptions,
		Imageurls:    imageURLs,
		Urls:         urls,
		Buttontexts:  buttonTexts,
		Publishedats: publishedAts,
		Endtimes:     endTimes,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to bulk create challenges: %w", err)
	}

	// Invalidate project cache to reflect new challenges in lists
	r.Cache.InvalidateProject(projectID)

	// Convert to GraphQL models
	result := make([]model.Challenge, len(rows))
	for i, row := range rows {
		result[i] = *convertBulkCreateChallengesRowToChallenge(row)
	}

	return result, nil
}

// SetChallengeVisibility - Admin mutation for visibility settings
func (r *mutationResolver) SetChallengeVisibility(ctx context.Context, id string, visibleAt scalars.DateTime, startedAt *scalars.DateTime) (*model.Challenge, error) {
	adminID, ok := middleware.GetUserID(ctx)
	if !ok || adminID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Load challenge for authorization
	thunk := r.Loaders.ChallengeByIDLoader.Load(ctx, id)
	_, err := thunk()
	if err != nil {
		return nil, fmt.Errorf("challenge not found: %w", err)
	}

	// Build params
	params := sqlc.UpdateChallengeTimestampsParams{
		ID:        id,
		Visibleat: pgtype.Timestamptz{Time: visibleAt.Time, Valid: true},
	}
	if startedAt != nil {
		params.Startedat = pgtype.Timestamptz{Time: startedAt.Time, Valid: true}
	}

	// Update in database
	row, err := r.DB.Queries.UpdateChallengeTimestamps(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to update challenge visibility: %w", err)
	}

	// Cache invalidation
	r.Cache.InvalidateChallenge(id)

	// Convert and return
	return convertUpdateChallengeTimestampsRowToChallenge(*row), nil
}

// SetChallengeRequirements - Admin mutation for team/superteam requirements
func (r *mutationResolver) SetChallengeRequirements(ctx context.Context, id string, requiresTeamMembership *bool, requiresSuperTeamMembership *bool) (*model.Challenge, error) {
	adminID, ok := middleware.GetUserID(ctx)
	if !ok || adminID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Load challenge for authorization
	thunk := r.Loaders.ChallengeByIDLoader.Load(ctx, id)
	_, err := thunk()
	if err != nil {
		return nil, fmt.Errorf("challenge not found: %w", err)
	}

	// Build params
	params := sqlc.UpdateChallengeRequirementsParams{
		ID:                          id,
		Requiresteammembership:      requiresTeamMembership,
		Requiressuperteammembership: requiresSuperTeamMembership,
	}

	// Update in database
	row, err := r.DB.Queries.UpdateChallengeRequirements(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to update challenge requirements: %w", err)
	}

	// Cache invalidation
	r.Cache.InvalidateChallenge(id)

	// Convert and return
	return convertUpdateChallengeRequirementsRowToChallenge(*row), nil
}

// EnrollInChallenge - User self-enrollment with validation
func (r *mutationResolver) EnrollInChallenge(ctx context.Context, challengeID string) (*model.Challenge, error) {
	// Get authenticated user ID from context
	userID, ok := middleware.GetUserID(ctx)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Load challenge to verify it exists and get project ID
	thunk := r.Loaders.ChallengeByIDLoader.Load(ctx, challengeID)
	challenge, err := thunk()
	if err != nil {
		return nil, fmt.Errorf("challenge not found: %w", err)
	}

	// Validation 1: Challenge must be published
	if challenge.PublishedAt == nil || challenge.PublishedAt.Time.After(time.Now()) {
		return nil, fmt.Errorf("challenge is not yet available for enrollment")
	}

	// Validation 2: Challenge must not be ended
	if challenge.EndTime != nil && challenge.EndTime.Time.Before(time.Now()) {
		return nil, fmt.Errorf("challenge enrollment has ended")
	}

	// Validation 3: Auto-enroll in project if needed (like team joining)
	isInProject, err := r.DB.Queries.IsUserInProject(ctx, sqlc.IsUserInProjectParams{
		Userid:    userID,
		Projectid: challenge.ProjectID,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to check project membership: %w", err)
	}
	if !isInProject {
		// Automatically join the user to the project
		err = r.DB.Queries.JoinProject(ctx, sqlc.JoinProjectParams{
			Userid:    userID,
			Projectid: challenge.ProjectID,
		})
		if err != nil {
			return nil, fmt.Errorf("failed to auto-enroll in project: %w", err)
		}
	}

	// Validation 4: Check team membership requirement
	if challenge.RequiresTeamMembership {
		isInTeam, err := r.DB.Queries.IsUserInAnyTeamInProject(ctx, sqlc.IsUserInAnyTeamInProjectParams{
			Userid:    userID,
			Projectid: challenge.ProjectID,
		})
		if err != nil {
			return nil, fmt.Errorf("failed to check team membership: %w", err)
		}
		if !isInTeam {
			return nil, fmt.Errorf("you must be a member of a team in this project to enroll in this challenge")
		}
	}

	// Validation 5: Check superteam membership requirement
	if challenge.RequiresSuperTeamMembership {
		isInSuperTeam, err := r.DB.Queries.IsUserInAnySuperTeamInProject(ctx, sqlc.IsUserInAnySuperTeamInProjectParams{
			Userid:    userID,
			Projectid: challenge.ProjectID,
		})
		if err != nil {
			return nil, fmt.Errorf("failed to check super team membership: %w", err)
		}
		if !isInSuperTeam {
			return nil, fmt.Errorf("you must be a member of a super team in this project to enroll in this challenge")
		}
	}

	// Enroll user (idempotent)
	enrolledAt, err := r.DB.Queries.EnrollUserInChallenge(ctx, sqlc.EnrollUserInChallengeParams{
		Userid:      userID,
		Challengeid: challengeID,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to enroll in challenge: %w", err)
	}

	fmt.Printf("DEBUG: enrolledAt.Valid=%v, enrolledAt.Time=%v\n", enrolledAt.Valid, enrolledAt.Time)

	// Cache invalidation
	r.Cache.InvalidateUser(userID)
	r.Cache.InvalidateChallenge(challengeID)

	// Prime the cache with the enrollment timestamp AFTER invalidation
	if enrolledAt.Valid {
		ts := enrolledAt.Time
		cacheKey := cache.UserChallengeEnrollmentKey(userID, challengeID)
		r.Cache.Set(cacheKey, &ts)
		fmt.Printf("DEBUG: Set cache key=%s, value=%v\n", cacheKey, ts)
	}

	// Return challenge with translations
	return r.ApplyTranslationToChallenge(ctx, challenge), nil
}

// UnenrollFromChallenge - User self-unenrollment
func (r *mutationResolver) UnenrollFromChallenge(ctx context.Context, challengeID string) (bool, error) {
	userID, ok := middleware.GetUserID(ctx)
	if !ok || userID == "" {
		return false, fmt.Errorf("user not authenticated")
	}

	err := r.DB.Queries.UnenrollUserFromChallenge(ctx, sqlc.UnenrollUserFromChallengeParams{
		Userid:      userID,
		Challengeid: challengeID,
	})
	if err != nil {
		return false, fmt.Errorf("failed to unenroll from challenge: %w", err)
	}

	r.Cache.InvalidateUser(userID)
	r.Cache.InvalidateChallenge(challengeID)

	return true, nil
}

// EnrollUserInChallenge - Admin enrollment (no validation)
func (r *mutationResolver) EnrollUserInChallenge(ctx context.Context, userID string, challengeID string) (*model.Challenge, error) {
	// Get authenticated admin ID for authorization check
	adminID, ok := middleware.GetUserID(ctx)
	if !ok || adminID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Load challenge to verify it exists
	thunk := r.Loaders.ChallengeByIDLoader.Load(ctx, challengeID)
	challenge, err := thunk()
	if err != nil {
		return nil, fmt.Errorf("challenge not found: %w", err)
	}

	// Enroll user (idempotent)
	enrolledAt, err := r.DB.Queries.EnrollUserInChallenge(ctx, sqlc.EnrollUserInChallengeParams{
		Userid:      userID,
		Challengeid: challengeID,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to enroll user in challenge: %w", err)
	}

	// Cache invalidation
	r.Cache.InvalidateUser(userID)
	r.Cache.InvalidateChallenge(challengeID)

	// Prime the cache with the enrollment timestamp AFTER invalidation
	if enrolledAt.Valid {
		ts := enrolledAt.Time
		r.Cache.Set(cache.UserChallengeEnrollmentKey(userID, challengeID), &ts)
	}

	return r.ApplyTranslationToChallenge(ctx, challenge), nil
}

// UnenrollUserFromChallenge - Admin unenrollment
func (r *mutationResolver) UnenrollUserFromChallenge(ctx context.Context, userID string, challengeID string) (bool, error) {
	_, ok := middleware.GetUserID(ctx)
	if !ok {
		return false, fmt.Errorf("user not authenticated")
	}

	err := r.DB.Queries.UnenrollUserFromChallenge(ctx, sqlc.UnenrollUserFromChallengeParams{
		Userid:      userID,
		Challengeid: challengeID,
	})
	if err != nil {
		return false, fmt.Errorf("failed to unenroll user from challenge: %w", err)
	}

	r.Cache.InvalidateUser(userID)
	r.Cache.InvalidateChallenge(challengeID)

	return true, nil
}

// BulkEnrollUsersInChallenge - Bulk enrollment for admin/M2M
func (r *mutationResolver) BulkEnrollUsersInChallenge(ctx context.Context, target model.EnrollmentTargetInput, challengeID string) ([]model.Challenge, error) {
	adminID, ok := middleware.GetUserID(ctx)
	if !ok || adminID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Resolve target to user IDs
	userIds, err := r.resolveEnrollmentTarget(ctx, target)
	if err != nil {
		return nil, err
	}

	if len(userIds) == 0 {
		return []model.Challenge{}, nil // No users to enroll
	}

	// Load challenge for authorization
	thunk := r.Loaders.ChallengeByIDLoader.Load(ctx, challengeID)
	challenge, err := thunk()
	if err != nil {
		return nil, fmt.Errorf("challenge not found: %w", err)
	}

	// Bulk enroll
	err = r.DB.Queries.BulkEnrollUsersInChallenge(ctx, sqlc.BulkEnrollUsersInChallengeParams{
		Userids:     userIds,
		Challengeid: challengeID,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to bulk enroll users: %w", err)
	}

	// Cache invalidation
	for _, userID := range userIds {
		r.Cache.InvalidateUser(userID)
	}
	r.Cache.InvalidateChallenge(challengeID)

	// Return challenge for each user (same challenge, no dataloader needed)
	translatedChallenge := r.ApplyTranslationToChallenge(ctx, challenge)
	result := make([]model.Challenge, len(userIds))
	for i := range result {
		result[i] = *translatedChallenge
	}

	return result, nil
}

// BulkUnenrollUsersFromChallenge - Bulk unenrollment
func (r *mutationResolver) BulkUnenrollUsersFromChallenge(ctx context.Context, target model.EnrollmentTargetInput, challengeID string) (bool, error) {
	_, ok := middleware.GetUserID(ctx)
	if !ok {
		return false, fmt.Errorf("user not authenticated")
	}

	// Resolve target to user IDs
	userIds, err := r.resolveEnrollmentTarget(ctx, target)
	if err != nil {
		return false, err
	}

	if len(userIds) == 0 {
		return true, nil // No users to unenroll
	}

	err = r.DB.Queries.BulkUnenrollUsersFromChallenge(ctx, sqlc.BulkUnenrollUsersFromChallengeParams{
		Challengeid: challengeID,
		Userids:     userIds,
	})
	if err != nil {
		return false, fmt.Errorf("failed to bulk unenroll users: %w", err)
	}

	for _, userID := range userIds {
		r.Cache.InvalidateUser(userID)
	}
	r.Cache.InvalidateChallenge(challengeID)

	return true, nil
}

// CompleteChallenge is the resolver for the completeChallenge field.
func (r *mutationResolver) CompleteChallenge(ctx context.Context, userID string, challengeID string, completedAt *scalars.DateTime) (*model.Challenge, error) {
	// Get authenticated admin ID for authorization
	_, ok := middleware.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Load challenge to verify it exists
	thunk := r.Loaders.ChallengeByIDLoader.Load(ctx, challengeID)
	challenge, err := thunk()
	if err != nil {
		return nil, fmt.Errorf("challenge not found: %w", err)
	}

	// Convert optional completedAt parameter
	var completedAtTime *time.Time
	if completedAt != nil {
		completedAtTime = &completedAt.Time
	}

	// Complete the challenge
	_, err = r.DB.Queries.CompleteUserChallenge(ctx, sqlc.CompleteUserChallengeParams{
		Userid:      userID,
		Challengeid: challengeID,
		Completedat: completedAtTime,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to complete challenge: %w", err)
	}

	// Cache invalidation
	r.Cache.InvalidateUser(userID)
	r.Cache.InvalidateChallenge(challengeID)

	// Return challenge with translations
	return r.ApplyTranslationToChallenge(ctx, challenge), nil
}

// UncompleteChallenge is the resolver for the uncompleteChallenge field.
func (r *mutationResolver) UncompleteChallenge(ctx context.Context, userID string, challengeID string) (bool, error) {
	// Get authenticated admin ID for authorization
	_, ok := middleware.GetUserID(ctx)
	if !ok {
		return false, fmt.Errorf("user not authenticated")
	}

	// Delete the completion record
	err := r.DB.Queries.UncompleteUserFromChallenge(ctx, sqlc.UncompleteUserFromChallengeParams{
		Userid:      userID,
		Challengeid: challengeID,
	})
	if err != nil {
		return false, fmt.Errorf("failed to uncomplete challenge: %w", err)
	}

	// Cache invalidation
	r.Cache.InvalidateUser(userID)
	r.Cache.InvalidateChallenge(challengeID)

	return true, nil
}

// BulkCompleteChallenges is the resolver for the bulkCompleteChallenges field.
func (r *mutationResolver) BulkCompleteChallenges(ctx context.Context, target model.EnrollmentTargetInput, challengeID string, completedAt *scalars.DateTime) ([]model.Challenge, error) {
	// Get authenticated admin ID for authorization
	_, ok := middleware.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Resolve target to user IDs
	userIds, err := r.resolveEnrollmentTarget(ctx, target)
	if err != nil {
		return nil, err
	}

	if len(userIds) == 0 {
		return []model.Challenge{}, nil // No users to complete
	}

	// Load challenge to verify it exists
	thunk := r.Loaders.ChallengeByIDLoader.Load(ctx, challengeID)
	challenge, err := thunk()
	if err != nil {
		return nil, fmt.Errorf("challenge not found: %w", err)
	}

	// Convert optional completedAt parameter
	var completedAtTimestamp pgtype.Timestamptz
	if completedAt != nil {
		completedAtTimestamp = pgtype.Timestamptz{
			Time:  completedAt.Time,
			Valid: true,
		}
	}

	// Bulk complete
	err = r.DB.Queries.BulkCompleteChallenges(ctx, sqlc.BulkCompleteChallengesParams{
		Userids:     userIds,
		Challengeid: challengeID,
		Completedat: completedAtTimestamp,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to bulk complete challenges: %w", err)
	}

	// Cache invalidation
	for _, userID := range userIds {
		r.Cache.InvalidateUser(userID)
	}
	r.Cache.InvalidateChallenge(challengeID)

	// Return challenge for each user (same challenge, no dataloader needed)
	translatedChallenge := r.ApplyTranslationToChallenge(ctx, challenge)
	result := make([]model.Challenge, len(userIds))
	for i := range result {
		result[i] = *translatedChallenge
	}

	return result, nil
}

// Challenge is the resolver for the challenge field.
func (r *queryResolver) Challenge(ctx context.Context, id string) (*model.Challenge, error) {
	// Use translation-aware wrapper to fetch challenge
	return r.LoadChallengeWithTranslation(ctx, id)
}

// Challenges is the resolver for the challenges field.
func (r *queryResolver) Challenges(ctx context.Context, filter *model.ChallengeFilter, first *int, after *string, last *int, before *string) (*model.ChallengeConnection, error) {
	// Build cache key from filter and pagination parameters
	cacheKeyParams := buildChallengeCacheKeyParams(filter, first, after, last, before)
	cacheKey := cache.ChallengesFilterKey(cacheKeyParams)
	countCacheKey := cache.ChallengesCountKey(cacheKeyParams)

	// Check cache for connection result
	if cached, ok := r.Cache.Get(cacheKey); ok {
		if connection, ok := cached.(*model.ChallengeConnection); ok {
			return connection, nil
		}
	}

	// Decode cursors if provided
	var afterCursor, beforeCursor *string
	if after != nil && *after != "" {
		decoded, err := pagination.DecodeCursor(*after)
		if err != nil {
			return nil, fmt.Errorf("invalid after cursor: %w", err)
		}
		afterCursor = &decoded
	}
	if before != nil && *before != "" {
		decoded, err := pagination.DecodeCursor(*before)
		if err != nil {
			return nil, fmt.Errorf("invalid before cursor: %w", err)
		}
		beforeCursor = &decoded
	}

	// Build database query parameters for cursor pagination
	params, err := buildChallengeFilterParamsCursor(filter, first, afterCursor, last, beforeCursor)
	if err != nil {
		return nil, err
	}

	// Query database with cursor pagination
	rows, err := r.DB.Queries.GetChallengesFilteredCursor(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to query challenges: %w", err)
	}

	// Query total count (check cache first)
	var totalCount int64
	countCached := false
	if cachedCount, ok := r.Cache.Get(countCacheKey); ok {
		if count, ok := cachedCount.(int64); ok {
			totalCount = count
			countCached = true
		}
	}

	// If not in cache, query database
	if !countCached {
		countParams := buildCountChallengesFilterParams(filter)
		totalCount, err = r.DB.Queries.CountChallengesFiltered(ctx, countParams)
		if err != nil {
			return nil, fmt.Errorf("failed to count challenges: %w", err)
		}

		// Store count in cache
		r.Cache.Set(countCacheKey, totalCount)
	}

	// Determine requested limit and check if there are more results
	requestedLimit := 10 // default
	if first != nil {
		requestedLimit = *first
	} else if last != nil {
		requestedLimit = *last
	}

	hasMore := len(rows) > requestedLimit
	challengeRows := rows
	if hasMore {
		// Trim the extra record we fetched for hasMore detection
		challengeRows = rows[:requestedLimit]
	}

	// If backward pagination, reverse the results
	if last != nil {
		for i, j := 0, len(challengeRows)-1; i < j; i, j = i+1, j-1 {
			challengeRows[i], challengeRows[j] = challengeRows[j], challengeRows[i]
		}
	}

	// Convert to GraphQL model
	modelChallenges := make([]model.Challenge, len(challengeRows))
	for i, row := range challengeRows {
		challenge := convertGetChallengesFilteredCursorRowToChallenge(row)
		modelChallenges[i] = *challenge
	}

	// Build connection using pagination helper
	connection := pagination.BuildChallengeConnection(pagination.BuildChallengeConnectionParams{
		Challenges:      modelChallenges,
		RequestedFirst:  first,
		RequestedLast:   last,
		RequestedAfter:  after,
		RequestedBefore: before,
		TotalCount:      int(totalCount),
		HasMore:         hasMore,
	})

	// Store in cache
	r.Cache.Set(cacheKey, connection)

	return connection, nil
}
