package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"time"

	"github.com/bcc-media/wayfarer/internal/cache"
	"github.com/bcc-media/wayfarer/internal/database/sqlc"
	"github.com/bcc-media/wayfarer/internal/graph/api/model"
	"github.com/bcc-media/wayfarer/internal/graph/scalars"
	"github.com/bcc-media/wayfarer/internal/middleware"
	"github.com/bcc-media/wayfarer/internal/ulid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Body is the resolver for the body field.
func (r *consentResolver) Body(ctx context.Context, obj *model.Consent) (*model.MarkdownText, error) {
	return &model.MarkdownText{
		Markdown: obj.BodyMarkdown,
	}, nil
}

// UserHistory is the resolver for the userHistory field.
func (r *consentResolver) UserHistory(ctx context.Context, obj *model.Consent) ([]model.UserConsentHistoryEntry, error) {
	// Get user ID from context
	userID, ok := middleware.GetUserID(ctx)
	if !ok || userID == "" {
		// No authenticated user, return empty history
		return []model.UserConsentHistoryEntry{}, nil
	}

	// Get history for this consent key for the current user
	rows, err := r.DB.Queries.GetUserConsentHistoryByUserAndKey(ctx, sqlc.GetUserConsentHistoryByUserAndKeyParams{
		UserID:     userID,
		ConsentKey: obj.Key,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get user consent history: %w", err)
	}

	historyEntries := make([]model.UserConsentHistoryEntry, len(rows))
	for i, row := range rows {
		action := model.ConsentActionAccepted
		if row.Action == "REJECTED" {
			action = model.ConsentActionRejected
		}

		var externalTimestamp *scalars.DateTime
		if row.ExternalTimestamp.Valid {
			dt := scalars.DateTime{Time: row.ExternalTimestamp.Time}
			externalTimestamp = &dt
		}

		// Load the consent for this history entry
		consent, err := r.LoadConsentWithTranslation(ctx, row.ConsentID)
		if err != nil {
			return nil, fmt.Errorf("failed to load consent: %w", err)
		}

		entry := model.UserConsentHistoryEntry{
			ID:                row.ID,
			Consent:           consent,
			Action:            action,
			OccurredAt:        scalars.DateTime{Time: row.OccurredAt.Time},
			Source:            row.Source,
			ExternalConsentID: row.ExternalConsentID,
			ExternalTimestamp: externalTimestamp,
		}

		historyEntries[i] = entry
	}

	return historyEntries, nil
}

// TranslationStatus is the resolver for the translationStatus field.
func (r *consentResolver) TranslationStatus(ctx context.Context, obj *model.Consent) ([]model.TranslationFieldStatus, error) {
	return r.consentTranslationStatus(ctx, obj.ID)
}

// AcceptConsent is the resolver for the acceptConsent field.
func (r *mutationResolver) AcceptConsent(ctx context.Context, consentID string) (*model.UserConsent, error) {
	// Get current user from context
	userID, ok := middleware.GetUserID(ctx)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Verify consent exists and is published
	consent, err := r.DB.Queries.GetConsentByID(ctx, consentID)
	if err != nil {
		return nil, fmt.Errorf("consent not found: %w", err)
	}

	if !consent.PublishedAt.Valid || consent.PublishedAt.Time.After(time.Now()) {
		return nil, fmt.Errorf("consent is not published yet")
	}

	// Block if consent is remote (must be accepted externally)
	if consent.IsRemote {
		return nil, fmt.Errorf("cannot accept remote consent locally, must be accepted via external system")
	}

	// Check if user already has an action on this consent
	existing, err := r.DB.Queries.GetLatestUserConsentActionByKey(ctx, sqlc.GetLatestUserConsentActionByKeyParams{
		UserID:     userID,
		ConsentKey: consent.Key,
	})
	if err == nil && existing.Action == "ACCEPTED" {
		// User already accepted this consent
		return &model.UserConsent{
			ID:         existing.ID,
			ConsentID:  existing.ConsentID,
			Action:     model.ConsentActionAccepted,
			ActionDate: scalars.DateTime{Time: existing.OccurredAt.Time},
		}, nil
	}

	// Create new user consent history entry
	occurredAt := pgtype.Timestamptz{Time: time.Now(), Valid: true}
	historyEntry, err := r.DB.Queries.CreateUserConsentHistory(ctx, sqlc.CreateUserConsentHistoryParams{
		ID:                ulid.NewUserConsentHistoryID(),
		UserID:            userID,
		ConsentID:         consentID,
		ConsentKey:        consent.Key,
		Action:            "ACCEPTED",
		OccurredAt:        occurredAt,
		Source:            nil, // NULL for local
		ExternalConsentID: nil,
		ExternalTimestamp: pgtype.Timestamptz{},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to accept consent: %w", err)
	}

	// Invalidate user cache
	r.Cache.Delete(cache.UserKey(userID))

	return &model.UserConsent{
		ID:         historyEntry.ID,
		ConsentID:  historyEntry.ConsentID,
		Action:     model.ConsentActionAccepted,
		ActionDate: scalars.DateTime{Time: historyEntry.OccurredAt.Time},
	}, nil
}

// RejectConsent is the resolver for the rejectConsent field.
func (r *mutationResolver) RejectConsent(ctx context.Context, consentID string) (*model.UserConsent, error) {
	// Get current user from context
	userID, ok := middleware.GetUserID(ctx)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Verify consent exists and is published
	consent, err := r.DB.Queries.GetConsentByID(ctx, consentID)
	if err != nil {
		return nil, fmt.Errorf("consent not found: %w", err)
	}

	if !consent.PublishedAt.Valid || consent.PublishedAt.Time.After(time.Now()) {
		return nil, fmt.Errorf("consent is not published yet")
	}

	// Block if consent is remote (must be rejected externally)
	if consent.IsRemote {
		return nil, fmt.Errorf("cannot reject remote consent locally, must be managed via external system")
	}

	// Check if user already rejected this consent
	existing, err := r.DB.Queries.GetLatestUserConsentActionByKey(ctx, sqlc.GetLatestUserConsentActionByKeyParams{
		UserID:     userID,
		ConsentKey: consent.Key,
	})
	if err == nil && existing.Action == "REJECTED" {
		// User already rejected this consent
		return &model.UserConsent{
			ID:         existing.ID,
			ConsentID:  existing.ConsentID,
			Action:     model.ConsentActionRejected,
			ActionDate: scalars.DateTime{Time: existing.OccurredAt.Time},
		}, nil
	}

	// Create new user consent history entry
	occurredAt := pgtype.Timestamptz{Time: time.Now(), Valid: true}
	historyEntry, err := r.DB.Queries.CreateUserConsentHistory(ctx, sqlc.CreateUserConsentHistoryParams{
		ID:                ulid.NewUserConsentHistoryID(),
		UserID:            userID,
		ConsentID:         consentID,
		ConsentKey:        consent.Key,
		Action:            "REJECTED",
		OccurredAt:        occurredAt,
		Source:            nil, // NULL for local
		ExternalConsentID: nil,
		ExternalTimestamp: pgtype.Timestamptz{},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to reject consent: %w", err)
	}

	// Invalidate user cache
	r.Cache.Delete(cache.UserKey(userID))

	return &model.UserConsent{
		ID:         historyEntry.ID,
		ConsentID:  historyEntry.ConsentID,
		Action:     model.ConsentActionRejected,
		ActionDate: scalars.DateTime{Time: historyEntry.OccurredAt.Time},
	}, nil
}

// CreateConsent is the resolver for the createConsent field.
func (r *mutationResolver) CreateConsent(ctx context.Context, key string, title string, shortText *string, body string, url *string, publishedAt *scalars.DateTime, isRemote *bool, managedBy *string) (*model.Consent, error) {
	// Get next version for this consent key
	nextVersion, err := r.DB.Queries.GetNextVersionForConsentKey(ctx, key)
	if err != nil {
		return nil, fmt.Errorf("failed to get next version: %w", err)
	}

	var publishedAtPG pgtype.Timestamptz
	if publishedAt != nil {
		publishedAtPG = pgtype.Timestamptz{Time: publishedAt.Time, Valid: true}
	}

	var isRemoteBool bool
	if isRemote != nil {
		isRemoteBool = *isRemote
	}

	// Default short text to empty string if not provided
	var shortTextStr string
	if shortText != nil {
		shortTextStr = *shortText
	}

	// Create consent
	consent, err := r.DB.Queries.CreateConsent(ctx, sqlc.CreateConsentParams{
		ID:          ulid.NewConsentID(),
		Key:         key,
		Version:     nextVersion,
		Title:       title,
		ShortText:   shortTextStr,
		Body:        string(body),
		Url:         url,
		PublishedAt: publishedAtPG,
		IsRemote:    isRemoteBool,
		ManagedBy:   managedBy,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create consent: %w", err)
	}

	// Invalidate latest consents cache
	r.Cache.Delete(cache.LatestConsentsKey())

	var publishedAtOut *scalars.DateTime
	if consent.PublishedAt.Valid {
		dt := scalars.DateTime{Time: consent.PublishedAt.Time}
		publishedAtOut = &dt
	}

	managementType := model.ConsentManagementTypeLocal
	if consent.IsRemote {
		managementType = model.ConsentManagementTypeRemote
	}

	return &model.Consent{
		ID:             consent.ID,
		Key:            consent.Key,
		Version:        int(consent.Version),
		Title:          consent.Title,
		ShortText:      consent.ShortText,
		BodyMarkdown:   consent.Body,
		URL:            consent.Url,
		PublishedAt:    publishedAtOut,
		ManagementType: managementType,
		ManagedBy:      consent.ManagedBy,
	}, nil
}

// UpdateConsent is the resolver for the updateConsent field.
func (r *mutationResolver) UpdateConsent(ctx context.Context, id string, title *string, shortText *string, body *string, url *string, publishedAt *scalars.DateTime, managedBy *string) (*model.Consent, error) {
	var titleStr, shortTextStr, bodyStr, urlStr, managedByStr string
	if title != nil {
		titleStr = *title
	}
	if shortText != nil {
		shortTextStr = *shortText
	}
	if body != nil {
		bodyStr = string(*body)
	}
	if url != nil {
		urlStr = *url
	}
	if managedBy != nil {
		managedByStr = *managedBy
	}

	var publishedAtPG pgtype.Timestamptz
	if publishedAt != nil {
		publishedAtPG = pgtype.Timestamptz{Time: publishedAt.Time, Valid: true}
	}

	consent, err := r.DB.Queries.UpdateConsent(ctx, sqlc.UpdateConsentParams{
		ID:          id,
		Title:       titleStr,
		ShortText:   shortTextStr,
		Body:        bodyStr,
		Url:         urlStr,
		ManagedBy:   managedByStr,
		PublishedAt: publishedAtPG,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update consent: %w", err)
	}

	// Invalidate caches
	r.Cache.Delete(cache.ConsentKey(id))
	r.Cache.Delete(cache.LatestConsentsKey())

	var publishedAtOut *scalars.DateTime
	if consent.PublishedAt.Valid {
		dt := scalars.DateTime{Time: consent.PublishedAt.Time}
		publishedAtOut = &dt
	}

	managementType := model.ConsentManagementTypeLocal
	if consent.IsRemote {
		managementType = model.ConsentManagementTypeRemote
	}

	return &model.Consent{
		ID:             consent.ID,
		Key:            consent.Key,
		Version:        int(consent.Version),
		Title:          consent.Title,
		ShortText:      consent.ShortText,
		BodyMarkdown:   consent.Body,
		URL:            consent.Url,
		PublishedAt:    publishedAtOut,
		ManagementType: managementType,
		ManagedBy:      consent.ManagedBy,
	}, nil
}

// AdminSetUserConsent is the resolver for the adminSetUserConsent field.
func (r *mutationResolver) AdminSetUserConsent(ctx context.Context, userID string, consentID string, action model.ConsentAction) (*model.UserConsentHistoryEntry, error) {
	// Get admin user ID from context for audit tracking
	adminUserID, ok := middleware.GetUserID(ctx)
	if !ok || adminUserID == "" {
		return nil, fmt.Errorf("admin not authenticated")
	}

	// Validate target user exists
	_, err := r.DB.Queries.GetUserByID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	// Fetch consent and validate
	consent, err := r.DB.Queries.GetConsentByID(ctx, consentID)
	if err != nil {
		return nil, fmt.Errorf("consent not found: %w", err)
	}

	// Block remote consents - must be managed externally
	if consent.IsRemote {
		return nil, fmt.Errorf("cannot set consent for remote-managed consents")
	}

	// Convert action enum to string
	actionStr := "ACCEPTED"
	if action == model.ConsentActionRejected {
		actionStr = "REJECTED"
	}

	// Create history entry with admin's user ID as source
	source := adminUserID
	historyEntry, err := r.DB.Queries.CreateUserConsentHistory(ctx, sqlc.CreateUserConsentHistoryParams{
		ID:                ulid.NewUserConsentHistoryID(),
		UserID:            userID,
		ConsentID:         consentID,
		ConsentKey:        consent.Key,
		Action:            actionStr,
		OccurredAt:        pgtype.Timestamptz{Time: time.Now(), Valid: true},
		Source:            &source,
		ExternalConsentID: nil,
		ExternalTimestamp: pgtype.Timestamptz{},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create consent history: %w", err)
	}

	// Invalidate target user's cache
	r.Cache.Delete(cache.UserKey(userID))

	// Load consent for return value
	consentModel, err := r.LoadConsentWithTranslation(ctx, historyEntry.ConsentID)
	if err != nil {
		return nil, fmt.Errorf("failed to load consent: %w", err)
	}

	return &model.UserConsentHistoryEntry{
		ID:                historyEntry.ID,
		Consent:           consentModel,
		Action:            action,
		OccurredAt:        scalars.DateTime{Time: historyEntry.OccurredAt.Time},
		Source:            historyEntry.Source,
		ExternalConsentID: historyEntry.ExternalConsentID,
		ExternalTimestamp: nil,
	}, nil
}

// Consents is the resolver for the consents field.
func (r *queryResolver) Consents(ctx context.Context) ([]model.Consent, error) {
	rows, err := r.DB.Queries.GetAllLatestPublishedConsents(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get consents: %w", err)
	}

	consents := make([]model.Consent, len(rows))
	for i, row := range rows {
		var publishedAt *scalars.DateTime
		if row.PublishedAt.Valid {
			dt := scalars.DateTime{Time: row.PublishedAt.Time}
			publishedAt = &dt
		}

		managementType := model.ConsentManagementTypeLocal
		if row.IsRemote {
			managementType = model.ConsentManagementTypeRemote
		}

		consent := model.Consent{
			ID:             row.ID,
			Key:            row.Key,
			Version:        int(row.Version),
			Title:          row.Title,
			ShortText:      row.ShortText,
			BodyMarkdown:   row.Body,
			URL:            row.Url,
			PublishedAt:    publishedAt,
			ManagementType: managementType,
			ManagedBy:      row.ManagedBy,
		}

		// Apply translation
		consents[i] = *r.ApplyTranslationToConsent(ctx, &consent)
	}

	return consents, nil
}

// Consent is the resolver for the consent field.
func (r *queryResolver) Consent(ctx context.Context, id string) (*model.Consent, error) {
	return r.LoadConsentWithTranslation(ctx, id)
}

// PendingConsents is the resolver for the pendingConsents field.
func (r *queryResolver) PendingConsents(ctx context.Context) ([]model.Consent, error) {
	userID, ok := middleware.GetUserID(ctx)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	rows, err := r.DB.Queries.GetMissingConsentsForUserWithRejections(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get pending consents: %w", err)
	}

	consents := make([]model.Consent, len(rows))
	for i, row := range rows {
		var publishedAt *scalars.DateTime
		if row.PublishedAt.Valid {
			dt := scalars.DateTime{Time: row.PublishedAt.Time}
			publishedAt = &dt
		}

		managementType := model.ConsentManagementTypeLocal
		if row.IsRemote {
			managementType = model.ConsentManagementTypeRemote
		}

		consent := model.Consent{
			ID:             row.ID,
			Key:            row.Key,
			Version:        int(row.Version),
			Title:          row.Title,
			ShortText:      row.ShortText,
			BodyMarkdown:   row.Body,
			URL:            row.Url,
			PublishedAt:    publishedAt,
			ManagementType: managementType,
			ManagedBy:      row.ManagedBy,
		}

		// Apply translation
		consents[i] = *r.ApplyTranslationToConsent(ctx, &consent)
	}

	return consents, nil
}

// Consent is the resolver for the consent field.
func (r *userConsentResolver) Consent(ctx context.Context, obj *model.UserConsent) (*model.Consent, error) {
	return r.LoadConsentWithTranslation(ctx, obj.ConsentID)
}

// Consent resolver for UserConsentHistoryEntry - returns already populated field
func (r *userConsentHistoryEntryResolver) Consent(ctx context.Context, obj *model.UserConsentHistoryEntry) (*model.Consent, error) {
	return obj.Consent, nil
}

// Consent returns ConsentResolver implementation.
func (r *Resolver) Consent() ConsentResolver { return &consentResolver{r} }

// UserConsent returns UserConsentResolver implementation.
func (r *Resolver) UserConsent() UserConsentResolver { return &userConsentResolver{r} }

// UserConsentHistoryEntry returns UserConsentHistoryEntryResolver implementation.
func (r *Resolver) UserConsentHistoryEntry() UserConsentHistoryEntryResolver {
	return &userConsentHistoryEntryResolver{r}
}

type consentResolver struct{ *Resolver }
type userConsentResolver struct{ *Resolver }
type userConsentHistoryEntryResolver struct{ *Resolver }
