package api

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/bcc-media/wayfarer/internal/cache"
	"github.com/bcc-media/wayfarer/internal/graph/api/model"
	"github.com/bcc-media/wayfarer/internal/graph/pagination"
	"github.com/bcc-media/wayfarer/internal/middleware"
)

// Translations is the resolver for the translations field.
func (r *externalContentResolver) Translations(ctx context.Context, obj *model.ExternalContent) ([]model.ExternalContentTranslation, error) {
	thunk := r.Loaders.ExternalContentTranslationsLoader.Load(ctx, obj.ID)
	translations, err := thunk()
	if err != nil {
		return nil, err
	}
	return translations, nil
}

// Title is the resolver for the title field.
func (r *externalContentResolver) Title(ctx context.Context, obj *model.ExternalContent) (*string, error) {
	thunk := r.Loaders.ExternalContentTranslationsLoader.Load(ctx, obj.ID)
	translations, err := thunk()
	if err != nil {
		return nil, err
	}

	if len(translations) == 0 {
		return nil, nil
	}

	// Get language from Accept-Language header
	lang := middleware.GetLanguage(ctx)

	// Find translation matching the user's preferred language
	for _, t := range translations {
		if t.LanguageCode == lang {
			return t.Title, nil
		}
	}

	// Fallback: return first translation if preferred language not found
	return translations[0].Title, nil
}

// CreateContentAchievementFromExternalContent is the resolver for the createContentAchievementFromExternalContent field.
func (r *mutationResolver) CreateContentAchievementFromExternalContent(ctx context.Context, input model.CreateContentAchievementFromExternalContentInput) (*model.ContentAchievement, error) {
	// Convert external content IDs to ContentItemInput
	items := make([]model.ContentItemInput, len(input.ExternalContentIds))
	for i, ecID := range input.ExternalContentIds {
		items[i] = model.ContentItemInput{
			ExternalContentID: ecID,
		}
	}

	// Delegate to existing CreateContentAchievement resolver
	createInput := model.CreateContentAchievementInput{
		Name:                 input.Name,
		DescriptionPending:   input.DescriptionPending,
		DescriptionCompleted: input.DescriptionCompleted,
		ImagePending:         input.ImagePending,
		ImageCompleted:       input.ImageCompleted,
		ProjectID:            input.ProjectID,
		EventID:              input.EventID,
		ChallengeID:          input.ChallengeID,
		Points:               input.Points,
		Hidden:               input.Hidden,
		Items:                items,
	}

	return r.CreateContentAchievement(ctx, createInput)
}

// ExternalContent is the resolver for the externalContent field.
func (r *queryResolver) ExternalContent(ctx context.Context, id string) (*model.ExternalContent, error) {
	thunk := r.Loaders.ExternalContentByIDLoader.Load(ctx, id)
	content, err := thunk()
	if err != nil {
		return nil, err
	}
	return content, nil
}

// ExternalContents is the resolver for the externalContents field.
func (r *queryResolver) ExternalContents(ctx context.Context, filter model.ExternalContentFilter, sortBy *model.ExternalContentSortBy, first *int, after *string, last *int, before *string) (*model.ExternalContentConnection, error) {
	// Build cache key params
	cacheParams := buildExternalContentFilterParams(filter, sortBy, first, after, last, before)
	cacheKey := cache.ExternalContentsFilterKey(cacheParams)
	countCacheKey := cache.ExternalContentsCountKey(cacheParams)

	// Check cache for connection
	if cached, ok := r.Cache.Get(cacheKey); ok {
		if connection, ok := cached.(*model.ExternalContentConnection); ok {
			return connection, nil
		}
	}

	// Decode cursors
	var afterCursor, beforeCursor string
	if after != nil && *after != "" {
		decoded, err := pagination.DecodeCursor(*after)
		if err != nil {
			return nil, fmt.Errorf("invalid after cursor: %w", err)
		}
		afterCursor = decoded
	}
	if before != nil && *before != "" {
		decoded, err := pagination.DecodeCursor(*before)
		if err != nil {
			return nil, fmt.Errorf("invalid before cursor: %w", err)
		}
		beforeCursor = decoded
	}

	// Determine limit and offset
	requestedLimit := 10 // default
	if first != nil {
		requestedLimit = *first
	} else if last != nil {
		requestedLimit = *last
	}

	// Build query params
	queryParams := buildExternalContentSearchParams(filter, sortBy, requestedLimit+1, afterCursor, beforeCursor, last != nil)

	// Query database
	rows, err := r.DB.Queries.SearchExternalContentAdmin(ctx, queryParams)
	if err != nil {
		return nil, fmt.Errorf("failed to query external content: %w", err)
	}

	// Query total count (check cache first)
	var totalCount int64
	countCached := false
	if cachedCount, ok := r.Cache.Get(countCacheKey); ok {
		if count, ok := cachedCount.(int64); ok {
			totalCount = count
			countCached = true
		}
	}

	if !countCached {
		countParams := buildExternalContentCountParams(filter)
		totalCount, err = r.DB.Queries.CountExternalContentAdmin(ctx, countParams)
		if err != nil {
			return nil, fmt.Errorf("failed to count external content: %w", err)
		}
		r.Cache.Set(countCacheKey, totalCount)
	}

	// Determine if there are more results
	hasMore := len(rows) > requestedLimit
	if hasMore {
		rows = rows[:requestedLimit]
	}

	// If backward pagination, reverse the results
	if last != nil {
		for i, j := 0, len(rows)-1; i < j; i, j = i+1, j-1 {
			rows[i], rows[j] = rows[j], rows[i]
		}
	}

	// Convert to GraphQL model
	contents := make([]*model.ExternalContent, len(rows))
	for i, row := range rows {
		contents[i] = convertExternalContentRow(row)
	}

	// Build the connection
	connection := pagination.BuildExternalContentConnection(pagination.BuildExternalContentConnectionParams{
		ExternalContents: contents,
		RequestedFirst:   first,
		RequestedLast:    last,
		RequestedAfter:   after,
		RequestedBefore:  before,
		TotalCount:       int(totalCount),
		HasMore:          hasMore,
	})

	// Store connection in cache
	r.Cache.Set(cacheKey, connection)

	return connection, nil
}

// ExternalContent returns ExternalContentResolver implementation.
func (r *Resolver) ExternalContent() ExternalContentResolver { return &externalContentResolver{r} }

type externalContentResolver struct{ *Resolver }
