package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/bcc-media/wayfarer/internal/graph/api/model"
	"github.com/bcc-media/wayfarer/internal/services"
)

// SetCurrentProject is the resolver for the setCurrentProject field.
func (r *mutationResolver) SetCurrentProject(ctx context.Context, projectID string) (*model.Project, error) {
	return r.Resolver.setCurrentProject(ctx, projectID)
}

// SetSettings is the resolver for the setSettings field.
func (r *mutationResolver) SetSettings(ctx context.Context, input []model.SettingInput) ([]model.Setting, error) {
	return r.Resolver.setSettings(ctx, input)
}

// FrontendConfig is the resolver for the frontendConfig field.
func (r *queryResolver) FrontendConfig(ctx context.Context) (string, error) {
	configJSON, err := r.DB.Queries.GetSettingJSON(ctx, services.SettingFrontendConfig)
	if err != nil {
		return "{}", nil
	}
	return string(configJSON), nil
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) ([]model.Setting, error) {
	return r.Resolver.listSettings(ctx)
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) SetSetting(ctx context.Context, key string, value string) (*model.Setting, error) {
	return r.Resolver.setSetting(ctx, key, value)
}
*/
