package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	model1 "github.com/bcc-media/wayfarer/internal/graph/api/model"
)

// Project is the resolver for the project field.
func (r *challengeResolver) Project(ctx context.Context, obj *model1.Challenge) (*model1.Project, error) {
	panic(fmt.Errorf("not implemented: Project - project"))
}

// Event is the resolver for the event field.
func (r *challengeResolver) Event(ctx context.Context, obj *model1.Challenge) (*model1.Event, error) {
	panic(fmt.Errorf("not implemented: Event - event"))
}

// Challenges is the resolver for the challenges field.
func (r *eventResolver) Challenges(ctx context.Context, obj *model1.Event) ([]model1.Challenge, error) {
	panic(fmt.Errorf("not implemented: Challenges - challenges"))
}

// ParentProject is the resolver for the parentProject field.
func (r *eventResolver) ParentProject(ctx context.Context, obj *model1.Event) (*model1.Project, error) {
	panic(fmt.Errorf("not implemented: ParentProject - parentProject"))
}

// Project is the resolver for the project field.
func (r *listeningAchievementResolver) Project(ctx context.Context, obj *model1.ListeningAchievement) (*model1.Project, error) {
	panic(fmt.Errorf("not implemented: Project - project"))
}

// Event is the resolver for the event field.
func (r *listeningAchievementResolver) Event(ctx context.Context, obj *model1.ListeningAchievement) (*model1.Event, error) {
	panic(fmt.Errorf("not implemented: Event - event"))
}

// Challenge is the resolver for the challenge field.
func (r *listeningAchievementResolver) Challenge(ctx context.Context, obj *model1.ListeningAchievement) (*model1.Challenge, error) {
	panic(fmt.Errorf("not implemented: Challenge - challenge"))
}

// Challenges is the resolver for the challenges field.
func (r *projectResolver) Challenges(ctx context.Context, obj *model1.Project) ([]model1.Challenge, error) {
	panic(fmt.Errorf("not implemented: Challenges - challenges"))
}

// Events is the resolver for the events field.
func (r *projectResolver) Events(ctx context.Context, obj *model1.Project) ([]model1.Event, error) {
	panic(fmt.Errorf("not implemented: Events - events"))
}

// Teams is the resolver for the teams field.
func (r *projectResolver) Teams(ctx context.Context, obj *model1.Project) ([]model1.Team, error) {
	panic(fmt.Errorf("not implemented: Teams - teams"))
}

// MyTeam is the resolver for the myTeam field.
func (r *projectResolver) MyTeam(ctx context.Context, obj *model1.Project) (*model1.Team, error) {
	panic(fmt.Errorf("not implemented: MyTeam - myTeam"))
}

// Achievements is the resolver for the achievements field.
func (r *projectResolver) Achievements(ctx context.Context, obj *model1.Project) ([]model1.Achievement, error) {
	panic(fmt.Errorf("not implemented: Achievements - achievements"))
}

// Streaks is the resolver for the streaks field.
func (r *projectResolver) Streaks(ctx context.Context, obj *model1.Project) ([]model1.Streak, error) {
	panic(fmt.Errorf("not implemented: Streaks - streaks"))
}

// Project is the resolver for the project field.
func (r *readingAchievementResolver) Project(ctx context.Context, obj *model1.ReadingAchievement) (*model1.Project, error) {
	panic(fmt.Errorf("not implemented: Project - project"))
}

// Event is the resolver for the event field.
func (r *readingAchievementResolver) Event(ctx context.Context, obj *model1.ReadingAchievement) (*model1.Event, error) {
	panic(fmt.Errorf("not implemented: Event - event"))
}

// Challenge is the resolver for the challenge field.
func (r *readingAchievementResolver) Challenge(ctx context.Context, obj *model1.ReadingAchievement) (*model1.Challenge, error) {
	panic(fmt.Errorf("not implemented: Challenge - challenge"))
}

// Project is the resolver for the project field.
func (r *simpleAchievementResolver) Project(ctx context.Context, obj *model1.SimpleAchievement) (*model1.Project, error) {
	panic(fmt.Errorf("not implemented: Project - project"))
}

// Event is the resolver for the event field.
func (r *simpleAchievementResolver) Event(ctx context.Context, obj *model1.SimpleAchievement) (*model1.Event, error) {
	panic(fmt.Errorf("not implemented: Event - event"))
}

// Challenge is the resolver for the challenge field.
func (r *simpleAchievementResolver) Challenge(ctx context.Context, obj *model1.SimpleAchievement) (*model1.Challenge, error) {
	panic(fmt.Errorf("not implemented: Challenge - challenge"))
}

// Project is the resolver for the project field.
func (r *streakResolver) Project(ctx context.Context, obj *model1.Streak) (*model1.Project, error) {
	panic(fmt.Errorf("not implemented: Project - project"))
}

// Project is the resolver for the project field.
func (r *streakAchievementResolver) Project(ctx context.Context, obj *model1.StreakAchievement) (*model1.Project, error) {
	panic(fmt.Errorf("not implemented: Project - project"))
}

// Event is the resolver for the event field.
func (r *streakAchievementResolver) Event(ctx context.Context, obj *model1.StreakAchievement) (*model1.Event, error) {
	panic(fmt.Errorf("not implemented: Event - event"))
}

// Challenge is the resolver for the challenge field.
func (r *streakAchievementResolver) Challenge(ctx context.Context, obj *model1.StreakAchievement) (*model1.Challenge, error) {
	panic(fmt.Errorf("not implemented: Challenge - challenge"))
}

// Streak is the resolver for the streak field.
func (r *streakAchievementResolver) Streak(ctx context.Context, obj *model1.StreakAchievement) (*model1.Streak, error) {
	panic(fmt.Errorf("not implemented: Streak - streak"))
}

// Members is the resolver for the members field.
func (r *superTeamResolver) Members(ctx context.Context, obj *model1.SuperTeam) ([]model1.User, error) {
	panic(fmt.Errorf("not implemented: Members - members"))
}

// ParentProject is the resolver for the parentProject field.
func (r *superTeamResolver) ParentProject(ctx context.Context, obj *model1.SuperTeam) (*model1.Project, error) {
	panic(fmt.Errorf("not implemented: ParentProject - parentProject"))
}

// Teams is the resolver for the teams field.
func (r *superTeamResolver) Teams(ctx context.Context, obj *model1.SuperTeam) ([]model1.Team, error) {
	panic(fmt.Errorf("not implemented: Teams - teams"))
}

// Members is the resolver for the members field.
func (r *teamResolver) Members(ctx context.Context, obj *model1.Team) ([]model1.User, error) {
	panic(fmt.Errorf("not implemented: Members - members"))
}

// ParentProject is the resolver for the parentProject field.
func (r *teamResolver) ParentProject(ctx context.Context, obj *model1.Team) (*model1.Project, error) {
	panic(fmt.Errorf("not implemented: ParentProject - parentProject"))
}

// SuperTeam is the resolver for the superTeam field.
func (r *teamResolver) SuperTeam(ctx context.Context, obj *model1.Team) (*model1.SuperTeam, error) {
	panic(fmt.Errorf("not implemented: SuperTeam - superTeam"))
}

// Church is the resolver for the church field.
func (r *userResolver) Church(ctx context.Context, obj *model1.User) (*model1.Church, error) {
	panic(fmt.Errorf("not implemented: Church - church"))
}

// Projects is the resolver for the projects field.
func (r *userResolver) Projects(ctx context.Context, obj *model1.User) ([]model1.Project, error) {
	panic(fmt.Errorf("not implemented: Projects - projects"))
}

// Events is the resolver for the events field.
func (r *userResolver) Events(ctx context.Context, obj *model1.User) ([]model1.Event, error) {
	panic(fmt.Errorf("not implemented: Events - events"))
}

// Teams is the resolver for the teams field.
func (r *userResolver) Teams(ctx context.Context, obj *model1.User) ([]model1.Team, error) {
	panic(fmt.Errorf("not implemented: Teams - teams"))
}

// SuperTeams is the resolver for the superTeams field.
func (r *userResolver) SuperTeams(ctx context.Context, obj *model1.User) ([]model1.SuperTeam, error) {
	panic(fmt.Errorf("not implemented: SuperTeams - superTeams"))
}

// Challenge returns ChallengeResolver implementation.
func (r *Resolver) Challenge() ChallengeResolver { return &challengeResolver{r} }

// Event returns EventResolver implementation.
func (r *Resolver) Event() EventResolver { return &eventResolver{r} }

// ListeningAchievement returns ListeningAchievementResolver implementation.
func (r *Resolver) ListeningAchievement() ListeningAchievementResolver {
	return &listeningAchievementResolver{r}
}

// Project returns ProjectResolver implementation.
func (r *Resolver) Project() ProjectResolver { return &projectResolver{r} }

// ReadingAchievement returns ReadingAchievementResolver implementation.
func (r *Resolver) ReadingAchievement() ReadingAchievementResolver {
	return &readingAchievementResolver{r}
}

// SimpleAchievement returns SimpleAchievementResolver implementation.
func (r *Resolver) SimpleAchievement() SimpleAchievementResolver {
	return &simpleAchievementResolver{r}
}

// Streak returns StreakResolver implementation.
func (r *Resolver) Streak() StreakResolver { return &streakResolver{r} }

// StreakAchievement returns StreakAchievementResolver implementation.
func (r *Resolver) StreakAchievement() StreakAchievementResolver {
	return &streakAchievementResolver{r}
}

// SuperTeam returns SuperTeamResolver implementation.
func (r *Resolver) SuperTeam() SuperTeamResolver { return &superTeamResolver{r} }

// Team returns TeamResolver implementation.
func (r *Resolver) Team() TeamResolver { return &teamResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type challengeResolver struct{ *Resolver }
type eventResolver struct{ *Resolver }
type listeningAchievementResolver struct{ *Resolver }
type projectResolver struct{ *Resolver }
type readingAchievementResolver struct{ *Resolver }
type simpleAchievementResolver struct{ *Resolver }
type streakResolver struct{ *Resolver }
type streakAchievementResolver struct{ *Resolver }
type superTeamResolver struct{ *Resolver }
type teamResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
