package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"time"

	"github.com/bcc-media/wayfarer/internal/cache"
	"github.com/bcc-media/wayfarer/internal/graph/api/model"
	"github.com/bcc-media/wayfarer/internal/graph/pagination"
	"github.com/bcc-media/wayfarer/internal/graph/scalars"
	"github.com/bcc-media/wayfarer/internal/loaders"
	"github.com/bcc-media/wayfarer/internal/middleware"
)

// CreateStreak is the resolver for the createStreak field.
func (r *mutationResolver) CreateStreak(ctx context.Context, input model.CreateStreakInput) (*model.Streak, error) {
	panic(fmt.Errorf("not implemented: CreateStreak - createStreak"))
}

// UpdateStreak is the resolver for the updateStreak field.
func (r *mutationResolver) UpdateStreak(ctx context.Context, id string, input model.UpdateStreakInput) (*model.Streak, error) {
	panic(fmt.Errorf("not implemented: UpdateStreak - updateStreak"))
}

// DeleteStreak is the resolver for the deleteStreak field.
func (r *mutationResolver) DeleteStreak(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteStreak - deleteStreak"))
}

// Streak is the resolver for the streak field.
func (r *queryResolver) Streak(ctx context.Context, id string) (*model.Streak, error) {
	// Use translation-aware wrapper to fetch streak
	return r.LoadStreakWithTranslation(ctx, id)
}

// Streaks is the resolver for the streaks field.
func (r *queryResolver) Streaks(ctx context.Context, filter *model.StreakFilter, first *int, after *string, last *int, before *string) (*model.StreakConnection, error) {
	// Build cache key from filter and pagination parameters
	cacheKeyParams := buildStreakCacheKeyParams(filter, first, after, last, before)
	cacheKey := cache.StreaksFilterKey(cacheKeyParams)
	countCacheKey := cache.StreaksCountKey(cacheKeyParams)

	// Check cache for connection result
	if cached, ok := r.Cache.Get(cacheKey); ok {
		if connection, ok := cached.(*model.StreakConnection); ok {
			return connection, nil
		}
	}

	// Decode cursors if provided
	var afterCursor, beforeCursor *string
	if after != nil && *after != "" {
		decoded, err := pagination.DecodeCursor(*after)
		if err != nil {
			return nil, fmt.Errorf("invalid after cursor: %w", err)
		}
		afterCursor = &decoded
	}
	if before != nil && *before != "" {
		decoded, err := pagination.DecodeCursor(*before)
		if err != nil {
			return nil, fmt.Errorf("invalid before cursor: %w", err)
		}
		beforeCursor = &decoded
	}

	// Build database query parameters for cursor pagination
	params, err := buildStreakFilterParamsCursor(filter, first, afterCursor, last, beforeCursor)
	if err != nil {
		return nil, err
	}

	// Query database with cursor pagination
	rows, err := r.DB.Queries.GetStreaksFilteredCursor(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to query streaks: %w", err)
	}

	// Query total count (check cache first)
	var totalCount int64
	countCached := false
	if cachedCount, ok := r.Cache.Get(countCacheKey); ok {
		if count, ok := cachedCount.(int64); ok {
			totalCount = count
			countCached = true
		}
	}

	// If not in cache, query database
	if !countCached {
		countParams := buildCountStreaksFilterParams(filter)
		totalCount, err = r.DB.Queries.CountStreaksFiltered(ctx, countParams)
		if err != nil {
			return nil, fmt.Errorf("failed to count streaks: %w", err)
		}

		// Store count in cache
		r.Cache.Set(countCacheKey, totalCount)
	}

	// Determine requested limit and check if there are more results
	requestedLimit := 10 // default
	if first != nil {
		requestedLimit = *first
	} else if last != nil {
		requestedLimit = *last
	}

	hasMore := len(rows) > requestedLimit
	streaks := rows
	if hasMore {
		// Trim the extra record we fetched for hasMore detection
		streaks = rows[:requestedLimit]
	}

	// If backward pagination, reverse the results
	if last != nil {
		for i, j := 0, len(streaks)-1; i < j; i, j = i+1, j-1 {
			streaks[i], streaks[j] = streaks[j], streaks[i]
		}
	}

	// Convert to GraphQL model
	modelStreaks := make([]model.Streak, len(streaks))
	for i, row := range streaks {
		modelStreaks[i] = model.Streak{
			ID:          row.ID,
			Name:        row.Name,
			Description: row.Description,
			ProjectID:   row.ProjectID,
		}
	}

	// Build the connection
	connection := pagination.BuildStreakConnection(pagination.BuildStreakConnectionParams{
		Streaks:         modelStreaks,
		RequestedFirst:  first,
		RequestedLast:   last,
		RequestedAfter:  after,
		RequestedBefore: before,
		TotalCount:      int(totalCount),
		HasMore:         hasMore,
	})

	// Store connection in cache
	r.Cache.Set(cacheKey, connection)

	return connection, nil
}

// Status is the resolver for the status field.
func (r *streakResolver) Status(ctx context.Context, obj *model.Streak) (int, error) {
	// Get current user ID
	currentUserID, ok := middleware.GetUserID(ctx)
	if !ok || currentUserID == "" {
		return 0, nil // Return 0 for unauthenticated users
	}

	// Load user's activity for this streak
	key := loaders.UserStreakActivityKey{UserID: currentUserID, StreakID: obj.ID}
	thunk := r.Loaders.UserStreakActivityLoader.Load(ctx, key)
	activities, err := thunk()
	if err != nil {
		return 0, fmt.Errorf("failed to load user streak activity: %w", err)
	}

	// If no activities, streak is 0
	if len(activities) == 0 {
		return 0, nil
	}

	// Load relevant days for this streak
	relevantDaysThunk := r.Loaders.RelevantDaysByStreakLoader.Load(ctx, obj.ID)
	relevantDays, err := relevantDaysThunk()
	if err != nil {
		return 0, fmt.Errorf("failed to load relevant days: %w", err)
	}

	// Build a set of activity dates for fast lookup (truncate to midnight for comparison)
	activityDateSet := make(map[time.Time]bool)
	for _, activity := range activities {
		if activity.ActivityDate.Valid {
			activityDateSet[activity.ActivityDate.Time.Truncate(24*time.Hour)] = true
		}
	}

	// Calculate current streak by counting consecutive relevant days with activity
	// Start from today and work backwards
	today := time.Now().UTC().Truncate(24 * time.Hour)
	streakCount := 0
	currentDate := today

	// Iterate backwards through dates to find consecutive activity
	for {
		// Check if current date is in any relevant range
		isRelevant := false
		for _, dr := range relevantDays {
			start := dr.Start.Time.Truncate(24 * time.Hour)
			end := dr.End.Time.Truncate(24 * time.Hour)
			if !currentDate.Before(start) && !currentDate.After(end) {
				isRelevant = true
				break
			}
		}

		// If date is relevant, check if user was active
		if isRelevant {
			if activityDateSet[currentDate] {
				streakCount++
			} else {
				// Streak is broken
				break
			}
		}

		// Move to previous day
		currentDate = currentDate.AddDate(0, 0, -1)

		// Stop if we go back too far (e.g., 1 year)
		if today.Sub(currentDate) > 365*24*time.Hour {
			break
		}
	}

	return streakCount, nil
}

// RelevantDays is the resolver for the relevantDays field.
func (r *streakResolver) RelevantDays(ctx context.Context, obj *model.Streak) ([]model.DateRange, error) {
	thunk := r.Loaders.RelevantDaysByStreakLoader.Load(ctx, obj.ID)
	relevantDays, err := thunk()
	if err != nil {
		return nil, fmt.Errorf("failed to load relevant days: %w", err)
	}
	return relevantDays, nil
}

// ListenedDays is the resolver for the listenedDays field.
func (r *streakResolver) ListenedDays(ctx context.Context, obj *model.Streak, last int) ([]model.StreakDay, error) {
	// Get current user ID
	currentUserID, ok := middleware.GetUserID(ctx)
	if !ok || currentUserID == "" {
		return []model.StreakDay{}, nil // Return empty for unauthenticated users
	}

	// Load relevant days for this streak
	relevantDaysThunk := r.Loaders.RelevantDaysByStreakLoader.Load(ctx, obj.ID)
	relevantDays, err := relevantDaysThunk()
	if err != nil {
		return nil, fmt.Errorf("failed to load relevant days: %w", err)
	}

	// Load user's activity for this streak
	key := loaders.UserStreakActivityKey{UserID: currentUserID, StreakID: obj.ID}
	thunk := r.Loaders.UserStreakActivityLoader.Load(ctx, key)
	activities, err := thunk()
	if err != nil {
		return nil, fmt.Errorf("failed to load user streak activity: %w", err)
	}

	// Build a set of activity dates for fast lookup
	activityDateSet := make(map[time.Time]bool)
	for _, activity := range activities {
		if activity.ActivityDate.Valid {
			activityDateSet[activity.ActivityDate.Time.Truncate(24*time.Hour)] = true
		}
	}

	// Collect all relevant dates from today backwards (no future dates)
	today := time.Now().UTC().Truncate(24 * time.Hour)
	var allRelevantDates []time.Time
	for _, dr := range relevantDays {
		start := dr.Start.Time.Truncate(24 * time.Hour)
		end := dr.End.Time.Truncate(24 * time.Hour)

		// Add all dates in this range, but only up to today
		for d := start; !d.After(end); d = d.AddDate(0, 0, 1) {
			if !d.After(today) {
				allRelevantDates = append(allRelevantDates, d)
			}
		}
	}

	// Sort dates in descending order (most recent first)
	// Use a simple bubble sort for small arrays or implement a proper sort
	for i := 0; i < len(allRelevantDates)-1; i++ {
		for j := i + 1; j < len(allRelevantDates); j++ {
			if allRelevantDates[i].Before(allRelevantDates[j]) {
				allRelevantDates[i], allRelevantDates[j] = allRelevantDates[j], allRelevantDates[i]
			}
		}
	}

	// Take the last N dates
	numToTake := last
	if numToTake > len(allRelevantDates) {
		numToTake = len(allRelevantDates)
	}

	// Build the result with activity status
	result := make([]model.StreakDay, numToTake)
	for i := 0; i < numToTake; i++ {
		date := allRelevantDates[i]
		result[i] = model.StreakDay{
			Date:   scalars.Date{Time: date},
			Active: activityDateSet[date],
		}
	}

	return result, nil
}

// Project is the resolver for the project field.
func (r *streakResolver) Project(ctx context.Context, obj *model.Streak) (*model.Project, error) {
	return resolveProjectByID(ctx, r.Resolver, obj.ProjectID)
}

// TranslationStatus is the resolver for the translationStatus field.
func (r *streakResolver) TranslationStatus(ctx context.Context, obj *model.Streak) ([]model.TranslationFieldStatus, error) {
	return r.streakTranslationStatus(ctx, obj.ID)
}

// Streak returns StreakResolver implementation.
func (r *Resolver) Streak() StreakResolver { return &streakResolver{r} }

type streakResolver struct{ *Resolver }
