query ChallengesPage {
  myCurrentProject {
    challenges {
      __typename
      id
      name
      description
      image
      buttonText
      publishedAt
      endTime
      visibleAt
      userCompletedAt
      ... on SimpleChallenge {
        allowSelfCompletion
      }
      ... on ExternalChallenge {
        url
      }
      ... on QuizChallenge {
        quiz {
          userCanStart
        }
      }
    }
  }
}
