query ActiveChallengesPage {
  myCurrentProject {
    myTeam {
      joinCode
    }
    activeChallenges {
      ...ChallengeFields
    }
  }
}

query CompletedChallengesPage {
  myCurrentProject {
    completedChallenges {
      ...ChallengeFields
    }
  }
}
