query ProfilePage($ageFilter: LeaderboardFilter) {
  me {
    id
    name
    age
    consentStatus {
      pendingConsents {
        __typename
        id
        key
        version
        title
        body {
          html
        }
        shortText
        url
        managementType
        managedBy
      }
    }
  }
  myCurrentProject {
    id
    name
    achievements {
      id
      name
      descriptionPending
      descriptionCompleted
      imagePending
      imageCompleted
      hidden
      achievedAt
      points
    }
    leaderboard(entityType: PERSONS, filter: $ageFilter) {
      me {
        score
        rank
      }
    }
  }
}
