query ProfilePage {
  me {
    id
    name
    consentStatus {
      pendingConsents {
        __typename
        id
        key
        version
        title
        body {
          html
        }
        managementType
        managedBy
      }
    }
  }
  myCurrentProject {
    id
    name
    achievements {
      id
      name
      description
      image
      hidden
      achievedAt
      points
    }
    leaderboard(entityType: PERSONS) {
      me {
        score
        rank
      }
    }
  }
}
