query ProfilePage($ageFilter: LeaderboardFilter) {
  me {
    id
    name
    consentStatus {
      pendingConsents {
        __typename
        id
        key
        version
        title
        body {
          html
        }
        shortText
        url
        managementType
        managedBy
      }
    }
  }
  myCurrentProject {
    id
    name
    infoMessage {
      markdown
      html
    }
    infoMessageStart
    infoMessageEnd
    branding {
      ...BrandingFields
    }
    achievements {
      __typename
      id
      name
      descriptionPending
      descriptionCompleted
      imagePendingObject {
        ...ImageFields
      }
      imageCompletedObject {
        ...ImageFields
      }
      hidden
      achievedAt
      points
      ... on ContentAchievement {
        nextItem {
          id
          sortOrder
          externalContent {
            id
            title
            url
          }
        }
      }
    }
    leaderboard(entityType: PERSONS, filter: $ageFilter) {
      me {
        score
        rank
      }
    }
  }
}
