query ConsentsPage {
  me {
    consentStatus {
      pendingConsents {
        __typename
        id
        key
        version
        title
        body {
          html
        }
        shortText
        publishedAt
        managedBy
        managementType
        url
      }
      acceptedConsents {
        __typename
        id
        consent {
          id
          title
          body {
            html
          }
          shortText
          managedBy
          managementType
          url
        }
        action
        actionDate
      }
      rejectedConsents {
        __typename
        id
        consent {
          id
          title
          body {
            html
          }
          shortText
          managedBy
          managementType
          url
        }
        action
        actionDate
      }
    }
  }
}
