fragment LeaderboardConfigFields on LeaderboardConfig {
  id
  name
  entityType
  limitMode
  maxEntries
  sortOrder
  isActive
  event {
    id
    name
  }
  filter {
    myChurch
    myTeam
    mySuperTeam
    minScore
    maxScore
    churchId
    country
    churchCategory
    gender
    ageRange {
      min
      max
    }
    teamId
    superTeamId
  }
}
