// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bcc-media/wayfarer/internal/database/sqlc"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLeaderboardQuerier creates a new instance of MockLeaderboardQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLeaderboardQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLeaderboardQuerier {
	mock := &MockLeaderboardQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLeaderboardQuerier is an autogenerated mock type for the LeaderboardQuerier type
type MockLeaderboardQuerier struct {
	mock.Mock
}

type MockLeaderboardQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLeaderboardQuerier) EXPECT() *MockLeaderboardQuerier_Expecter {
	return &MockLeaderboardQuerier_Expecter{mock: &_m.Mock}
}

// CountEventChurchLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) CountEventChurchLeaderboard(ctx context.Context, params sqlc.CountEventChurchLeaderboardParams) (int64, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CountEventChurchLeaderboard")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CountEventChurchLeaderboardParams) (int64, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CountEventChurchLeaderboardParams) int64); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CountEventChurchLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_CountEventChurchLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountEventChurchLeaderboard'
type MockLeaderboardQuerier_CountEventChurchLeaderboard_Call struct {
	*mock.Call
}

// CountEventChurchLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.CountEventChurchLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) CountEventChurchLeaderboard(ctx any, params any) *MockLeaderboardQuerier_CountEventChurchLeaderboard_Call {
	return &MockLeaderboardQuerier_CountEventChurchLeaderboard_Call{Call: _e.mock.On("CountEventChurchLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_CountEventChurchLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.CountEventChurchLeaderboardParams)) *MockLeaderboardQuerier_CountEventChurchLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CountEventChurchLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CountEventChurchLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_CountEventChurchLeaderboard_Call) Return(n int64, err error) *MockLeaderboardQuerier_CountEventChurchLeaderboard_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLeaderboardQuerier_CountEventChurchLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.CountEventChurchLeaderboardParams) (int64, error)) *MockLeaderboardQuerier_CountEventChurchLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// CountEventPersonLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) CountEventPersonLeaderboard(ctx context.Context, params sqlc.CountEventPersonLeaderboardParams) (int64, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CountEventPersonLeaderboard")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CountEventPersonLeaderboardParams) (int64, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CountEventPersonLeaderboardParams) int64); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CountEventPersonLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_CountEventPersonLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountEventPersonLeaderboard'
type MockLeaderboardQuerier_CountEventPersonLeaderboard_Call struct {
	*mock.Call
}

// CountEventPersonLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.CountEventPersonLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) CountEventPersonLeaderboard(ctx any, params any) *MockLeaderboardQuerier_CountEventPersonLeaderboard_Call {
	return &MockLeaderboardQuerier_CountEventPersonLeaderboard_Call{Call: _e.mock.On("CountEventPersonLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_CountEventPersonLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.CountEventPersonLeaderboardParams)) *MockLeaderboardQuerier_CountEventPersonLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CountEventPersonLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CountEventPersonLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_CountEventPersonLeaderboard_Call) Return(n int64, err error) *MockLeaderboardQuerier_CountEventPersonLeaderboard_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLeaderboardQuerier_CountEventPersonLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.CountEventPersonLeaderboardParams) (int64, error)) *MockLeaderboardQuerier_CountEventPersonLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// CountEventSuperTeamLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) CountEventSuperTeamLeaderboard(ctx context.Context, eventid string) (int64, error) {
	ret := _mock.Called(ctx, eventid)

	if len(ret) == 0 {
		panic("no return value specified for CountEventSuperTeamLeaderboard")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, eventid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, eventid)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, eventid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_CountEventSuperTeamLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountEventSuperTeamLeaderboard'
type MockLeaderboardQuerier_CountEventSuperTeamLeaderboard_Call struct {
	*mock.Call
}

// CountEventSuperTeamLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - eventid string
func (_e *MockLeaderboardQuerier_Expecter) CountEventSuperTeamLeaderboard(ctx any, eventid any) *MockLeaderboardQuerier_CountEventSuperTeamLeaderboard_Call {
	return &MockLeaderboardQuerier_CountEventSuperTeamLeaderboard_Call{Call: _e.mock.On("CountEventSuperTeamLeaderboard", ctx, eventid)}
}

func (_c *MockLeaderboardQuerier_CountEventSuperTeamLeaderboard_Call) Run(run func(ctx context.Context, eventid string)) *MockLeaderboardQuerier_CountEventSuperTeamLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_CountEventSuperTeamLeaderboard_Call) Return(n int64, err error) *MockLeaderboardQuerier_CountEventSuperTeamLeaderboard_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLeaderboardQuerier_CountEventSuperTeamLeaderboard_Call) RunAndReturn(run func(ctx context.Context, eventid string) (int64, error)) *MockLeaderboardQuerier_CountEventSuperTeamLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// CountEventTeamLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) CountEventTeamLeaderboard(ctx context.Context, arg sqlc.CountEventTeamLeaderboardParams) (int64, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CountEventTeamLeaderboard")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CountEventTeamLeaderboardParams) (int64, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CountEventTeamLeaderboardParams) int64); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CountEventTeamLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_CountEventTeamLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountEventTeamLeaderboard'
type MockLeaderboardQuerier_CountEventTeamLeaderboard_Call struct {
	*mock.Call
}

// CountEventTeamLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CountEventTeamLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) CountEventTeamLeaderboard(ctx any, arg any) *MockLeaderboardQuerier_CountEventTeamLeaderboard_Call {
	return &MockLeaderboardQuerier_CountEventTeamLeaderboard_Call{Call: _e.mock.On("CountEventTeamLeaderboard", ctx, arg)}
}

func (_c *MockLeaderboardQuerier_CountEventTeamLeaderboard_Call) Run(run func(ctx context.Context, arg sqlc.CountEventTeamLeaderboardParams)) *MockLeaderboardQuerier_CountEventTeamLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CountEventTeamLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CountEventTeamLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_CountEventTeamLeaderboard_Call) Return(n int64, err error) *MockLeaderboardQuerier_CountEventTeamLeaderboard_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLeaderboardQuerier_CountEventTeamLeaderboard_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CountEventTeamLeaderboardParams) (int64, error)) *MockLeaderboardQuerier_CountEventTeamLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// CountProjectChurchLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) CountProjectChurchLeaderboard(ctx context.Context, params sqlc.CountProjectChurchLeaderboardParams) (int64, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CountProjectChurchLeaderboard")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CountProjectChurchLeaderboardParams) (int64, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CountProjectChurchLeaderboardParams) int64); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CountProjectChurchLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_CountProjectChurchLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountProjectChurchLeaderboard'
type MockLeaderboardQuerier_CountProjectChurchLeaderboard_Call struct {
	*mock.Call
}

// CountProjectChurchLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.CountProjectChurchLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) CountProjectChurchLeaderboard(ctx any, params any) *MockLeaderboardQuerier_CountProjectChurchLeaderboard_Call {
	return &MockLeaderboardQuerier_CountProjectChurchLeaderboard_Call{Call: _e.mock.On("CountProjectChurchLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_CountProjectChurchLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.CountProjectChurchLeaderboardParams)) *MockLeaderboardQuerier_CountProjectChurchLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CountProjectChurchLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CountProjectChurchLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_CountProjectChurchLeaderboard_Call) Return(n int64, err error) *MockLeaderboardQuerier_CountProjectChurchLeaderboard_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLeaderboardQuerier_CountProjectChurchLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.CountProjectChurchLeaderboardParams) (int64, error)) *MockLeaderboardQuerier_CountProjectChurchLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// CountProjectPersonLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) CountProjectPersonLeaderboard(ctx context.Context, params sqlc.CountProjectPersonLeaderboardParams) (int64, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CountProjectPersonLeaderboard")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CountProjectPersonLeaderboardParams) (int64, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CountProjectPersonLeaderboardParams) int64); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CountProjectPersonLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_CountProjectPersonLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountProjectPersonLeaderboard'
type MockLeaderboardQuerier_CountProjectPersonLeaderboard_Call struct {
	*mock.Call
}

// CountProjectPersonLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.CountProjectPersonLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) CountProjectPersonLeaderboard(ctx any, params any) *MockLeaderboardQuerier_CountProjectPersonLeaderboard_Call {
	return &MockLeaderboardQuerier_CountProjectPersonLeaderboard_Call{Call: _e.mock.On("CountProjectPersonLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_CountProjectPersonLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.CountProjectPersonLeaderboardParams)) *MockLeaderboardQuerier_CountProjectPersonLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CountProjectPersonLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CountProjectPersonLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_CountProjectPersonLeaderboard_Call) Return(n int64, err error) *MockLeaderboardQuerier_CountProjectPersonLeaderboard_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLeaderboardQuerier_CountProjectPersonLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.CountProjectPersonLeaderboardParams) (int64, error)) *MockLeaderboardQuerier_CountProjectPersonLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// CountProjectSuperTeamLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) CountProjectSuperTeamLeaderboard(ctx context.Context, projectid string) (int64, error) {
	ret := _mock.Called(ctx, projectid)

	if len(ret) == 0 {
		panic("no return value specified for CountProjectSuperTeamLeaderboard")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, projectid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, projectid)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, projectid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_CountProjectSuperTeamLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountProjectSuperTeamLeaderboard'
type MockLeaderboardQuerier_CountProjectSuperTeamLeaderboard_Call struct {
	*mock.Call
}

// CountProjectSuperTeamLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - projectid string
func (_e *MockLeaderboardQuerier_Expecter) CountProjectSuperTeamLeaderboard(ctx any, projectid any) *MockLeaderboardQuerier_CountProjectSuperTeamLeaderboard_Call {
	return &MockLeaderboardQuerier_CountProjectSuperTeamLeaderboard_Call{Call: _e.mock.On("CountProjectSuperTeamLeaderboard", ctx, projectid)}
}

func (_c *MockLeaderboardQuerier_CountProjectSuperTeamLeaderboard_Call) Run(run func(ctx context.Context, projectid string)) *MockLeaderboardQuerier_CountProjectSuperTeamLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_CountProjectSuperTeamLeaderboard_Call) Return(n int64, err error) *MockLeaderboardQuerier_CountProjectSuperTeamLeaderboard_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLeaderboardQuerier_CountProjectSuperTeamLeaderboard_Call) RunAndReturn(run func(ctx context.Context, projectid string) (int64, error)) *MockLeaderboardQuerier_CountProjectSuperTeamLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// CountProjectTeamLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) CountProjectTeamLeaderboard(ctx context.Context, arg sqlc.CountProjectTeamLeaderboardParams) (int64, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CountProjectTeamLeaderboard")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CountProjectTeamLeaderboardParams) (int64, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CountProjectTeamLeaderboardParams) int64); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CountProjectTeamLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_CountProjectTeamLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountProjectTeamLeaderboard'
type MockLeaderboardQuerier_CountProjectTeamLeaderboard_Call struct {
	*mock.Call
}

// CountProjectTeamLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CountProjectTeamLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) CountProjectTeamLeaderboard(ctx any, arg any) *MockLeaderboardQuerier_CountProjectTeamLeaderboard_Call {
	return &MockLeaderboardQuerier_CountProjectTeamLeaderboard_Call{Call: _e.mock.On("CountProjectTeamLeaderboard", ctx, arg)}
}

func (_c *MockLeaderboardQuerier_CountProjectTeamLeaderboard_Call) Run(run func(ctx context.Context, arg sqlc.CountProjectTeamLeaderboardParams)) *MockLeaderboardQuerier_CountProjectTeamLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CountProjectTeamLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CountProjectTeamLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_CountProjectTeamLeaderboard_Call) Return(n int64, err error) *MockLeaderboardQuerier_CountProjectTeamLeaderboard_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLeaderboardQuerier_CountProjectTeamLeaderboard_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CountProjectTeamLeaderboardParams) (int64, error)) *MockLeaderboardQuerier_CountProjectTeamLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// FindMyEventChurchPosition provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) FindMyEventChurchPosition(ctx context.Context, params sqlc.FindMyEventChurchPositionParams) (*sqlc.FindMyEventChurchPositionRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for FindMyEventChurchPosition")
	}

	var r0 *sqlc.FindMyEventChurchPositionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyEventChurchPositionParams) (*sqlc.FindMyEventChurchPositionRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyEventChurchPositionParams) *sqlc.FindMyEventChurchPositionRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.FindMyEventChurchPositionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.FindMyEventChurchPositionParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_FindMyEventChurchPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMyEventChurchPosition'
type MockLeaderboardQuerier_FindMyEventChurchPosition_Call struct {
	*mock.Call
}

// FindMyEventChurchPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.FindMyEventChurchPositionParams
func (_e *MockLeaderboardQuerier_Expecter) FindMyEventChurchPosition(ctx any, params any) *MockLeaderboardQuerier_FindMyEventChurchPosition_Call {
	return &MockLeaderboardQuerier_FindMyEventChurchPosition_Call{Call: _e.mock.On("FindMyEventChurchPosition", ctx, params)}
}

func (_c *MockLeaderboardQuerier_FindMyEventChurchPosition_Call) Run(run func(ctx context.Context, params sqlc.FindMyEventChurchPositionParams)) *MockLeaderboardQuerier_FindMyEventChurchPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.FindMyEventChurchPositionParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.FindMyEventChurchPositionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyEventChurchPosition_Call) Return(findMyEventChurchPositionRow *sqlc.FindMyEventChurchPositionRow, err error) *MockLeaderboardQuerier_FindMyEventChurchPosition_Call {
	_c.Call.Return(findMyEventChurchPositionRow, err)
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyEventChurchPosition_Call) RunAndReturn(run func(ctx context.Context, params sqlc.FindMyEventChurchPositionParams) (*sqlc.FindMyEventChurchPositionRow, error)) *MockLeaderboardQuerier_FindMyEventChurchPosition_Call {
	_c.Call.Return(run)
	return _c
}

// FindMyEventPersonPosition provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) FindMyEventPersonPosition(ctx context.Context, params sqlc.FindMyEventPersonPositionParams) (*sqlc.FindMyEventPersonPositionRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for FindMyEventPersonPosition")
	}

	var r0 *sqlc.FindMyEventPersonPositionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyEventPersonPositionParams) (*sqlc.FindMyEventPersonPositionRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyEventPersonPositionParams) *sqlc.FindMyEventPersonPositionRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.FindMyEventPersonPositionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.FindMyEventPersonPositionParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_FindMyEventPersonPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMyEventPersonPosition'
type MockLeaderboardQuerier_FindMyEventPersonPosition_Call struct {
	*mock.Call
}

// FindMyEventPersonPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.FindMyEventPersonPositionParams
func (_e *MockLeaderboardQuerier_Expecter) FindMyEventPersonPosition(ctx any, params any) *MockLeaderboardQuerier_FindMyEventPersonPosition_Call {
	return &MockLeaderboardQuerier_FindMyEventPersonPosition_Call{Call: _e.mock.On("FindMyEventPersonPosition", ctx, params)}
}

func (_c *MockLeaderboardQuerier_FindMyEventPersonPosition_Call) Run(run func(ctx context.Context, params sqlc.FindMyEventPersonPositionParams)) *MockLeaderboardQuerier_FindMyEventPersonPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.FindMyEventPersonPositionParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.FindMyEventPersonPositionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyEventPersonPosition_Call) Return(findMyEventPersonPositionRow *sqlc.FindMyEventPersonPositionRow, err error) *MockLeaderboardQuerier_FindMyEventPersonPosition_Call {
	_c.Call.Return(findMyEventPersonPositionRow, err)
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyEventPersonPosition_Call) RunAndReturn(run func(ctx context.Context, params sqlc.FindMyEventPersonPositionParams) (*sqlc.FindMyEventPersonPositionRow, error)) *MockLeaderboardQuerier_FindMyEventPersonPosition_Call {
	_c.Call.Return(run)
	return _c
}

// FindMyEventSuperTeamPosition provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) FindMyEventSuperTeamPosition(ctx context.Context, params sqlc.FindMyEventSuperTeamPositionParams) (*sqlc.FindMyEventSuperTeamPositionRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for FindMyEventSuperTeamPosition")
	}

	var r0 *sqlc.FindMyEventSuperTeamPositionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyEventSuperTeamPositionParams) (*sqlc.FindMyEventSuperTeamPositionRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyEventSuperTeamPositionParams) *sqlc.FindMyEventSuperTeamPositionRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.FindMyEventSuperTeamPositionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.FindMyEventSuperTeamPositionParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_FindMyEventSuperTeamPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMyEventSuperTeamPosition'
type MockLeaderboardQuerier_FindMyEventSuperTeamPosition_Call struct {
	*mock.Call
}

// FindMyEventSuperTeamPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.FindMyEventSuperTeamPositionParams
func (_e *MockLeaderboardQuerier_Expecter) FindMyEventSuperTeamPosition(ctx any, params any) *MockLeaderboardQuerier_FindMyEventSuperTeamPosition_Call {
	return &MockLeaderboardQuerier_FindMyEventSuperTeamPosition_Call{Call: _e.mock.On("FindMyEventSuperTeamPosition", ctx, params)}
}

func (_c *MockLeaderboardQuerier_FindMyEventSuperTeamPosition_Call) Run(run func(ctx context.Context, params sqlc.FindMyEventSuperTeamPositionParams)) *MockLeaderboardQuerier_FindMyEventSuperTeamPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.FindMyEventSuperTeamPositionParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.FindMyEventSuperTeamPositionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyEventSuperTeamPosition_Call) Return(findMyEventSuperTeamPositionRow *sqlc.FindMyEventSuperTeamPositionRow, err error) *MockLeaderboardQuerier_FindMyEventSuperTeamPosition_Call {
	_c.Call.Return(findMyEventSuperTeamPositionRow, err)
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyEventSuperTeamPosition_Call) RunAndReturn(run func(ctx context.Context, params sqlc.FindMyEventSuperTeamPositionParams) (*sqlc.FindMyEventSuperTeamPositionRow, error)) *MockLeaderboardQuerier_FindMyEventSuperTeamPosition_Call {
	_c.Call.Return(run)
	return _c
}

// FindMyEventTeamPosition provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) FindMyEventTeamPosition(ctx context.Context, params sqlc.FindMyEventTeamPositionParams) (*sqlc.FindMyEventTeamPositionRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for FindMyEventTeamPosition")
	}

	var r0 *sqlc.FindMyEventTeamPositionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyEventTeamPositionParams) (*sqlc.FindMyEventTeamPositionRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyEventTeamPositionParams) *sqlc.FindMyEventTeamPositionRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.FindMyEventTeamPositionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.FindMyEventTeamPositionParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_FindMyEventTeamPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMyEventTeamPosition'
type MockLeaderboardQuerier_FindMyEventTeamPosition_Call struct {
	*mock.Call
}

// FindMyEventTeamPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.FindMyEventTeamPositionParams
func (_e *MockLeaderboardQuerier_Expecter) FindMyEventTeamPosition(ctx any, params any) *MockLeaderboardQuerier_FindMyEventTeamPosition_Call {
	return &MockLeaderboardQuerier_FindMyEventTeamPosition_Call{Call: _e.mock.On("FindMyEventTeamPosition", ctx, params)}
}

func (_c *MockLeaderboardQuerier_FindMyEventTeamPosition_Call) Run(run func(ctx context.Context, params sqlc.FindMyEventTeamPositionParams)) *MockLeaderboardQuerier_FindMyEventTeamPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.FindMyEventTeamPositionParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.FindMyEventTeamPositionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyEventTeamPosition_Call) Return(findMyEventTeamPositionRow *sqlc.FindMyEventTeamPositionRow, err error) *MockLeaderboardQuerier_FindMyEventTeamPosition_Call {
	_c.Call.Return(findMyEventTeamPositionRow, err)
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyEventTeamPosition_Call) RunAndReturn(run func(ctx context.Context, params sqlc.FindMyEventTeamPositionParams) (*sqlc.FindMyEventTeamPositionRow, error)) *MockLeaderboardQuerier_FindMyEventTeamPosition_Call {
	_c.Call.Return(run)
	return _c
}

// FindMyProjectChurchPosition provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) FindMyProjectChurchPosition(ctx context.Context, params sqlc.FindMyProjectChurchPositionParams) (*sqlc.FindMyProjectChurchPositionRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for FindMyProjectChurchPosition")
	}

	var r0 *sqlc.FindMyProjectChurchPositionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyProjectChurchPositionParams) (*sqlc.FindMyProjectChurchPositionRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyProjectChurchPositionParams) *sqlc.FindMyProjectChurchPositionRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.FindMyProjectChurchPositionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.FindMyProjectChurchPositionParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_FindMyProjectChurchPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMyProjectChurchPosition'
type MockLeaderboardQuerier_FindMyProjectChurchPosition_Call struct {
	*mock.Call
}

// FindMyProjectChurchPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.FindMyProjectChurchPositionParams
func (_e *MockLeaderboardQuerier_Expecter) FindMyProjectChurchPosition(ctx any, params any) *MockLeaderboardQuerier_FindMyProjectChurchPosition_Call {
	return &MockLeaderboardQuerier_FindMyProjectChurchPosition_Call{Call: _e.mock.On("FindMyProjectChurchPosition", ctx, params)}
}

func (_c *MockLeaderboardQuerier_FindMyProjectChurchPosition_Call) Run(run func(ctx context.Context, params sqlc.FindMyProjectChurchPositionParams)) *MockLeaderboardQuerier_FindMyProjectChurchPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.FindMyProjectChurchPositionParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.FindMyProjectChurchPositionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyProjectChurchPosition_Call) Return(findMyProjectChurchPositionRow *sqlc.FindMyProjectChurchPositionRow, err error) *MockLeaderboardQuerier_FindMyProjectChurchPosition_Call {
	_c.Call.Return(findMyProjectChurchPositionRow, err)
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyProjectChurchPosition_Call) RunAndReturn(run func(ctx context.Context, params sqlc.FindMyProjectChurchPositionParams) (*sqlc.FindMyProjectChurchPositionRow, error)) *MockLeaderboardQuerier_FindMyProjectChurchPosition_Call {
	_c.Call.Return(run)
	return _c
}

// FindMyProjectPersonPosition provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) FindMyProjectPersonPosition(ctx context.Context, params sqlc.FindMyProjectPersonPositionParams) (*sqlc.FindMyProjectPersonPositionRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for FindMyProjectPersonPosition")
	}

	var r0 *sqlc.FindMyProjectPersonPositionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyProjectPersonPositionParams) (*sqlc.FindMyProjectPersonPositionRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyProjectPersonPositionParams) *sqlc.FindMyProjectPersonPositionRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.FindMyProjectPersonPositionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.FindMyProjectPersonPositionParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_FindMyProjectPersonPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMyProjectPersonPosition'
type MockLeaderboardQuerier_FindMyProjectPersonPosition_Call struct {
	*mock.Call
}

// FindMyProjectPersonPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.FindMyProjectPersonPositionParams
func (_e *MockLeaderboardQuerier_Expecter) FindMyProjectPersonPosition(ctx any, params any) *MockLeaderboardQuerier_FindMyProjectPersonPosition_Call {
	return &MockLeaderboardQuerier_FindMyProjectPersonPosition_Call{Call: _e.mock.On("FindMyProjectPersonPosition", ctx, params)}
}

func (_c *MockLeaderboardQuerier_FindMyProjectPersonPosition_Call) Run(run func(ctx context.Context, params sqlc.FindMyProjectPersonPositionParams)) *MockLeaderboardQuerier_FindMyProjectPersonPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.FindMyProjectPersonPositionParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.FindMyProjectPersonPositionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyProjectPersonPosition_Call) Return(findMyProjectPersonPositionRow *sqlc.FindMyProjectPersonPositionRow, err error) *MockLeaderboardQuerier_FindMyProjectPersonPosition_Call {
	_c.Call.Return(findMyProjectPersonPositionRow, err)
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyProjectPersonPosition_Call) RunAndReturn(run func(ctx context.Context, params sqlc.FindMyProjectPersonPositionParams) (*sqlc.FindMyProjectPersonPositionRow, error)) *MockLeaderboardQuerier_FindMyProjectPersonPosition_Call {
	_c.Call.Return(run)
	return _c
}

// FindMyProjectSuperTeamPosition provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) FindMyProjectSuperTeamPosition(ctx context.Context, params sqlc.FindMyProjectSuperTeamPositionParams) (*sqlc.FindMyProjectSuperTeamPositionRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for FindMyProjectSuperTeamPosition")
	}

	var r0 *sqlc.FindMyProjectSuperTeamPositionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyProjectSuperTeamPositionParams) (*sqlc.FindMyProjectSuperTeamPositionRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyProjectSuperTeamPositionParams) *sqlc.FindMyProjectSuperTeamPositionRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.FindMyProjectSuperTeamPositionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.FindMyProjectSuperTeamPositionParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_FindMyProjectSuperTeamPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMyProjectSuperTeamPosition'
type MockLeaderboardQuerier_FindMyProjectSuperTeamPosition_Call struct {
	*mock.Call
}

// FindMyProjectSuperTeamPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.FindMyProjectSuperTeamPositionParams
func (_e *MockLeaderboardQuerier_Expecter) FindMyProjectSuperTeamPosition(ctx any, params any) *MockLeaderboardQuerier_FindMyProjectSuperTeamPosition_Call {
	return &MockLeaderboardQuerier_FindMyProjectSuperTeamPosition_Call{Call: _e.mock.On("FindMyProjectSuperTeamPosition", ctx, params)}
}

func (_c *MockLeaderboardQuerier_FindMyProjectSuperTeamPosition_Call) Run(run func(ctx context.Context, params sqlc.FindMyProjectSuperTeamPositionParams)) *MockLeaderboardQuerier_FindMyProjectSuperTeamPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.FindMyProjectSuperTeamPositionParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.FindMyProjectSuperTeamPositionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyProjectSuperTeamPosition_Call) Return(findMyProjectSuperTeamPositionRow *sqlc.FindMyProjectSuperTeamPositionRow, err error) *MockLeaderboardQuerier_FindMyProjectSuperTeamPosition_Call {
	_c.Call.Return(findMyProjectSuperTeamPositionRow, err)
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyProjectSuperTeamPosition_Call) RunAndReturn(run func(ctx context.Context, params sqlc.FindMyProjectSuperTeamPositionParams) (*sqlc.FindMyProjectSuperTeamPositionRow, error)) *MockLeaderboardQuerier_FindMyProjectSuperTeamPosition_Call {
	_c.Call.Return(run)
	return _c
}

// FindMyProjectTeamPosition provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) FindMyProjectTeamPosition(ctx context.Context, params sqlc.FindMyProjectTeamPositionParams) (*sqlc.FindMyProjectTeamPositionRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for FindMyProjectTeamPosition")
	}

	var r0 *sqlc.FindMyProjectTeamPositionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyProjectTeamPositionParams) (*sqlc.FindMyProjectTeamPositionRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.FindMyProjectTeamPositionParams) *sqlc.FindMyProjectTeamPositionRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.FindMyProjectTeamPositionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.FindMyProjectTeamPositionParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_FindMyProjectTeamPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMyProjectTeamPosition'
type MockLeaderboardQuerier_FindMyProjectTeamPosition_Call struct {
	*mock.Call
}

// FindMyProjectTeamPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.FindMyProjectTeamPositionParams
func (_e *MockLeaderboardQuerier_Expecter) FindMyProjectTeamPosition(ctx any, params any) *MockLeaderboardQuerier_FindMyProjectTeamPosition_Call {
	return &MockLeaderboardQuerier_FindMyProjectTeamPosition_Call{Call: _e.mock.On("FindMyProjectTeamPosition", ctx, params)}
}

func (_c *MockLeaderboardQuerier_FindMyProjectTeamPosition_Call) Run(run func(ctx context.Context, params sqlc.FindMyProjectTeamPositionParams)) *MockLeaderboardQuerier_FindMyProjectTeamPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.FindMyProjectTeamPositionParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.FindMyProjectTeamPositionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyProjectTeamPosition_Call) Return(findMyProjectTeamPositionRow *sqlc.FindMyProjectTeamPositionRow, err error) *MockLeaderboardQuerier_FindMyProjectTeamPosition_Call {
	_c.Call.Return(findMyProjectTeamPositionRow, err)
	return _c
}

func (_c *MockLeaderboardQuerier_FindMyProjectTeamPosition_Call) RunAndReturn(run func(ctx context.Context, params sqlc.FindMyProjectTeamPositionParams) (*sqlc.FindMyProjectTeamPositionRow, error)) *MockLeaderboardQuerier_FindMyProjectTeamPosition_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventChurchLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetEventChurchLeaderboard(ctx context.Context, params sqlc.GetEventChurchLeaderboardParams) ([]*sqlc.GetEventChurchLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetEventChurchLeaderboard")
	}

	var r0 []*sqlc.GetEventChurchLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetEventChurchLeaderboardParams) ([]*sqlc.GetEventChurchLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetEventChurchLeaderboardParams) []*sqlc.GetEventChurchLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetEventChurchLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetEventChurchLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetEventChurchLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventChurchLeaderboard'
type MockLeaderboardQuerier_GetEventChurchLeaderboard_Call struct {
	*mock.Call
}

// GetEventChurchLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetEventChurchLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetEventChurchLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetEventChurchLeaderboard_Call {
	return &MockLeaderboardQuerier_GetEventChurchLeaderboard_Call{Call: _e.mock.On("GetEventChurchLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetEventChurchLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetEventChurchLeaderboardParams)) *MockLeaderboardQuerier_GetEventChurchLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetEventChurchLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetEventChurchLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetEventChurchLeaderboard_Call) Return(getEventChurchLeaderboardRows []*sqlc.GetEventChurchLeaderboardRow, err error) *MockLeaderboardQuerier_GetEventChurchLeaderboard_Call {
	_c.Call.Return(getEventChurchLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetEventChurchLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetEventChurchLeaderboardParams) ([]*sqlc.GetEventChurchLeaderboardRow, error)) *MockLeaderboardQuerier_GetEventChurchLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventPersonLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetEventPersonLeaderboard(ctx context.Context, params sqlc.GetEventPersonLeaderboardParams) ([]*sqlc.GetEventPersonLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetEventPersonLeaderboard")
	}

	var r0 []*sqlc.GetEventPersonLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetEventPersonLeaderboardParams) ([]*sqlc.GetEventPersonLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetEventPersonLeaderboardParams) []*sqlc.GetEventPersonLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetEventPersonLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetEventPersonLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetEventPersonLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventPersonLeaderboard'
type MockLeaderboardQuerier_GetEventPersonLeaderboard_Call struct {
	*mock.Call
}

// GetEventPersonLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetEventPersonLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetEventPersonLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetEventPersonLeaderboard_Call {
	return &MockLeaderboardQuerier_GetEventPersonLeaderboard_Call{Call: _e.mock.On("GetEventPersonLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetEventPersonLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetEventPersonLeaderboardParams)) *MockLeaderboardQuerier_GetEventPersonLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetEventPersonLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetEventPersonLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetEventPersonLeaderboard_Call) Return(getEventPersonLeaderboardRows []*sqlc.GetEventPersonLeaderboardRow, err error) *MockLeaderboardQuerier_GetEventPersonLeaderboard_Call {
	_c.Call.Return(getEventPersonLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetEventPersonLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetEventPersonLeaderboardParams) ([]*sqlc.GetEventPersonLeaderboardRow, error)) *MockLeaderboardQuerier_GetEventPersonLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventSuperTeamLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetEventSuperTeamLeaderboard(ctx context.Context, params sqlc.GetEventSuperTeamLeaderboardParams) ([]*sqlc.GetEventSuperTeamLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetEventSuperTeamLeaderboard")
	}

	var r0 []*sqlc.GetEventSuperTeamLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetEventSuperTeamLeaderboardParams) ([]*sqlc.GetEventSuperTeamLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetEventSuperTeamLeaderboardParams) []*sqlc.GetEventSuperTeamLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetEventSuperTeamLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetEventSuperTeamLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetEventSuperTeamLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventSuperTeamLeaderboard'
type MockLeaderboardQuerier_GetEventSuperTeamLeaderboard_Call struct {
	*mock.Call
}

// GetEventSuperTeamLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetEventSuperTeamLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetEventSuperTeamLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetEventSuperTeamLeaderboard_Call {
	return &MockLeaderboardQuerier_GetEventSuperTeamLeaderboard_Call{Call: _e.mock.On("GetEventSuperTeamLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetEventSuperTeamLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetEventSuperTeamLeaderboardParams)) *MockLeaderboardQuerier_GetEventSuperTeamLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetEventSuperTeamLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetEventSuperTeamLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetEventSuperTeamLeaderboard_Call) Return(getEventSuperTeamLeaderboardRows []*sqlc.GetEventSuperTeamLeaderboardRow, err error) *MockLeaderboardQuerier_GetEventSuperTeamLeaderboard_Call {
	_c.Call.Return(getEventSuperTeamLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetEventSuperTeamLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetEventSuperTeamLeaderboardParams) ([]*sqlc.GetEventSuperTeamLeaderboardRow, error)) *MockLeaderboardQuerier_GetEventSuperTeamLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventTeamLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetEventTeamLeaderboard(ctx context.Context, params sqlc.GetEventTeamLeaderboardParams) ([]*sqlc.GetEventTeamLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetEventTeamLeaderboard")
	}

	var r0 []*sqlc.GetEventTeamLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetEventTeamLeaderboardParams) ([]*sqlc.GetEventTeamLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetEventTeamLeaderboardParams) []*sqlc.GetEventTeamLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetEventTeamLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetEventTeamLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetEventTeamLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventTeamLeaderboard'
type MockLeaderboardQuerier_GetEventTeamLeaderboard_Call struct {
	*mock.Call
}

// GetEventTeamLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetEventTeamLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetEventTeamLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetEventTeamLeaderboard_Call {
	return &MockLeaderboardQuerier_GetEventTeamLeaderboard_Call{Call: _e.mock.On("GetEventTeamLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetEventTeamLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetEventTeamLeaderboardParams)) *MockLeaderboardQuerier_GetEventTeamLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetEventTeamLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetEventTeamLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetEventTeamLeaderboard_Call) Return(getEventTeamLeaderboardRows []*sqlc.GetEventTeamLeaderboardRow, err error) *MockLeaderboardQuerier_GetEventTeamLeaderboard_Call {
	_c.Call.Return(getEventTeamLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetEventTeamLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetEventTeamLeaderboardParams) ([]*sqlc.GetEventTeamLeaderboardRow, error)) *MockLeaderboardQuerier_GetEventTeamLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetFullEventChurchLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetFullEventChurchLeaderboard(ctx context.Context, params sqlc.GetFullEventChurchLeaderboardParams) ([]*sqlc.GetFullEventChurchLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFullEventChurchLeaderboard")
	}

	var r0 []*sqlc.GetFullEventChurchLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullEventChurchLeaderboardParams) ([]*sqlc.GetFullEventChurchLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullEventChurchLeaderboardParams) []*sqlc.GetFullEventChurchLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetFullEventChurchLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetFullEventChurchLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetFullEventChurchLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFullEventChurchLeaderboard'
type MockLeaderboardQuerier_GetFullEventChurchLeaderboard_Call struct {
	*mock.Call
}

// GetFullEventChurchLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetFullEventChurchLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetFullEventChurchLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetFullEventChurchLeaderboard_Call {
	return &MockLeaderboardQuerier_GetFullEventChurchLeaderboard_Call{Call: _e.mock.On("GetFullEventChurchLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetFullEventChurchLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetFullEventChurchLeaderboardParams)) *MockLeaderboardQuerier_GetFullEventChurchLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetFullEventChurchLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetFullEventChurchLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullEventChurchLeaderboard_Call) Return(getFullEventChurchLeaderboardRows []*sqlc.GetFullEventChurchLeaderboardRow, err error) *MockLeaderboardQuerier_GetFullEventChurchLeaderboard_Call {
	_c.Call.Return(getFullEventChurchLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullEventChurchLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetFullEventChurchLeaderboardParams) ([]*sqlc.GetFullEventChurchLeaderboardRow, error)) *MockLeaderboardQuerier_GetFullEventChurchLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetFullEventPersonLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetFullEventPersonLeaderboard(ctx context.Context, params sqlc.GetFullEventPersonLeaderboardParams) ([]*sqlc.GetFullEventPersonLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFullEventPersonLeaderboard")
	}

	var r0 []*sqlc.GetFullEventPersonLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullEventPersonLeaderboardParams) ([]*sqlc.GetFullEventPersonLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullEventPersonLeaderboardParams) []*sqlc.GetFullEventPersonLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetFullEventPersonLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetFullEventPersonLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetFullEventPersonLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFullEventPersonLeaderboard'
type MockLeaderboardQuerier_GetFullEventPersonLeaderboard_Call struct {
	*mock.Call
}

// GetFullEventPersonLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetFullEventPersonLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetFullEventPersonLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetFullEventPersonLeaderboard_Call {
	return &MockLeaderboardQuerier_GetFullEventPersonLeaderboard_Call{Call: _e.mock.On("GetFullEventPersonLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetFullEventPersonLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetFullEventPersonLeaderboardParams)) *MockLeaderboardQuerier_GetFullEventPersonLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetFullEventPersonLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetFullEventPersonLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullEventPersonLeaderboard_Call) Return(getFullEventPersonLeaderboardRows []*sqlc.GetFullEventPersonLeaderboardRow, err error) *MockLeaderboardQuerier_GetFullEventPersonLeaderboard_Call {
	_c.Call.Return(getFullEventPersonLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullEventPersonLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetFullEventPersonLeaderboardParams) ([]*sqlc.GetFullEventPersonLeaderboardRow, error)) *MockLeaderboardQuerier_GetFullEventPersonLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetFullEventSuperTeamLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetFullEventSuperTeamLeaderboard(ctx context.Context, params sqlc.GetFullEventSuperTeamLeaderboardParams) ([]*sqlc.GetFullEventSuperTeamLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFullEventSuperTeamLeaderboard")
	}

	var r0 []*sqlc.GetFullEventSuperTeamLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullEventSuperTeamLeaderboardParams) ([]*sqlc.GetFullEventSuperTeamLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullEventSuperTeamLeaderboardParams) []*sqlc.GetFullEventSuperTeamLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetFullEventSuperTeamLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetFullEventSuperTeamLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetFullEventSuperTeamLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFullEventSuperTeamLeaderboard'
type MockLeaderboardQuerier_GetFullEventSuperTeamLeaderboard_Call struct {
	*mock.Call
}

// GetFullEventSuperTeamLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetFullEventSuperTeamLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetFullEventSuperTeamLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetFullEventSuperTeamLeaderboard_Call {
	return &MockLeaderboardQuerier_GetFullEventSuperTeamLeaderboard_Call{Call: _e.mock.On("GetFullEventSuperTeamLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetFullEventSuperTeamLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetFullEventSuperTeamLeaderboardParams)) *MockLeaderboardQuerier_GetFullEventSuperTeamLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetFullEventSuperTeamLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetFullEventSuperTeamLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullEventSuperTeamLeaderboard_Call) Return(getFullEventSuperTeamLeaderboardRows []*sqlc.GetFullEventSuperTeamLeaderboardRow, err error) *MockLeaderboardQuerier_GetFullEventSuperTeamLeaderboard_Call {
	_c.Call.Return(getFullEventSuperTeamLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullEventSuperTeamLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetFullEventSuperTeamLeaderboardParams) ([]*sqlc.GetFullEventSuperTeamLeaderboardRow, error)) *MockLeaderboardQuerier_GetFullEventSuperTeamLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetFullEventTeamLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetFullEventTeamLeaderboard(ctx context.Context, params sqlc.GetFullEventTeamLeaderboardParams) ([]*sqlc.GetFullEventTeamLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFullEventTeamLeaderboard")
	}

	var r0 []*sqlc.GetFullEventTeamLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullEventTeamLeaderboardParams) ([]*sqlc.GetFullEventTeamLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullEventTeamLeaderboardParams) []*sqlc.GetFullEventTeamLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetFullEventTeamLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetFullEventTeamLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetFullEventTeamLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFullEventTeamLeaderboard'
type MockLeaderboardQuerier_GetFullEventTeamLeaderboard_Call struct {
	*mock.Call
}

// GetFullEventTeamLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetFullEventTeamLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetFullEventTeamLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetFullEventTeamLeaderboard_Call {
	return &MockLeaderboardQuerier_GetFullEventTeamLeaderboard_Call{Call: _e.mock.On("GetFullEventTeamLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetFullEventTeamLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetFullEventTeamLeaderboardParams)) *MockLeaderboardQuerier_GetFullEventTeamLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetFullEventTeamLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetFullEventTeamLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullEventTeamLeaderboard_Call) Return(getFullEventTeamLeaderboardRows []*sqlc.GetFullEventTeamLeaderboardRow, err error) *MockLeaderboardQuerier_GetFullEventTeamLeaderboard_Call {
	_c.Call.Return(getFullEventTeamLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullEventTeamLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetFullEventTeamLeaderboardParams) ([]*sqlc.GetFullEventTeamLeaderboardRow, error)) *MockLeaderboardQuerier_GetFullEventTeamLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetFullProjectChurchLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetFullProjectChurchLeaderboard(ctx context.Context, params sqlc.GetFullProjectChurchLeaderboardParams) ([]*sqlc.GetFullProjectChurchLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFullProjectChurchLeaderboard")
	}

	var r0 []*sqlc.GetFullProjectChurchLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullProjectChurchLeaderboardParams) ([]*sqlc.GetFullProjectChurchLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullProjectChurchLeaderboardParams) []*sqlc.GetFullProjectChurchLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetFullProjectChurchLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetFullProjectChurchLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetFullProjectChurchLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFullProjectChurchLeaderboard'
type MockLeaderboardQuerier_GetFullProjectChurchLeaderboard_Call struct {
	*mock.Call
}

// GetFullProjectChurchLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetFullProjectChurchLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetFullProjectChurchLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetFullProjectChurchLeaderboard_Call {
	return &MockLeaderboardQuerier_GetFullProjectChurchLeaderboard_Call{Call: _e.mock.On("GetFullProjectChurchLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetFullProjectChurchLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetFullProjectChurchLeaderboardParams)) *MockLeaderboardQuerier_GetFullProjectChurchLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetFullProjectChurchLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetFullProjectChurchLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullProjectChurchLeaderboard_Call) Return(getFullProjectChurchLeaderboardRows []*sqlc.GetFullProjectChurchLeaderboardRow, err error) *MockLeaderboardQuerier_GetFullProjectChurchLeaderboard_Call {
	_c.Call.Return(getFullProjectChurchLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullProjectChurchLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetFullProjectChurchLeaderboardParams) ([]*sqlc.GetFullProjectChurchLeaderboardRow, error)) *MockLeaderboardQuerier_GetFullProjectChurchLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetFullProjectPersonLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetFullProjectPersonLeaderboard(ctx context.Context, params sqlc.GetFullProjectPersonLeaderboardParams) ([]*sqlc.GetFullProjectPersonLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFullProjectPersonLeaderboard")
	}

	var r0 []*sqlc.GetFullProjectPersonLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullProjectPersonLeaderboardParams) ([]*sqlc.GetFullProjectPersonLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullProjectPersonLeaderboardParams) []*sqlc.GetFullProjectPersonLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetFullProjectPersonLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetFullProjectPersonLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetFullProjectPersonLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFullProjectPersonLeaderboard'
type MockLeaderboardQuerier_GetFullProjectPersonLeaderboard_Call struct {
	*mock.Call
}

// GetFullProjectPersonLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetFullProjectPersonLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetFullProjectPersonLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetFullProjectPersonLeaderboard_Call {
	return &MockLeaderboardQuerier_GetFullProjectPersonLeaderboard_Call{Call: _e.mock.On("GetFullProjectPersonLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetFullProjectPersonLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetFullProjectPersonLeaderboardParams)) *MockLeaderboardQuerier_GetFullProjectPersonLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetFullProjectPersonLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetFullProjectPersonLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullProjectPersonLeaderboard_Call) Return(getFullProjectPersonLeaderboardRows []*sqlc.GetFullProjectPersonLeaderboardRow, err error) *MockLeaderboardQuerier_GetFullProjectPersonLeaderboard_Call {
	_c.Call.Return(getFullProjectPersonLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullProjectPersonLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetFullProjectPersonLeaderboardParams) ([]*sqlc.GetFullProjectPersonLeaderboardRow, error)) *MockLeaderboardQuerier_GetFullProjectPersonLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetFullProjectSuperTeamLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetFullProjectSuperTeamLeaderboard(ctx context.Context, params sqlc.GetFullProjectSuperTeamLeaderboardParams) ([]*sqlc.GetFullProjectSuperTeamLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFullProjectSuperTeamLeaderboard")
	}

	var r0 []*sqlc.GetFullProjectSuperTeamLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullProjectSuperTeamLeaderboardParams) ([]*sqlc.GetFullProjectSuperTeamLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullProjectSuperTeamLeaderboardParams) []*sqlc.GetFullProjectSuperTeamLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetFullProjectSuperTeamLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetFullProjectSuperTeamLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetFullProjectSuperTeamLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFullProjectSuperTeamLeaderboard'
type MockLeaderboardQuerier_GetFullProjectSuperTeamLeaderboard_Call struct {
	*mock.Call
}

// GetFullProjectSuperTeamLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetFullProjectSuperTeamLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetFullProjectSuperTeamLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetFullProjectSuperTeamLeaderboard_Call {
	return &MockLeaderboardQuerier_GetFullProjectSuperTeamLeaderboard_Call{Call: _e.mock.On("GetFullProjectSuperTeamLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetFullProjectSuperTeamLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetFullProjectSuperTeamLeaderboardParams)) *MockLeaderboardQuerier_GetFullProjectSuperTeamLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetFullProjectSuperTeamLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetFullProjectSuperTeamLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullProjectSuperTeamLeaderboard_Call) Return(getFullProjectSuperTeamLeaderboardRows []*sqlc.GetFullProjectSuperTeamLeaderboardRow, err error) *MockLeaderboardQuerier_GetFullProjectSuperTeamLeaderboard_Call {
	_c.Call.Return(getFullProjectSuperTeamLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullProjectSuperTeamLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetFullProjectSuperTeamLeaderboardParams) ([]*sqlc.GetFullProjectSuperTeamLeaderboardRow, error)) *MockLeaderboardQuerier_GetFullProjectSuperTeamLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetFullProjectTeamLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetFullProjectTeamLeaderboard(ctx context.Context, params sqlc.GetFullProjectTeamLeaderboardParams) ([]*sqlc.GetFullProjectTeamLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFullProjectTeamLeaderboard")
	}

	var r0 []*sqlc.GetFullProjectTeamLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullProjectTeamLeaderboardParams) ([]*sqlc.GetFullProjectTeamLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetFullProjectTeamLeaderboardParams) []*sqlc.GetFullProjectTeamLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetFullProjectTeamLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetFullProjectTeamLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetFullProjectTeamLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFullProjectTeamLeaderboard'
type MockLeaderboardQuerier_GetFullProjectTeamLeaderboard_Call struct {
	*mock.Call
}

// GetFullProjectTeamLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetFullProjectTeamLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetFullProjectTeamLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetFullProjectTeamLeaderboard_Call {
	return &MockLeaderboardQuerier_GetFullProjectTeamLeaderboard_Call{Call: _e.mock.On("GetFullProjectTeamLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetFullProjectTeamLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetFullProjectTeamLeaderboardParams)) *MockLeaderboardQuerier_GetFullProjectTeamLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetFullProjectTeamLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetFullProjectTeamLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullProjectTeamLeaderboard_Call) Return(getFullProjectTeamLeaderboardRows []*sqlc.GetFullProjectTeamLeaderboardRow, err error) *MockLeaderboardQuerier_GetFullProjectTeamLeaderboard_Call {
	_c.Call.Return(getFullProjectTeamLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetFullProjectTeamLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetFullProjectTeamLeaderboardParams) ([]*sqlc.GetFullProjectTeamLeaderboardRow, error)) *MockLeaderboardQuerier_GetFullProjectTeamLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectChurchLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetProjectChurchLeaderboard(ctx context.Context, params sqlc.GetProjectChurchLeaderboardParams) ([]*sqlc.GetProjectChurchLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectChurchLeaderboard")
	}

	var r0 []*sqlc.GetProjectChurchLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetProjectChurchLeaderboardParams) ([]*sqlc.GetProjectChurchLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetProjectChurchLeaderboardParams) []*sqlc.GetProjectChurchLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetProjectChurchLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetProjectChurchLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetProjectChurchLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectChurchLeaderboard'
type MockLeaderboardQuerier_GetProjectChurchLeaderboard_Call struct {
	*mock.Call
}

// GetProjectChurchLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetProjectChurchLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetProjectChurchLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetProjectChurchLeaderboard_Call {
	return &MockLeaderboardQuerier_GetProjectChurchLeaderboard_Call{Call: _e.mock.On("GetProjectChurchLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetProjectChurchLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetProjectChurchLeaderboardParams)) *MockLeaderboardQuerier_GetProjectChurchLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetProjectChurchLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetProjectChurchLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetProjectChurchLeaderboard_Call) Return(getProjectChurchLeaderboardRows []*sqlc.GetProjectChurchLeaderboardRow, err error) *MockLeaderboardQuerier_GetProjectChurchLeaderboard_Call {
	_c.Call.Return(getProjectChurchLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetProjectChurchLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetProjectChurchLeaderboardParams) ([]*sqlc.GetProjectChurchLeaderboardRow, error)) *MockLeaderboardQuerier_GetProjectChurchLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectPersonLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetProjectPersonLeaderboard(ctx context.Context, params sqlc.GetProjectPersonLeaderboardParams) ([]*sqlc.GetProjectPersonLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectPersonLeaderboard")
	}

	var r0 []*sqlc.GetProjectPersonLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetProjectPersonLeaderboardParams) ([]*sqlc.GetProjectPersonLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetProjectPersonLeaderboardParams) []*sqlc.GetProjectPersonLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetProjectPersonLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetProjectPersonLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetProjectPersonLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectPersonLeaderboard'
type MockLeaderboardQuerier_GetProjectPersonLeaderboard_Call struct {
	*mock.Call
}

// GetProjectPersonLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetProjectPersonLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetProjectPersonLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetProjectPersonLeaderboard_Call {
	return &MockLeaderboardQuerier_GetProjectPersonLeaderboard_Call{Call: _e.mock.On("GetProjectPersonLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetProjectPersonLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetProjectPersonLeaderboardParams)) *MockLeaderboardQuerier_GetProjectPersonLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetProjectPersonLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetProjectPersonLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetProjectPersonLeaderboard_Call) Return(getProjectPersonLeaderboardRows []*sqlc.GetProjectPersonLeaderboardRow, err error) *MockLeaderboardQuerier_GetProjectPersonLeaderboard_Call {
	_c.Call.Return(getProjectPersonLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetProjectPersonLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetProjectPersonLeaderboardParams) ([]*sqlc.GetProjectPersonLeaderboardRow, error)) *MockLeaderboardQuerier_GetProjectPersonLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectSuperTeamLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetProjectSuperTeamLeaderboard(ctx context.Context, params sqlc.GetProjectSuperTeamLeaderboardParams) ([]*sqlc.GetProjectSuperTeamLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectSuperTeamLeaderboard")
	}

	var r0 []*sqlc.GetProjectSuperTeamLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetProjectSuperTeamLeaderboardParams) ([]*sqlc.GetProjectSuperTeamLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetProjectSuperTeamLeaderboardParams) []*sqlc.GetProjectSuperTeamLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetProjectSuperTeamLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetProjectSuperTeamLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetProjectSuperTeamLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectSuperTeamLeaderboard'
type MockLeaderboardQuerier_GetProjectSuperTeamLeaderboard_Call struct {
	*mock.Call
}

// GetProjectSuperTeamLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetProjectSuperTeamLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetProjectSuperTeamLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetProjectSuperTeamLeaderboard_Call {
	return &MockLeaderboardQuerier_GetProjectSuperTeamLeaderboard_Call{Call: _e.mock.On("GetProjectSuperTeamLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetProjectSuperTeamLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetProjectSuperTeamLeaderboardParams)) *MockLeaderboardQuerier_GetProjectSuperTeamLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetProjectSuperTeamLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetProjectSuperTeamLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetProjectSuperTeamLeaderboard_Call) Return(getProjectSuperTeamLeaderboardRows []*sqlc.GetProjectSuperTeamLeaderboardRow, err error) *MockLeaderboardQuerier_GetProjectSuperTeamLeaderboard_Call {
	_c.Call.Return(getProjectSuperTeamLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetProjectSuperTeamLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetProjectSuperTeamLeaderboardParams) ([]*sqlc.GetProjectSuperTeamLeaderboardRow, error)) *MockLeaderboardQuerier_GetProjectSuperTeamLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectTeamLeaderboard provides a mock function for the type MockLeaderboardQuerier
func (_mock *MockLeaderboardQuerier) GetProjectTeamLeaderboard(ctx context.Context, params sqlc.GetProjectTeamLeaderboardParams) ([]*sqlc.GetProjectTeamLeaderboardRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectTeamLeaderboard")
	}

	var r0 []*sqlc.GetProjectTeamLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetProjectTeamLeaderboardParams) ([]*sqlc.GetProjectTeamLeaderboardRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetProjectTeamLeaderboardParams) []*sqlc.GetProjectTeamLeaderboardRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.GetProjectTeamLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetProjectTeamLeaderboardParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLeaderboardQuerier_GetProjectTeamLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectTeamLeaderboard'
type MockLeaderboardQuerier_GetProjectTeamLeaderboard_Call struct {
	*mock.Call
}

// GetProjectTeamLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.GetProjectTeamLeaderboardParams
func (_e *MockLeaderboardQuerier_Expecter) GetProjectTeamLeaderboard(ctx any, params any) *MockLeaderboardQuerier_GetProjectTeamLeaderboard_Call {
	return &MockLeaderboardQuerier_GetProjectTeamLeaderboard_Call{Call: _e.mock.On("GetProjectTeamLeaderboard", ctx, params)}
}

func (_c *MockLeaderboardQuerier_GetProjectTeamLeaderboard_Call) Run(run func(ctx context.Context, params sqlc.GetProjectTeamLeaderboardParams)) *MockLeaderboardQuerier_GetProjectTeamLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetProjectTeamLeaderboardParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetProjectTeamLeaderboardParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLeaderboardQuerier_GetProjectTeamLeaderboard_Call) Return(getProjectTeamLeaderboardRows []*sqlc.GetProjectTeamLeaderboardRow, err error) *MockLeaderboardQuerier_GetProjectTeamLeaderboard_Call {
	_c.Call.Return(getProjectTeamLeaderboardRows, err)
	return _c
}

func (_c *MockLeaderboardQuerier_GetProjectTeamLeaderboard_Call) RunAndReturn(run func(ctx context.Context, params sqlc.GetProjectTeamLeaderboardParams) ([]*sqlc.GetProjectTeamLeaderboardRow, error)) *MockLeaderboardQuerier_GetProjectTeamLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}
