// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bcc-media/wayfarer/internal/database/sqlc"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSettingsQuerier creates a new instance of MockSettingsQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettingsQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettingsQuerier {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSettingsQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSettingsQuerier is an autogenerated mock type for the SettingsQuerier type
type MockSettingsQuerier struct {
	mock.Mock
}

type MockSettingsQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettingsQuerier) EXPECT() *MockSettingsQuerier_Expecter {
	return &MockSettingsQuerier_Expecter{mock: &_m.Mock}
}

// GetAllSettings provides a mock function for the type MockSettingsQuerier
func (_mock *MockSettingsQuerier) GetAllSettings(ctx context.Context) ([]*sqlc.Setting, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSettings")
	}

	var r0 []*sqlc.Setting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*sqlc.Setting, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*sqlc.Setting); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlc.Setting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingsQuerier_GetAllSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSettings'
type MockSettingsQuerier_GetAllSettings_Call struct {
	*mock.Call
}

// GetAllSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSettingsQuerier_Expecter) GetAllSettings(ctx any) *MockSettingsQuerier_GetAllSettings_Call {
	return &MockSettingsQuerier_GetAllSettings_Call{Call: _e.mock.On("GetAllSettings", ctx)}
}

func (_c *MockSettingsQuerier_GetAllSettings_Call) Run(run func(ctx context.Context)) *MockSettingsQuerier_GetAllSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSettingsQuerier_GetAllSettings_Call) Return(settings []*sqlc.Setting, err error) *MockSettingsQuerier_GetAllSettings_Call {
	_c.Call.Return(settings, err)
	return _c
}

func (_c *MockSettingsQuerier_GetAllSettings_Call) RunAndReturn(run func(ctx context.Context) ([]*sqlc.Setting, error)) *MockSettingsQuerier_GetAllSettings_Call {
	_c.Call.Return(run)
	return _c
}

// ProjectExists provides a mock function for the type MockSettingsQuerier
func (_mock *MockSettingsQuerier) ProjectExists(ctx context.Context, projectID string) (bool, error) {
	ret := _mock.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ProjectExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, projectID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingsQuerier_ProjectExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectExists'
type MockSettingsQuerier_ProjectExists_Call struct {
	*mock.Call
}

// ProjectExists is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
func (_e *MockSettingsQuerier_Expecter) ProjectExists(ctx any, projectID any) *MockSettingsQuerier_ProjectExists_Call {
	return &MockSettingsQuerier_ProjectExists_Call{Call: _e.mock.On("ProjectExists", ctx, projectID)}
}

func (_c *MockSettingsQuerier_ProjectExists_Call) Run(run func(ctx context.Context, projectID string)) *MockSettingsQuerier_ProjectExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettingsQuerier_ProjectExists_Call) Return(b bool, err error) *MockSettingsQuerier_ProjectExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSettingsQuerier_ProjectExists_Call) RunAndReturn(run func(ctx context.Context, projectID string) (bool, error)) *MockSettingsQuerier_ProjectExists_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSettingBool provides a mock function for the type MockSettingsQuerier
func (_mock *MockSettingsQuerier) UpdateSettingBool(ctx context.Context, arg sqlc.UpdateSettingBoolParams) (int64, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettingBool")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateSettingBoolParams) (int64, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateSettingBoolParams) int64); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.UpdateSettingBoolParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingsQuerier_UpdateSettingBool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSettingBool'
type MockSettingsQuerier_UpdateSettingBool_Call struct {
	*mock.Call
}

// UpdateSettingBool is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateSettingBoolParams
func (_e *MockSettingsQuerier_Expecter) UpdateSettingBool(ctx any, arg any) *MockSettingsQuerier_UpdateSettingBool_Call {
	return &MockSettingsQuerier_UpdateSettingBool_Call{Call: _e.mock.On("UpdateSettingBool", ctx, arg)}
}

func (_c *MockSettingsQuerier_UpdateSettingBool_Call) Run(run func(ctx context.Context, arg sqlc.UpdateSettingBoolParams)) *MockSettingsQuerier_UpdateSettingBool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateSettingBoolParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateSettingBoolParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettingsQuerier_UpdateSettingBool_Call) Return(n int64, err error) *MockSettingsQuerier_UpdateSettingBool_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSettingsQuerier_UpdateSettingBool_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateSettingBoolParams) (int64, error)) *MockSettingsQuerier_UpdateSettingBool_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSettingFloat provides a mock function for the type MockSettingsQuerier
func (_mock *MockSettingsQuerier) UpdateSettingFloat(ctx context.Context, arg sqlc.UpdateSettingFloatParams) (int64, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettingFloat")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateSettingFloatParams) (int64, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateSettingFloatParams) int64); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.UpdateSettingFloatParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingsQuerier_UpdateSettingFloat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSettingFloat'
type MockSettingsQuerier_UpdateSettingFloat_Call struct {
	*mock.Call
}

// UpdateSettingFloat is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateSettingFloatParams
func (_e *MockSettingsQuerier_Expecter) UpdateSettingFloat(ctx any, arg any) *MockSettingsQuerier_UpdateSettingFloat_Call {
	return &MockSettingsQuerier_UpdateSettingFloat_Call{Call: _e.mock.On("UpdateSettingFloat", ctx, arg)}
}

func (_c *MockSettingsQuerier_UpdateSettingFloat_Call) Run(run func(ctx context.Context, arg sqlc.UpdateSettingFloatParams)) *MockSettingsQuerier_UpdateSettingFloat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateSettingFloatParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateSettingFloatParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettingsQuerier_UpdateSettingFloat_Call) Return(n int64, err error) *MockSettingsQuerier_UpdateSettingFloat_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSettingsQuerier_UpdateSettingFloat_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateSettingFloatParams) (int64, error)) *MockSettingsQuerier_UpdateSettingFloat_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSettingInt provides a mock function for the type MockSettingsQuerier
func (_mock *MockSettingsQuerier) UpdateSettingInt(ctx context.Context, arg sqlc.UpdateSettingIntParams) (int64, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettingInt")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateSettingIntParams) (int64, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateSettingIntParams) int64); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.UpdateSettingIntParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingsQuerier_UpdateSettingInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSettingInt'
type MockSettingsQuerier_UpdateSettingInt_Call struct {
	*mock.Call
}

// UpdateSettingInt is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateSettingIntParams
func (_e *MockSettingsQuerier_Expecter) UpdateSettingInt(ctx any, arg any) *MockSettingsQuerier_UpdateSettingInt_Call {
	return &MockSettingsQuerier_UpdateSettingInt_Call{Call: _e.mock.On("UpdateSettingInt", ctx, arg)}
}

func (_c *MockSettingsQuerier_UpdateSettingInt_Call) Run(run func(ctx context.Context, arg sqlc.UpdateSettingIntParams)) *MockSettingsQuerier_UpdateSettingInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateSettingIntParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateSettingIntParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettingsQuerier_UpdateSettingInt_Call) Return(n int64, err error) *MockSettingsQuerier_UpdateSettingInt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSettingsQuerier_UpdateSettingInt_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateSettingIntParams) (int64, error)) *MockSettingsQuerier_UpdateSettingInt_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSettingJSON provides a mock function for the type MockSettingsQuerier
func (_mock *MockSettingsQuerier) UpdateSettingJSON(ctx context.Context, arg sqlc.UpdateSettingJSONParams) (int64, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettingJSON")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateSettingJSONParams) (int64, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateSettingJSONParams) int64); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.UpdateSettingJSONParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingsQuerier_UpdateSettingJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSettingJSON'
type MockSettingsQuerier_UpdateSettingJSON_Call struct {
	*mock.Call
}

// UpdateSettingJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateSettingJSONParams
func (_e *MockSettingsQuerier_Expecter) UpdateSettingJSON(ctx any, arg any) *MockSettingsQuerier_UpdateSettingJSON_Call {
	return &MockSettingsQuerier_UpdateSettingJSON_Call{Call: _e.mock.On("UpdateSettingJSON", ctx, arg)}
}

func (_c *MockSettingsQuerier_UpdateSettingJSON_Call) Run(run func(ctx context.Context, arg sqlc.UpdateSettingJSONParams)) *MockSettingsQuerier_UpdateSettingJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateSettingJSONParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateSettingJSONParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettingsQuerier_UpdateSettingJSON_Call) Return(n int64, err error) *MockSettingsQuerier_UpdateSettingJSON_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSettingsQuerier_UpdateSettingJSON_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateSettingJSONParams) (int64, error)) *MockSettingsQuerier_UpdateSettingJSON_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSettingText provides a mock function for the type MockSettingsQuerier
func (_mock *MockSettingsQuerier) UpdateSettingText(ctx context.Context, arg sqlc.UpdateSettingTextParams) (int64, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettingText")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateSettingTextParams) (int64, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateSettingTextParams) int64); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.UpdateSettingTextParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingsQuerier_UpdateSettingText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSettingText'
type MockSettingsQuerier_UpdateSettingText_Call struct {
	*mock.Call
}

// UpdateSettingText is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateSettingTextParams
func (_e *MockSettingsQuerier_Expecter) UpdateSettingText(ctx any, arg any) *MockSettingsQuerier_UpdateSettingText_Call {
	return &MockSettingsQuerier_UpdateSettingText_Call{Call: _e.mock.On("UpdateSettingText", ctx, arg)}
}

func (_c *MockSettingsQuerier_UpdateSettingText_Call) Run(run func(ctx context.Context, arg sqlc.UpdateSettingTextParams)) *MockSettingsQuerier_UpdateSettingText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateSettingTextParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateSettingTextParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettingsQuerier_UpdateSettingText_Call) Return(n int64, err error) *MockSettingsQuerier_UpdateSettingText_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSettingsQuerier_UpdateSettingText_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateSettingTextParams) (int64, error)) *MockSettingsQuerier_UpdateSettingText_Call {
	_c.Call.Return(run)
	return _c
}
