// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboards.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountEventChurchLeaderboard = `-- name: CountEventChurchLeaderboard :one
SELECT COUNT(DISTINCT c.id)::bigint AS total
FROM churches c
INNER JOIN users u ON c.id = u.church_id
INNER JOIN user_events ue ON u.id = ue.user_id
WHERE
    ue.event_id = $1::text
    AND ($2::text = '' OR c.country = $2::text)
    AND ($3::text = '' OR c.category = $3::text)
`

type CountEventChurchLeaderboardParams struct {
	Eventid        string `json:"eventid"`
	Country        string `json:"country"`
	Churchcategory string `json:"churchcategory"`
}

func (q *Queries) CountEventChurchLeaderboard(ctx context.Context, arg CountEventChurchLeaderboardParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountEventChurchLeaderboard, arg.Eventid, arg.Country, arg.Churchcategory)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const CountEventPersonLeaderboard = `-- name: CountEventPersonLeaderboard :one
SELECT COUNT(DISTINCT u.id)::bigint AS total
FROM users u
INNER JOIN user_events ue ON u.id = ue.user_id
WHERE
    ue.event_id = $1::text
    AND ($2::text = '' OR u.church_id = $2::text)
    AND ($3::text = '' OR EXISTS (
        SELECT 1 FROM churches c WHERE c.id = u.church_id AND c.country = $3::text
    ))
    AND ($4::text = '' OR EXISTS (
        SELECT 1 FROM churches c WHERE c.id = u.church_id AND c.category = $4::text
    ))
    AND ($5::text = '' OR u.gender = $5::text)
    AND ($6::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) >= $6::int)
    AND ($7::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) <= $7::int)
`

type CountEventPersonLeaderboardParams struct {
	Eventid        string `json:"eventid"`
	Churchid       string `json:"churchid"`
	Country        string `json:"country"`
	Churchcategory string `json:"churchcategory"`
	Gender         string `json:"gender"`
	Minage         int32  `json:"minage"`
	Maxage         int32  `json:"maxage"`
}

func (q *Queries) CountEventPersonLeaderboard(ctx context.Context, arg CountEventPersonLeaderboardParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountEventPersonLeaderboard,
		arg.Eventid,
		arg.Churchid,
		arg.Country,
		arg.Churchcategory,
		arg.Gender,
		arg.Minage,
		arg.Maxage,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const CountEventSuperTeamLeaderboard = `-- name: CountEventSuperTeamLeaderboard :one
WITH event_project AS (
    SELECT project_id FROM events WHERE id = $1::text
)
SELECT COUNT(DISTINCT st.id)::bigint AS total
FROM super_teams st
CROSS JOIN event_project ep
WHERE st.project_id = ep.project_id
`

func (q *Queries) CountEventSuperTeamLeaderboard(ctx context.Context, eventid string) (int64, error) {
	row := q.db.QueryRow(ctx, CountEventSuperTeamLeaderboard, eventid)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const CountEventTeamLeaderboard = `-- name: CountEventTeamLeaderboard :one
WITH event_project AS (
    SELECT project_id FROM events WHERE id = $2::text
)
SELECT COUNT(DISTINCT t.id)::bigint AS total
FROM teams t
CROSS JOIN event_project ep
WHERE t.project_id = ep.project_id
  AND t.leaderboard_excluded = false
  -- Church filter: team has ANY member from specified church
  AND ($1::text = '' OR EXISTS (
      SELECT 1 FROM team_members tm
      INNER JOIN users u ON tm.user_id = u.id
      WHERE tm.team_id = t.id AND u.church_id = $1::text
  ))
`

type CountEventTeamLeaderboardParams struct {
	Churchid string `json:"churchid"`
	Eventid  string `json:"eventid"`
}

func (q *Queries) CountEventTeamLeaderboard(ctx context.Context, arg CountEventTeamLeaderboardParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountEventTeamLeaderboard, arg.Churchid, arg.Eventid)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const CountProjectChurchLeaderboard = `-- name: CountProjectChurchLeaderboard :one
SELECT COUNT(DISTINCT c.id)::bigint AS total
FROM churches c
INNER JOIN users u ON c.id = u.church_id
INNER JOIN user_projects up ON u.id = up.user_id
WHERE
    up.project_id = $1::text
    AND ($2::text = '' OR c.country = $2::text)
    AND ($3::text = '' OR c.category = $3::text)
`

type CountProjectChurchLeaderboardParams struct {
	Projectid      string `json:"projectid"`
	Country        string `json:"country"`
	Churchcategory string `json:"churchcategory"`
}

func (q *Queries) CountProjectChurchLeaderboard(ctx context.Context, arg CountProjectChurchLeaderboardParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountProjectChurchLeaderboard, arg.Projectid, arg.Country, arg.Churchcategory)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const CountProjectPersonLeaderboard = `-- name: CountProjectPersonLeaderboard :one
WITH project_users AS MATERIALIZED (
    -- Start with users in THIS project
    SELECT DISTINCT u.id, u.birthdate, u.church_id, u.gender
    FROM user_projects up
    INNER JOIN users u ON up.user_id = u.id
    WHERE up.project_id = $5::text
      AND ($6::text = '' OR u.church_id = $6::text)
      AND ($7::text = '' OR u.gender = $7::text)
      AND ($8::text = '' OR EXISTS (
          SELECT 1 FROM team_members tm
          WHERE tm.user_id = u.id AND tm.team_id = $8::text
      ))
      AND ($9::text = '' OR EXISTS (
          SELECT 1 FROM team_members tm
          INNER JOIN teams t ON tm.team_id = t.id
          WHERE tm.user_id = u.id AND t.super_team_id = $9::text
      ))
)
SELECT COUNT(*)::bigint AS total
FROM project_users pu
WHERE ($1::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM pu.birthdate)) >= $1::int)
  AND ($2::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM pu.birthdate)) <= $2::int)
  AND ($3::text = '' OR EXISTS (
      SELECT 1 FROM churches c
      WHERE c.id = pu.church_id AND c.country = $3::text
  ))
  AND ($4::text = '' OR EXISTS (
      SELECT 1 FROM churches c
      WHERE c.id = pu.church_id AND c.category = $4::text
  ))
`

type CountProjectPersonLeaderboardParams struct {
	Minage         int32  `json:"minage"`
	Maxage         int32  `json:"maxage"`
	Country        string `json:"country"`
	Churchcategory string `json:"churchcategory"`
	Projectid      string `json:"projectid"`
	Churchid       string `json:"churchid"`
	Gender         string `json:"gender"`
	Teamid         string `json:"teamid"`
	Superteamid    string `json:"superteamid"`
}

func (q *Queries) CountProjectPersonLeaderboard(ctx context.Context, arg CountProjectPersonLeaderboardParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountProjectPersonLeaderboard,
		arg.Minage,
		arg.Maxage,
		arg.Country,
		arg.Churchcategory,
		arg.Projectid,
		arg.Churchid,
		arg.Gender,
		arg.Teamid,
		arg.Superteamid,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const CountProjectSuperTeamLeaderboard = `-- name: CountProjectSuperTeamLeaderboard :one
SELECT COUNT(DISTINCT st.id)::bigint AS total
FROM super_teams st
WHERE st.project_id = $1::text
`

func (q *Queries) CountProjectSuperTeamLeaderboard(ctx context.Context, projectid string) (int64, error) {
	row := q.db.QueryRow(ctx, CountProjectSuperTeamLeaderboard, projectid)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const CountProjectTeamLeaderboard = `-- name: CountProjectTeamLeaderboard :one
SELECT COUNT(DISTINCT t.id)::bigint AS total
FROM teams t
WHERE
    t.project_id = $1::text
    AND t.leaderboard_excluded = false
    AND ($2::text = '' OR t.super_team_id = $2::text)
    -- Church filter: team has ANY member from specified church
    AND ($3::text = '' OR EXISTS (
        SELECT 1 FROM team_members tm
        INNER JOIN users u ON tm.user_id = u.id
        WHERE tm.team_id = t.id AND u.church_id = $3::text
    ))
`

type CountProjectTeamLeaderboardParams struct {
	Projectid   string `json:"projectid"`
	Superteamid string `json:"superteamid"`
	Churchid    string `json:"churchid"`
}

func (q *Queries) CountProjectTeamLeaderboard(ctx context.Context, arg CountProjectTeamLeaderboardParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountProjectTeamLeaderboard, arg.Projectid, arg.Superteamid, arg.Churchid)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const FindMyEventChurchPosition = `-- name: FindMyEventChurchPosition :one
WITH ranked_scores AS (
    SELECT
        c.id AS entity_id,
        c.name,
        NULL::text AS image,
        lec.score,
        lec.last_score_at,
        DENSE_RANK() OVER (ORDER BY lec.score DESC) AS rank
    FROM leaderboard_event_churches lec
    INNER JOIN churches c ON lec.church_id = c.id
    WHERE lec.event_id = $1::text
      AND lec.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR lec.score <= $3::int)
),
user_church AS (
    SELECT church_id
    FROM users
    WHERE id = $4::text
)
SELECT rs.entity_id, rs.name, rs.image, rs.score, rs.rank, rs.last_score_at
FROM ranked_scores rs
INNER JOIN user_church uc ON rs.entity_id = uc.church_id
`

type FindMyEventChurchPositionParams struct {
	Eventid  string `json:"eventid"`
	Minscore int32  `json:"minscore"`
	Maxscore int32  `json:"maxscore"`
	Userid   string `json:"userid"`
}

type FindMyEventChurchPositionRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) FindMyEventChurchPosition(ctx context.Context, arg FindMyEventChurchPositionParams) (*FindMyEventChurchPositionRow, error) {
	row := q.db.QueryRow(ctx, FindMyEventChurchPosition,
		arg.Eventid,
		arg.Minscore,
		arg.Maxscore,
		arg.Userid,
	)
	var i FindMyEventChurchPositionRow
	err := row.Scan(
		&i.EntityID,
		&i.Name,
		&i.Image,
		&i.Score,
		&i.Rank,
		&i.LastScoreAt,
	)
	return &i, err
}

const FindMyEventPersonPosition = `-- name: FindMyEventPersonPosition :one
WITH ranked_scores AS (
    SELECT
        u.id AS entity_id,
        COALESCE(u.display_name, u.name) AS name,
        c.name AS church_name,
        u.avatar_url AS image,
        lep.score,
        lep.last_score_at,
        DENSE_RANK() OVER (ORDER BY lep.score DESC) AS rank
    FROM leaderboard_event_persons lep
    INNER JOIN users u ON lep.user_id = u.id
    INNER JOIN churches c ON u.church_id = c.id
    WHERE lep.event_id = $2::text
      AND lep.score >= COALESCE($3::int, 1)
      AND ($4::int IS NULL OR lep.score <= $4::int)
      AND ($5::text = '' OR u.church_id = $5::text)
)
SELECT entity_id, name, church_name, image, score, rank, last_score_at
FROM ranked_scores
WHERE entity_id = $1::text
`

type FindMyEventPersonPositionParams struct {
	Userid   string `json:"userid"`
	Eventid  string `json:"eventid"`
	Minscore int32  `json:"minscore"`
	Maxscore int32  `json:"maxscore"`
	Churchid string `json:"churchid"`
}

type FindMyEventPersonPositionRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	ChurchName  string             `json:"church_name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) FindMyEventPersonPosition(ctx context.Context, arg FindMyEventPersonPositionParams) (*FindMyEventPersonPositionRow, error) {
	row := q.db.QueryRow(ctx, FindMyEventPersonPosition,
		arg.Userid,
		arg.Eventid,
		arg.Minscore,
		arg.Maxscore,
		arg.Churchid,
	)
	var i FindMyEventPersonPositionRow
	err := row.Scan(
		&i.EntityID,
		&i.Name,
		&i.ChurchName,
		&i.Image,
		&i.Score,
		&i.Rank,
		&i.LastScoreAt,
	)
	return &i, err
}

const FindMyEventSuperTeamPosition = `-- name: FindMyEventSuperTeamPosition :one
WITH ranked_scores AS (
    SELECT
        st.id AS entity_id,
        st.name,
        NULL::text AS image,
        les.score,
        les.last_score_at,
        DENSE_RANK() OVER (ORDER BY les.score DESC) AS rank
    FROM leaderboard_event_superteams les
    INNER JOIN super_teams st ON les.super_team_id = st.id
    WHERE les.event_id = $1::text
      AND les.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR les.score <= $3::int)
),
user_superteam AS (
    SELECT t.super_team_id
    FROM team_members tm
    INNER JOIN teams t ON tm.team_id = t.id
    INNER JOIN events e ON t.project_id = e.project_id AND e.id = $1::text
    WHERE tm.user_id = $4::text
      AND t.super_team_id IS NOT NULL
    LIMIT 1
)
SELECT rs.entity_id, rs.name, rs.image, rs.score, rs.rank, rs.last_score_at
FROM ranked_scores rs
INNER JOIN user_superteam ust ON rs.entity_id = ust.super_team_id
`

type FindMyEventSuperTeamPositionParams struct {
	Eventid  string `json:"eventid"`
	Minscore int32  `json:"minscore"`
	Maxscore int32  `json:"maxscore"`
	Userid   string `json:"userid"`
}

type FindMyEventSuperTeamPositionRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) FindMyEventSuperTeamPosition(ctx context.Context, arg FindMyEventSuperTeamPositionParams) (*FindMyEventSuperTeamPositionRow, error) {
	row := q.db.QueryRow(ctx, FindMyEventSuperTeamPosition,
		arg.Eventid,
		arg.Minscore,
		arg.Maxscore,
		arg.Userid,
	)
	var i FindMyEventSuperTeamPositionRow
	err := row.Scan(
		&i.EntityID,
		&i.Name,
		&i.Image,
		&i.Score,
		&i.Rank,
		&i.LastScoreAt,
	)
	return &i, err
}

const FindMyEventTeamPosition = `-- name: FindMyEventTeamPosition :one
WITH ranked_scores AS (
    SELECT
        t.id AS entity_id,
        t.name,
        NULL::text AS image,
        let.score,
        let.last_score_at,
        DENSE_RANK() OVER (ORDER BY let.score DESC) AS rank
    FROM leaderboard_event_teams let
    INNER JOIN teams t ON let.team_id = t.id
    WHERE let.event_id = $1::text
      AND t.leaderboard_excluded = false
      AND let.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR let.score <= $3::int)
      -- Church filter: team has ANY member from specified church
      AND ($4::text = '' OR EXISTS (
          SELECT 1 FROM team_members tm
          INNER JOIN users u ON tm.user_id = u.id
          WHERE tm.team_id = t.id AND u.church_id = $4::text
      ))
),
user_team AS (
    SELECT tm.team_id
    FROM team_members tm
    INNER JOIN teams t ON tm.team_id = t.id
    INNER JOIN events e ON t.project_id = e.project_id AND e.id = $1::text
    WHERE tm.user_id = $5::text
    LIMIT 1
)
SELECT rs.entity_id, rs.name, rs.image, rs.score, rs.rank, rs.last_score_at
FROM ranked_scores rs
INNER JOIN user_team ut ON rs.entity_id = ut.team_id
`

type FindMyEventTeamPositionParams struct {
	Eventid  string `json:"eventid"`
	Minscore int32  `json:"minscore"`
	Maxscore int32  `json:"maxscore"`
	Churchid string `json:"churchid"`
	Userid   string `json:"userid"`
}

type FindMyEventTeamPositionRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) FindMyEventTeamPosition(ctx context.Context, arg FindMyEventTeamPositionParams) (*FindMyEventTeamPositionRow, error) {
	row := q.db.QueryRow(ctx, FindMyEventTeamPosition,
		arg.Eventid,
		arg.Minscore,
		arg.Maxscore,
		arg.Churchid,
		arg.Userid,
	)
	var i FindMyEventTeamPositionRow
	err := row.Scan(
		&i.EntityID,
		&i.Name,
		&i.Image,
		&i.Score,
		&i.Rank,
		&i.LastScoreAt,
	)
	return &i, err
}

const FindMyProjectChurchPosition = `-- name: FindMyProjectChurchPosition :one
WITH ranked_scores AS (
    SELECT
        c.id AS entity_id,
        c.name,
        NULL::text AS image,
        lpc.score,
        lpc.last_score_at,
        DENSE_RANK() OVER (ORDER BY lpc.score DESC) AS rank
    FROM leaderboard_project_churches lpc
    INNER JOIN churches c ON lpc.church_id = c.id
    WHERE lpc.project_id = $1::text
      AND lpc.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR lpc.score <= $3::int)
),
user_church AS (
    SELECT church_id
    FROM users
    WHERE id = $4::text
)
SELECT rs.entity_id, rs.name, rs.image, rs.score, rs.rank, rs.last_score_at
FROM ranked_scores rs
INNER JOIN user_church uc ON rs.entity_id = uc.church_id
`

type FindMyProjectChurchPositionParams struct {
	Projectid string `json:"projectid"`
	Minscore  int32  `json:"minscore"`
	Maxscore  int32  `json:"maxscore"`
	Userid    string `json:"userid"`
}

type FindMyProjectChurchPositionRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) FindMyProjectChurchPosition(ctx context.Context, arg FindMyProjectChurchPositionParams) (*FindMyProjectChurchPositionRow, error) {
	row := q.db.QueryRow(ctx, FindMyProjectChurchPosition,
		arg.Projectid,
		arg.Minscore,
		arg.Maxscore,
		arg.Userid,
	)
	var i FindMyProjectChurchPositionRow
	err := row.Scan(
		&i.EntityID,
		&i.Name,
		&i.Image,
		&i.Score,
		&i.Rank,
		&i.LastScoreAt,
	)
	return &i, err
}

const FindMyProjectPersonPosition = `-- name: FindMyProjectPersonPosition :one
WITH ranked_scores AS (
    SELECT
        u.id AS entity_id,
        COALESCE(u.display_name, u.name) AS name,
        c.name AS church_name,
        u.avatar_url AS image,
        lpp.score,
        lpp.last_score_at,
        DENSE_RANK() OVER (ORDER BY lpp.score DESC) AS rank
    FROM leaderboard_project_persons lpp
    INNER JOIN users u ON lpp.user_id = u.id
    INNER JOIN churches c ON u.church_id = c.id
    WHERE lpp.project_id = $2::text
      AND lpp.score >= COALESCE($3::int, 1)
      AND ($4::int IS NULL OR lpp.score <= $4::int)
      AND ($5::text = '' OR u.church_id = $5::text)
)
SELECT entity_id, name, church_name, image, score, rank, last_score_at
FROM ranked_scores
WHERE entity_id = $1::text
`

type FindMyProjectPersonPositionParams struct {
	Userid    string `json:"userid"`
	Projectid string `json:"projectid"`
	Minscore  int32  `json:"minscore"`
	Maxscore  int32  `json:"maxscore"`
	Churchid  string `json:"churchid"`
}

type FindMyProjectPersonPositionRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	ChurchName  string             `json:"church_name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) FindMyProjectPersonPosition(ctx context.Context, arg FindMyProjectPersonPositionParams) (*FindMyProjectPersonPositionRow, error) {
	row := q.db.QueryRow(ctx, FindMyProjectPersonPosition,
		arg.Userid,
		arg.Projectid,
		arg.Minscore,
		arg.Maxscore,
		arg.Churchid,
	)
	var i FindMyProjectPersonPositionRow
	err := row.Scan(
		&i.EntityID,
		&i.Name,
		&i.ChurchName,
		&i.Image,
		&i.Score,
		&i.Rank,
		&i.LastScoreAt,
	)
	return &i, err
}

const FindMyProjectSuperTeamPosition = `-- name: FindMyProjectSuperTeamPosition :one
WITH ranked_scores AS (
    SELECT
        st.id AS entity_id,
        st.name,
        NULL::text AS image,
        lps.score,
        lps.last_score_at,
        DENSE_RANK() OVER (ORDER BY lps.score DESC) AS rank
    FROM leaderboard_project_superteams lps
    INNER JOIN super_teams st ON lps.super_team_id = st.id
    WHERE lps.project_id = $1::text
      AND lps.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR lps.score <= $3::int)
),
user_superteam AS (
    SELECT t.super_team_id
    FROM team_members tm
    INNER JOIN teams t ON tm.team_id = t.id
    WHERE tm.user_id = $4::text
      AND t.super_team_id IS NOT NULL
      AND t.project_id = $1::text
    LIMIT 1
)
SELECT rs.entity_id, rs.name, rs.image, rs.score, rs.rank, rs.last_score_at
FROM ranked_scores rs
INNER JOIN user_superteam ust ON rs.entity_id = ust.super_team_id
`

type FindMyProjectSuperTeamPositionParams struct {
	Projectid string `json:"projectid"`
	Minscore  int32  `json:"minscore"`
	Maxscore  int32  `json:"maxscore"`
	Userid    string `json:"userid"`
}

type FindMyProjectSuperTeamPositionRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) FindMyProjectSuperTeamPosition(ctx context.Context, arg FindMyProjectSuperTeamPositionParams) (*FindMyProjectSuperTeamPositionRow, error) {
	row := q.db.QueryRow(ctx, FindMyProjectSuperTeamPosition,
		arg.Projectid,
		arg.Minscore,
		arg.Maxscore,
		arg.Userid,
	)
	var i FindMyProjectSuperTeamPositionRow
	err := row.Scan(
		&i.EntityID,
		&i.Name,
		&i.Image,
		&i.Score,
		&i.Rank,
		&i.LastScoreAt,
	)
	return &i, err
}

const FindMyProjectTeamPosition = `-- name: FindMyProjectTeamPosition :one
WITH ranked_scores AS (
    SELECT
        t.id AS entity_id,
        t.name,
        NULL::text AS image,
        lpt.score,
        lpt.last_score_at,
        DENSE_RANK() OVER (ORDER BY lpt.score DESC) AS rank
    FROM leaderboard_project_teams lpt
    INNER JOIN teams t ON lpt.team_id = t.id
    WHERE lpt.project_id = $1::text
      AND t.leaderboard_excluded = false
      AND lpt.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR lpt.score <= $3::int)
      -- Church filter: team has ANY member from specified church
      AND ($4::text = '' OR EXISTS (
          SELECT 1 FROM team_members tm
          INNER JOIN users u ON tm.user_id = u.id
          WHERE tm.team_id = t.id AND u.church_id = $4::text
      ))
),
user_team AS (
    SELECT team_id
    FROM team_members
    WHERE user_id = $5::text
      AND team_id IN (SELECT id FROM teams WHERE project_id = $1::text)
    LIMIT 1
)
SELECT rs.entity_id, rs.name, rs.image, rs.score, rs.rank, rs.last_score_at
FROM ranked_scores rs
INNER JOIN user_team ut ON rs.entity_id = ut.team_id
`

type FindMyProjectTeamPositionParams struct {
	Projectid string `json:"projectid"`
	Minscore  int32  `json:"minscore"`
	Maxscore  int32  `json:"maxscore"`
	Churchid  string `json:"churchid"`
	Userid    string `json:"userid"`
}

type FindMyProjectTeamPositionRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) FindMyProjectTeamPosition(ctx context.Context, arg FindMyProjectTeamPositionParams) (*FindMyProjectTeamPositionRow, error) {
	row := q.db.QueryRow(ctx, FindMyProjectTeamPosition,
		arg.Projectid,
		arg.Minscore,
		arg.Maxscore,
		arg.Churchid,
		arg.Userid,
	)
	var i FindMyProjectTeamPositionRow
	err := row.Scan(
		&i.EntityID,
		&i.Name,
		&i.Image,
		&i.Score,
		&i.Rank,
		&i.LastScoreAt,
	)
	return &i, err
}

const GetEventChurchLeaderboard = `-- name: GetEventChurchLeaderboard :many

WITH church_scores AS (
    SELECT
        c.id AS entity_id,
        c.name,
        NULL::text AS image,
        COALESCE(SUM(sj.points), 0)::bigint AS score,
        MAX(sj.created_at) AS last_score_at
    FROM churches c
    INNER JOIN users u ON c.id = u.church_id
    INNER JOIN user_events ue ON u.id = ue.user_id
    LEFT JOIN score_journal sj ON sj.user_id = u.id AND sj.event_id = $6::text
    WHERE
        ue.event_id = $6::text
        AND ($7::text = '' OR c.country = $7::text)
        AND ($8::text = '' OR c.category = $8::text)
    GROUP BY c.id, c.name
),
ranked_scores AS (
    SELECT
        entity_id,
        name,
        image,
        score,
        last_score_at,
        DENSE_RANK() OVER (ORDER BY score DESC) AS rank
    FROM church_scores
)
SELECT entity_id, name, image, score, rank, last_score_at
FROM ranked_scores
WHERE
    score >= 1
    AND ($1::int IS NULL OR score >= $1::int)
    AND ($2::int IS NULL OR score <= $2::int)
    AND ($3::bigint IS NULL OR rank > $3::bigint)
    AND ($4::bigint IS NULL OR rank < $4::bigint)
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
LIMIT $5::int
`

type GetEventChurchLeaderboardParams struct {
	Minscore       int32  `json:"minscore"`
	Maxscore       int32  `json:"maxscore"`
	Afterrank      *int64 `json:"afterrank"`
	Beforerank     *int64 `json:"beforerank"`
	Querylimit     int32  `json:"querylimit"`
	Eventid        string `json:"eventid"`
	Country        string `json:"country"`
	Churchcategory string `json:"churchcategory"`
}

type GetEventChurchLeaderboardRow struct {
	EntityID    string      `json:"entity_id"`
	Name        string      `json:"name"`
	Image       *string     `json:"image"`
	Score       int64       `json:"score"`
	Rank        int64       `json:"rank"`
	LastScoreAt interface{} `json:"last_score_at"`
}

// ==================== Event Church Leaderboard ====================
func (q *Queries) GetEventChurchLeaderboard(ctx context.Context, arg GetEventChurchLeaderboardParams) ([]*GetEventChurchLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetEventChurchLeaderboard,
		arg.Minscore,
		arg.Maxscore,
		arg.Afterrank,
		arg.Beforerank,
		arg.Querylimit,
		arg.Eventid,
		arg.Country,
		arg.Churchcategory,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEventChurchLeaderboardRow{}
	for rows.Next() {
		var i GetEventChurchLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEventPersonLeaderboard = `-- name: GetEventPersonLeaderboard :many

WITH person_scores AS (
    SELECT
        u.id AS entity_id,
        COALESCE(u.display_name, u.name) AS name,
        c.name AS church_name,
        u.avatar_url AS image,
        COALESCE(SUM(sj.points), 0)::bigint AS score,
        MAX(sj.created_at) AS last_score_at
    FROM users u
    INNER JOIN user_events ue ON u.id = ue.user_id
    INNER JOIN churches c ON u.church_id = c.id
    LEFT JOIN score_journal sj ON sj.user_id = u.id AND sj.event_id = $6::text
    WHERE
        ue.event_id = $6::text
        AND ($7::text = '' OR u.church_id = $7::text)
        AND ($8::text = '' OR EXISTS (
            SELECT 1 FROM churches ch WHERE ch.id = u.church_id AND ch.country = $8::text
        ))
        AND ($9::text = '' OR EXISTS (
            SELECT 1 FROM churches ch WHERE ch.id = u.church_id AND ch.category = $9::text
        ))
        AND ($10::text = '' OR u.gender = $10::text)
        AND ($11::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) >= $11::int)
        AND ($12::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) <= $12::int)
    GROUP BY u.id, u.display_name, u.name, c.name, u.avatar_url
),
ranked_scores AS (
    SELECT
        entity_id,
        name,
        church_name,
        image,
        score,
        last_score_at,
        DENSE_RANK() OVER (ORDER BY score DESC) AS rank
    FROM person_scores
)
SELECT entity_id, name, church_name, image, score, rank, last_score_at
FROM ranked_scores
WHERE
    score >= 1
    AND ($1::int IS NULL OR score >= $1::int)
    AND ($2::int IS NULL OR score <= $2::int)
    AND ($3::bigint IS NULL OR rank > $3::bigint)
    AND ($4::bigint IS NULL OR rank < $4::bigint)
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
LIMIT $5::int
`

type GetEventPersonLeaderboardParams struct {
	Minscore       int32  `json:"minscore"`
	Maxscore       int32  `json:"maxscore"`
	Afterrank      *int64 `json:"afterrank"`
	Beforerank     *int64 `json:"beforerank"`
	Querylimit     int32  `json:"querylimit"`
	Eventid        string `json:"eventid"`
	Churchid       string `json:"churchid"`
	Country        string `json:"country"`
	Churchcategory string `json:"churchcategory"`
	Gender         string `json:"gender"`
	Minage         int32  `json:"minage"`
	Maxage         int32  `json:"maxage"`
}

type GetEventPersonLeaderboardRow struct {
	EntityID    string      `json:"entity_id"`
	Name        string      `json:"name"`
	ChurchName  string      `json:"church_name"`
	Image       *string     `json:"image"`
	Score       int64       `json:"score"`
	Rank        int64       `json:"rank"`
	LastScoreAt interface{} `json:"last_score_at"`
}

// ==================== Event Person Leaderboard ====================
func (q *Queries) GetEventPersonLeaderboard(ctx context.Context, arg GetEventPersonLeaderboardParams) ([]*GetEventPersonLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetEventPersonLeaderboard,
		arg.Minscore,
		arg.Maxscore,
		arg.Afterrank,
		arg.Beforerank,
		arg.Querylimit,
		arg.Eventid,
		arg.Churchid,
		arg.Country,
		arg.Churchcategory,
		arg.Gender,
		arg.Minage,
		arg.Maxage,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEventPersonLeaderboardRow{}
	for rows.Next() {
		var i GetEventPersonLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.ChurchName,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEventSuperTeamLeaderboard = `-- name: GetEventSuperTeamLeaderboard :many

WITH event_project AS (
    SELECT project_id FROM events WHERE id = $6::text
),
superteam_scores AS (
    SELECT
        st.id AS entity_id,
        st.name,
        NULL::text AS image,
        COALESCE(SUM(sj.points), 0)::bigint AS score,
        MAX(sj.created_at) AS last_score_at
    FROM super_teams st
    CROSS JOIN event_project ep
    INNER JOIN teams t ON t.super_team_id = st.id
    INNER JOIN team_members tm ON t.id = tm.team_id
    INNER JOIN users u ON tm.user_id = u.id
    INNER JOIN user_events ue ON u.id = ue.user_id AND ue.event_id = $6::text
    LEFT JOIN score_journal sj ON sj.user_id = u.id AND sj.event_id = $6::text
    WHERE
        st.project_id = ep.project_id
    GROUP BY st.id, st.name
),
ranked_scores AS (
    SELECT
        entity_id,
        name,
        image,
        score,
        last_score_at,
        DENSE_RANK() OVER (ORDER BY score DESC) AS rank
    FROM superteam_scores
)
SELECT entity_id, name, image, score, rank, last_score_at
FROM ranked_scores
WHERE
    score >= 1
    AND ($1::int IS NULL OR score >= $1::int)
    AND ($2::int IS NULL OR score <= $2::int)
    AND ($3::bigint IS NULL OR rank > $3::bigint)
    AND ($4::bigint IS NULL OR rank < $4::bigint)
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
LIMIT $5::int
`

type GetEventSuperTeamLeaderboardParams struct {
	Minscore   int32  `json:"minscore"`
	Maxscore   int32  `json:"maxscore"`
	Afterrank  *int64 `json:"afterrank"`
	Beforerank *int64 `json:"beforerank"`
	Querylimit int32  `json:"querylimit"`
	Eventid    string `json:"eventid"`
}

type GetEventSuperTeamLeaderboardRow struct {
	EntityID    string      `json:"entity_id"`
	Name        string      `json:"name"`
	Image       *string     `json:"image"`
	Score       int64       `json:"score"`
	Rank        int64       `json:"rank"`
	LastScoreAt interface{} `json:"last_score_at"`
}

// ==================== Event SuperTeam Leaderboard ====================
func (q *Queries) GetEventSuperTeamLeaderboard(ctx context.Context, arg GetEventSuperTeamLeaderboardParams) ([]*GetEventSuperTeamLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetEventSuperTeamLeaderboard,
		arg.Minscore,
		arg.Maxscore,
		arg.Afterrank,
		arg.Beforerank,
		arg.Querylimit,
		arg.Eventid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEventSuperTeamLeaderboardRow{}
	for rows.Next() {
		var i GetEventSuperTeamLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEventTeamLeaderboard = `-- name: GetEventTeamLeaderboard :many

WITH event_project AS (
    SELECT project_id FROM events WHERE id = $6::text
),
team_scores AS (
    SELECT
        t.id AS entity_id,
        t.name,
        NULL::text AS image,
        COALESCE(SUM(sj.points), 0)::bigint AS score,
        MAX(sj.created_at) AS last_score_at
    FROM teams t
    CROSS JOIN event_project ep
    INNER JOIN team_members tm ON t.id = tm.team_id
    INNER JOIN users u ON tm.user_id = u.id
    INNER JOIN user_events ue ON u.id = ue.user_id AND ue.event_id = $6::text
    LEFT JOIN score_journal sj ON sj.user_id = u.id AND sj.event_id = $6::text
    WHERE
        t.project_id = ep.project_id
        AND t.leaderboard_excluded = false
        -- Church filter: team has ANY member from specified church
        AND ($7::text = '' OR EXISTS (
            SELECT 1 FROM team_members tm2
            INNER JOIN users u2 ON tm2.user_id = u2.id
            WHERE tm2.team_id = t.id AND u2.church_id = $7::text
        ))
    GROUP BY t.id, t.name
),
ranked_scores AS (
    SELECT
        entity_id,
        name,
        image,
        score,
        last_score_at,
        DENSE_RANK() OVER (ORDER BY score DESC) AS rank
    FROM team_scores
)
SELECT entity_id, name, image, score, rank, last_score_at
FROM ranked_scores
WHERE
    score >= 1
    AND ($1::int IS NULL OR score >= $1::int)
    AND ($2::int IS NULL OR score <= $2::int)
    AND ($3::bigint IS NULL OR rank > $3::bigint)
    AND ($4::bigint IS NULL OR rank < $4::bigint)
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
LIMIT $5::int
`

type GetEventTeamLeaderboardParams struct {
	Minscore   int32  `json:"minscore"`
	Maxscore   int32  `json:"maxscore"`
	Afterrank  *int64 `json:"afterrank"`
	Beforerank *int64 `json:"beforerank"`
	Querylimit int32  `json:"querylimit"`
	Eventid    string `json:"eventid"`
	Churchid   string `json:"churchid"`
}

type GetEventTeamLeaderboardRow struct {
	EntityID    string      `json:"entity_id"`
	Name        string      `json:"name"`
	Image       *string     `json:"image"`
	Score       int64       `json:"score"`
	Rank        int64       `json:"rank"`
	LastScoreAt interface{} `json:"last_score_at"`
}

// ==================== Event Team Leaderboard ====================
func (q *Queries) GetEventTeamLeaderboard(ctx context.Context, arg GetEventTeamLeaderboardParams) ([]*GetEventTeamLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetEventTeamLeaderboard,
		arg.Minscore,
		arg.Maxscore,
		arg.Afterrank,
		arg.Beforerank,
		arg.Querylimit,
		arg.Eventid,
		arg.Churchid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEventTeamLeaderboardRow{}
	for rows.Next() {
		var i GetEventTeamLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFullEventChurchLeaderboard = `-- name: GetFullEventChurchLeaderboard :many
WITH ranked_scores AS (
    SELECT
        c.id AS entity_id,
        c.name,
        NULL::text AS image,
        lec.score,
        lec.last_score_at,
        DENSE_RANK() OVER (ORDER BY lec.score DESC) AS rank
    FROM leaderboard_event_churches lec
    INNER JOIN churches c ON lec.church_id = c.id
    WHERE lec.event_id = $1::text
      AND lec.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR lec.score <= $3::int)
)
SELECT entity_id, name, image, score, rank, last_score_at
FROM ranked_scores
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
`

type GetFullEventChurchLeaderboardParams struct {
	Eventid  string `json:"eventid"`
	Minscore int32  `json:"minscore"`
	Maxscore int32  `json:"maxscore"`
}

type GetFullEventChurchLeaderboardRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) GetFullEventChurchLeaderboard(ctx context.Context, arg GetFullEventChurchLeaderboardParams) ([]*GetFullEventChurchLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetFullEventChurchLeaderboard, arg.Eventid, arg.Minscore, arg.Maxscore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetFullEventChurchLeaderboardRow{}
	for rows.Next() {
		var i GetFullEventChurchLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFullEventPersonLeaderboard = `-- name: GetFullEventPersonLeaderboard :many
WITH ranked_scores AS (
    SELECT
        u.id AS entity_id,
        COALESCE(u.display_name, u.name) AS name,
        c.name AS church_name,
        u.avatar_url AS image,
        lep.score,
        lep.last_score_at,
        DENSE_RANK() OVER (ORDER BY lep.score DESC) AS rank
    FROM leaderboard_event_persons lep
    INNER JOIN users u ON lep.user_id = u.id
    INNER JOIN churches c ON u.church_id = c.id
    WHERE lep.event_id = $1::text
      AND lep.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR lep.score <= $3::int)
      AND ($4::text = '' OR u.church_id = $4::text)
      AND ($5::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) >= $5::int)
      AND ($6::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) <= $6::int)
      -- Team filtering
      AND ($7::text = '' OR EXISTS (
          SELECT 1 FROM team_members tm
          WHERE tm.user_id = u.id AND tm.team_id = $7::text
      ))
      AND ($8::text = '' OR EXISTS (
          SELECT 1 FROM team_members tm
          INNER JOIN teams t ON tm.team_id = t.id
          WHERE tm.user_id = u.id AND t.super_team_id = $8::text
      ))
      -- Consent filter: skip if team-filtered, otherwise require leaderboard_consent
      AND (
          $7::text != '' OR $8::text != ''
          OR EXISTS (
              SELECT 1 FROM user_consent_history uch
              WHERE uch.user_id = u.id
                AND uch.consent_key = 'leaderboard_consent'
                AND uch.action = 'ACCEPTED'
                AND uch.occurred_at = (
                    SELECT MAX(uch2.occurred_at)
                    FROM user_consent_history uch2
                    WHERE uch2.user_id = u.id
                      AND uch2.consent_key = 'leaderboard_consent'
                )
          )
      )
)
SELECT entity_id, name, church_name, image, score, rank, last_score_at
FROM ranked_scores
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
`

type GetFullEventPersonLeaderboardParams struct {
	Eventid     string `json:"eventid"`
	Minscore    int32  `json:"minscore"`
	Maxscore    int32  `json:"maxscore"`
	Churchid    string `json:"churchid"`
	Minage      int32  `json:"minage"`
	Maxage      int32  `json:"maxage"`
	Teamid      string `json:"teamid"`
	Superteamid string `json:"superteamid"`
}

type GetFullEventPersonLeaderboardRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	ChurchName  string             `json:"church_name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) GetFullEventPersonLeaderboard(ctx context.Context, arg GetFullEventPersonLeaderboardParams) ([]*GetFullEventPersonLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetFullEventPersonLeaderboard,
		arg.Eventid,
		arg.Minscore,
		arg.Maxscore,
		arg.Churchid,
		arg.Minage,
		arg.Maxage,
		arg.Teamid,
		arg.Superteamid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetFullEventPersonLeaderboardRow{}
	for rows.Next() {
		var i GetFullEventPersonLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.ChurchName,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFullEventSuperTeamLeaderboard = `-- name: GetFullEventSuperTeamLeaderboard :many
WITH ranked_scores AS (
    SELECT
        st.id AS entity_id,
        st.name,
        NULL::text AS image,
        lest.score,
        lest.last_score_at,
        DENSE_RANK() OVER (ORDER BY lest.score DESC) AS rank
    FROM leaderboard_event_superteams lest
    INNER JOIN super_teams st ON lest.super_team_id = st.id
    WHERE lest.event_id = $1::text
      AND lest.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR lest.score <= $3::int)
)
SELECT entity_id, name, image, score, rank, last_score_at
FROM ranked_scores
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
`

type GetFullEventSuperTeamLeaderboardParams struct {
	Eventid  string `json:"eventid"`
	Minscore int32  `json:"minscore"`
	Maxscore int32  `json:"maxscore"`
}

type GetFullEventSuperTeamLeaderboardRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) GetFullEventSuperTeamLeaderboard(ctx context.Context, arg GetFullEventSuperTeamLeaderboardParams) ([]*GetFullEventSuperTeamLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetFullEventSuperTeamLeaderboard, arg.Eventid, arg.Minscore, arg.Maxscore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetFullEventSuperTeamLeaderboardRow{}
	for rows.Next() {
		var i GetFullEventSuperTeamLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFullEventTeamLeaderboard = `-- name: GetFullEventTeamLeaderboard :many
WITH ranked_scores AS (
    SELECT
        t.id AS entity_id,
        t.name,
        NULL::text AS image,
        let.score,
        let.last_score_at,
        DENSE_RANK() OVER (ORDER BY let.score DESC) AS rank
    FROM leaderboard_event_teams let
    INNER JOIN teams t ON let.team_id = t.id
    WHERE let.event_id = $1::text
      AND t.leaderboard_excluded = false
      AND let.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR let.score <= $3::int)
      -- Church filter: team has ANY member from specified church
      AND ($4::text = '' OR EXISTS (
          SELECT 1 FROM team_members tm
          INNER JOIN users u ON tm.user_id = u.id
          WHERE tm.team_id = t.id AND u.church_id = $4::text
      ))
)
SELECT entity_id, name, image, score, rank, last_score_at
FROM ranked_scores
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
`

type GetFullEventTeamLeaderboardParams struct {
	Eventid  string `json:"eventid"`
	Minscore int32  `json:"minscore"`
	Maxscore int32  `json:"maxscore"`
	Churchid string `json:"churchid"`
}

type GetFullEventTeamLeaderboardRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) GetFullEventTeamLeaderboard(ctx context.Context, arg GetFullEventTeamLeaderboardParams) ([]*GetFullEventTeamLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetFullEventTeamLeaderboard,
		arg.Eventid,
		arg.Minscore,
		arg.Maxscore,
		arg.Churchid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetFullEventTeamLeaderboardRow{}
	for rows.Next() {
		var i GetFullEventTeamLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFullProjectChurchLeaderboard = `-- name: GetFullProjectChurchLeaderboard :many
WITH ranked_scores AS (
    SELECT
        c.id AS entity_id,
        c.name,
        NULL::text AS image,
        lpc.score,
        lpc.last_score_at,
        DENSE_RANK() OVER (ORDER BY lpc.score DESC) AS rank
    FROM leaderboard_project_churches lpc
    INNER JOIN churches c ON lpc.church_id = c.id
    WHERE lpc.project_id = $1::text
      AND lpc.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR lpc.score <= $3::int)
)
SELECT entity_id, name, image, score, rank, last_score_at
FROM ranked_scores
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
`

type GetFullProjectChurchLeaderboardParams struct {
	Projectid string `json:"projectid"`
	Minscore  int32  `json:"minscore"`
	Maxscore  int32  `json:"maxscore"`
}

type GetFullProjectChurchLeaderboardRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) GetFullProjectChurchLeaderboard(ctx context.Context, arg GetFullProjectChurchLeaderboardParams) ([]*GetFullProjectChurchLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetFullProjectChurchLeaderboard, arg.Projectid, arg.Minscore, arg.Maxscore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetFullProjectChurchLeaderboardRow{}
	for rows.Next() {
		var i GetFullProjectChurchLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFullProjectPersonLeaderboard = `-- name: GetFullProjectPersonLeaderboard :many
WITH ranked_scores AS (
    SELECT
        u.id AS entity_id,
        COALESCE(u.display_name, u.name) AS name,
        c.name AS church_name,
        u.avatar_url AS image,
        lpp.score,
        lpp.last_score_at,
        DENSE_RANK() OVER (ORDER BY lpp.score DESC) AS rank
    FROM leaderboard_project_persons lpp
    INNER JOIN users u ON lpp.user_id = u.id
    INNER JOIN churches c ON u.church_id = c.id
    WHERE lpp.project_id = $1::text
      AND lpp.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR lpp.score <= $3::int)
      AND ($4::text = '' OR u.church_id = $4::text)
      AND ($5::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) >= $5::int)
      AND ($6::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) <= $6::int)
      -- Team filtering
      AND ($7::text = '' OR EXISTS (
          SELECT 1 FROM team_members tm
          WHERE tm.user_id = u.id AND tm.team_id = $7::text
      ))
      AND ($8::text = '' OR EXISTS (
          SELECT 1 FROM team_members tm
          INNER JOIN teams t ON tm.team_id = t.id
          WHERE tm.user_id = u.id AND t.super_team_id = $8::text
      ))
      -- Consent filter: skip if team-filtered, otherwise require leaderboard_consent
      AND (
          $7::text != '' OR $8::text != ''
          OR EXISTS (
              SELECT 1 FROM user_consent_history uch
              WHERE uch.user_id = u.id
                AND uch.consent_key = 'leaderboard_consent'
                AND uch.action = 'ACCEPTED'
                AND uch.occurred_at = (
                    SELECT MAX(uch2.occurred_at)
                    FROM user_consent_history uch2
                    WHERE uch2.user_id = u.id
                      AND uch2.consent_key = 'leaderboard_consent'
                )
          )
      )
)
SELECT entity_id, name, church_name, image, score, rank, last_score_at
FROM ranked_scores
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
`

type GetFullProjectPersonLeaderboardParams struct {
	Projectid   string `json:"projectid"`
	Minscore    int32  `json:"minscore"`
	Maxscore    int32  `json:"maxscore"`
	Churchid    string `json:"churchid"`
	Minage      int32  `json:"minage"`
	Maxage      int32  `json:"maxage"`
	Teamid      string `json:"teamid"`
	Superteamid string `json:"superteamid"`
}

type GetFullProjectPersonLeaderboardRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	ChurchName  string             `json:"church_name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) GetFullProjectPersonLeaderboard(ctx context.Context, arg GetFullProjectPersonLeaderboardParams) ([]*GetFullProjectPersonLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetFullProjectPersonLeaderboard,
		arg.Projectid,
		arg.Minscore,
		arg.Maxscore,
		arg.Churchid,
		arg.Minage,
		arg.Maxage,
		arg.Teamid,
		arg.Superteamid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetFullProjectPersonLeaderboardRow{}
	for rows.Next() {
		var i GetFullProjectPersonLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.ChurchName,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFullProjectSuperTeamLeaderboard = `-- name: GetFullProjectSuperTeamLeaderboard :many
WITH ranked_scores AS (
    SELECT
        st.id AS entity_id,
        st.name,
        NULL::text AS image,
        lpst.score,
        lpst.last_score_at,
        DENSE_RANK() OVER (ORDER BY lpst.score DESC) AS rank
    FROM leaderboard_project_superteams lpst
    INNER JOIN super_teams st ON lpst.super_team_id = st.id
    WHERE lpst.project_id = $1::text
      AND lpst.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR lpst.score <= $3::int)
)
SELECT entity_id, name, image, score, rank, last_score_at
FROM ranked_scores
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
`

type GetFullProjectSuperTeamLeaderboardParams struct {
	Projectid string `json:"projectid"`
	Minscore  int32  `json:"minscore"`
	Maxscore  int32  `json:"maxscore"`
}

type GetFullProjectSuperTeamLeaderboardRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) GetFullProjectSuperTeamLeaderboard(ctx context.Context, arg GetFullProjectSuperTeamLeaderboardParams) ([]*GetFullProjectSuperTeamLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetFullProjectSuperTeamLeaderboard, arg.Projectid, arg.Minscore, arg.Maxscore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetFullProjectSuperTeamLeaderboardRow{}
	for rows.Next() {
		var i GetFullProjectSuperTeamLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFullProjectTeamLeaderboard = `-- name: GetFullProjectTeamLeaderboard :many
WITH ranked_scores AS (
    SELECT
        t.id AS entity_id,
        t.name,
        NULL::text AS image,
        lpt.score,
        lpt.last_score_at,
        DENSE_RANK() OVER (ORDER BY lpt.score DESC) AS rank
    FROM leaderboard_project_teams lpt
    INNER JOIN teams t ON lpt.team_id = t.id
    WHERE lpt.project_id = $1::text
      AND t.leaderboard_excluded = false
      AND lpt.score >= COALESCE($2::int, 1)
      AND ($3::int IS NULL OR lpt.score <= $3::int)
      -- Church filter: team has ANY member from specified church
      AND ($4::text = '' OR EXISTS (
          SELECT 1 FROM team_members tm
          INNER JOIN users u ON tm.user_id = u.id
          WHERE tm.team_id = t.id AND u.church_id = $4::text
      ))
)
SELECT entity_id, name, image, score, rank, last_score_at
FROM ranked_scores
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
`

type GetFullProjectTeamLeaderboardParams struct {
	Projectid string `json:"projectid"`
	Minscore  int32  `json:"minscore"`
	Maxscore  int32  `json:"maxscore"`
	Churchid  string `json:"churchid"`
}

type GetFullProjectTeamLeaderboardRow struct {
	EntityID    string             `json:"entity_id"`
	Name        string             `json:"name"`
	Image       *string            `json:"image"`
	Score       int64              `json:"score"`
	Rank        int64              `json:"rank"`
	LastScoreAt pgtype.Timestamptz `json:"last_score_at"`
}

func (q *Queries) GetFullProjectTeamLeaderboard(ctx context.Context, arg GetFullProjectTeamLeaderboardParams) ([]*GetFullProjectTeamLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetFullProjectTeamLeaderboard,
		arg.Projectid,
		arg.Minscore,
		arg.Maxscore,
		arg.Churchid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetFullProjectTeamLeaderboardRow{}
	for rows.Next() {
		var i GetFullProjectTeamLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetProjectChurchLeaderboard = `-- name: GetProjectChurchLeaderboard :many

WITH church_scores AS (
    SELECT
        c.id AS entity_id,
        c.name,
        NULL::text AS image,
        COALESCE(SUM(sj.points), 0)::bigint AS score,
        MAX(sj.created_at) AS last_score_at
    FROM churches c
    INNER JOIN users u ON c.id = u.church_id
    INNER JOIN user_projects up ON u.id = up.user_id
    LEFT JOIN score_journal sj ON sj.user_id = u.id AND sj.project_id = $6::text
    WHERE
        up.project_id = $6::text
        AND ($7::text = '' OR c.country = $7::text)
        AND ($8::text = '' OR c.category = $8::text)
    GROUP BY c.id, c.name
),
ranked_scores AS (
    SELECT
        entity_id,
        name,
        image,
        score,
        last_score_at,
        DENSE_RANK() OVER (ORDER BY score DESC) AS rank
    FROM church_scores
)
SELECT entity_id, name, image, score, rank, last_score_at
FROM ranked_scores
WHERE
    score >= 1
    AND ($1::int IS NULL OR score >= $1::int)
    AND ($2::int IS NULL OR score <= $2::int)
    AND ($3::bigint IS NULL OR rank > $3::bigint)
    AND ($4::bigint IS NULL OR rank < $4::bigint)
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
LIMIT $5::int
`

type GetProjectChurchLeaderboardParams struct {
	Minscore       int32  `json:"minscore"`
	Maxscore       int32  `json:"maxscore"`
	Afterrank      *int64 `json:"afterrank"`
	Beforerank     *int64 `json:"beforerank"`
	Querylimit     int32  `json:"querylimit"`
	Projectid      string `json:"projectid"`
	Country        string `json:"country"`
	Churchcategory string `json:"churchcategory"`
}

type GetProjectChurchLeaderboardRow struct {
	EntityID    string      `json:"entity_id"`
	Name        string      `json:"name"`
	Image       *string     `json:"image"`
	Score       int64       `json:"score"`
	Rank        int64       `json:"rank"`
	LastScoreAt interface{} `json:"last_score_at"`
}

// ==================== Project Church Leaderboard ====================
func (q *Queries) GetProjectChurchLeaderboard(ctx context.Context, arg GetProjectChurchLeaderboardParams) ([]*GetProjectChurchLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetProjectChurchLeaderboard,
		arg.Minscore,
		arg.Maxscore,
		arg.Afterrank,
		arg.Beforerank,
		arg.Querylimit,
		arg.Projectid,
		arg.Country,
		arg.Churchcategory,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetProjectChurchLeaderboardRow{}
	for rows.Next() {
		var i GetProjectChurchLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetProjectPersonLeaderboard = `-- name: GetProjectPersonLeaderboard :many

WITH project_users AS MATERIALIZED (
    -- Start with users in THIS project (huge performance win)
    -- MATERIALIZED forces execution order to avoid scanning all users
    SELECT DISTINCT
        u.id,
        COALESCE(u.display_name, u.name) AS name,
        u.avatar_url,
        u.birthdate,
        u.church_id,
        u.gender,
        c.name AS church_name
    FROM user_projects up
    INNER JOIN users u ON up.user_id = u.id
    INNER JOIN churches c ON u.church_id = c.id
    WHERE up.project_id = $6::text
      AND ($7::text = '' OR u.church_id = $7::text)
      AND ($8::text = '' OR u.gender = $8::text)
      AND ($9::text = '' OR EXISTS (
          SELECT 1 FROM team_members tm
          WHERE tm.user_id = u.id AND tm.team_id = $9::text
      ))
      AND ($10::text = '' OR EXISTS (
          SELECT 1 FROM team_members tm
          INNER JOIN teams t ON tm.team_id = t.id
          WHERE tm.user_id = u.id AND t.super_team_id = $10::text
      ))
),
filtered_users AS MATERIALIZED (
    -- Apply age and church filters
    SELECT pu.id, pu.name, pu.avatar_url, pu.church_name
    FROM project_users pu
    WHERE ($11::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM pu.birthdate)) >= $11::int)
      AND ($12::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM pu.birthdate)) <= $12::int)
      AND ($13::text = '' OR EXISTS (
          SELECT 1 FROM churches c
          WHERE c.id = pu.church_id AND c.country = $13::text
      ))
      AND ($14::text = '' OR EXISTS (
          SELECT 1 FROM churches c
          WHERE c.id = pu.church_id AND c.category = $14::text
      ))
),
person_scores AS (
    SELECT
        fu.id AS entity_id,
        fu.name,
        fu.church_name,
        fu.avatar_url AS image,
        COALESCE(SUM(sj.points), 0)::bigint AS score,
        MAX(sj.created_at) AS last_score_at
    FROM filtered_users fu
    LEFT JOIN score_journal sj ON sj.user_id = fu.id AND sj.project_id = $6::text
    GROUP BY fu.id, fu.name, fu.church_name, fu.avatar_url
    HAVING COALESCE(SUM(sj.points), 0) >= 1
),
ranked_scores AS (
    SELECT
        entity_id,
        name,
        church_name,
        image,
        score,
        last_score_at,
        DENSE_RANK() OVER (ORDER BY score DESC) AS rank
    FROM person_scores
)
SELECT entity_id, name, church_name, image, score, rank, last_score_at
FROM ranked_scores
WHERE
    ($1::int IS NULL OR score >= $1::int)
    AND ($2::int IS NULL OR score <= $2::int)
    AND ($3::bigint IS NULL OR rank > $3::bigint)
    AND ($4::bigint IS NULL OR rank < $4::bigint)
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
LIMIT $5::int
`

type GetProjectPersonLeaderboardParams struct {
	Minscore       int32  `json:"minscore"`
	Maxscore       int32  `json:"maxscore"`
	Afterrank      *int64 `json:"afterrank"`
	Beforerank     *int64 `json:"beforerank"`
	Querylimit     int32  `json:"querylimit"`
	Projectid      string `json:"projectid"`
	Churchid       string `json:"churchid"`
	Gender         string `json:"gender"`
	Teamid         string `json:"teamid"`
	Superteamid    string `json:"superteamid"`
	Minage         int32  `json:"minage"`
	Maxage         int32  `json:"maxage"`
	Country        string `json:"country"`
	Churchcategory string `json:"churchcategory"`
}

type GetProjectPersonLeaderboardRow struct {
	EntityID    string      `json:"entity_id"`
	Name        string      `json:"name"`
	ChurchName  string      `json:"church_name"`
	Image       *string     `json:"image"`
	Score       int64       `json:"score"`
	Rank        int64       `json:"rank"`
	LastScoreAt interface{} `json:"last_score_at"`
}

// ==================== Project Person Leaderboard ====================
func (q *Queries) GetProjectPersonLeaderboard(ctx context.Context, arg GetProjectPersonLeaderboardParams) ([]*GetProjectPersonLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetProjectPersonLeaderboard,
		arg.Minscore,
		arg.Maxscore,
		arg.Afterrank,
		arg.Beforerank,
		arg.Querylimit,
		arg.Projectid,
		arg.Churchid,
		arg.Gender,
		arg.Teamid,
		arg.Superteamid,
		arg.Minage,
		arg.Maxage,
		arg.Country,
		arg.Churchcategory,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetProjectPersonLeaderboardRow{}
	for rows.Next() {
		var i GetProjectPersonLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.ChurchName,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetProjectSuperTeamLeaderboard = `-- name: GetProjectSuperTeamLeaderboard :many

WITH superteam_scores AS (
    SELECT
        st.id AS entity_id,
        st.name,
        NULL::text AS image,
        COALESCE(SUM(sj.points), 0)::bigint AS score,
        MAX(sj.created_at) AS last_score_at
    FROM super_teams st
    INNER JOIN teams t ON t.super_team_id = st.id
    INNER JOIN team_members tm ON t.id = tm.team_id
    INNER JOIN users u ON tm.user_id = u.id
    LEFT JOIN score_journal sj ON sj.user_id = u.id AND sj.project_id = $6::text
    WHERE
        st.project_id = $6::text
    GROUP BY st.id, st.name
),
ranked_scores AS (
    SELECT
        entity_id,
        name,
        image,
        score,
        last_score_at,
        DENSE_RANK() OVER (ORDER BY score DESC) AS rank
    FROM superteam_scores
)
SELECT entity_id, name, image, score, rank, last_score_at
FROM ranked_scores
WHERE
    score >= 1
    AND ($1::int IS NULL OR score >= $1::int)
    AND ($2::int IS NULL OR score <= $2::int)
    AND ($3::bigint IS NULL OR rank > $3::bigint)
    AND ($4::bigint IS NULL OR rank < $4::bigint)
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
LIMIT $5::int
`

type GetProjectSuperTeamLeaderboardParams struct {
	Minscore   int32  `json:"minscore"`
	Maxscore   int32  `json:"maxscore"`
	Afterrank  *int64 `json:"afterrank"`
	Beforerank *int64 `json:"beforerank"`
	Querylimit int32  `json:"querylimit"`
	Projectid  string `json:"projectid"`
}

type GetProjectSuperTeamLeaderboardRow struct {
	EntityID    string      `json:"entity_id"`
	Name        string      `json:"name"`
	Image       *string     `json:"image"`
	Score       int64       `json:"score"`
	Rank        int64       `json:"rank"`
	LastScoreAt interface{} `json:"last_score_at"`
}

// ==================== Project SuperTeam Leaderboard ====================
func (q *Queries) GetProjectSuperTeamLeaderboard(ctx context.Context, arg GetProjectSuperTeamLeaderboardParams) ([]*GetProjectSuperTeamLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetProjectSuperTeamLeaderboard,
		arg.Minscore,
		arg.Maxscore,
		arg.Afterrank,
		arg.Beforerank,
		arg.Querylimit,
		arg.Projectid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetProjectSuperTeamLeaderboardRow{}
	for rows.Next() {
		var i GetProjectSuperTeamLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetProjectTeamLeaderboard = `-- name: GetProjectTeamLeaderboard :many

WITH team_scores AS (
    SELECT
        t.id AS entity_id,
        t.name,
        NULL::text AS image,
        COALESCE(SUM(sj.points), 0)::bigint AS score,
        MAX(sj.created_at) AS last_score_at
    FROM teams t
    INNER JOIN team_members tm ON t.id = tm.team_id
    INNER JOIN users u ON tm.user_id = u.id
    LEFT JOIN score_journal sj ON sj.user_id = u.id AND sj.project_id = $6::text
    WHERE
        t.project_id = $6::text
        AND t.leaderboard_excluded = false
        AND ($7::text = '' OR t.super_team_id = $7::text)
        -- Church filter: team has ANY member from specified church
        AND ($8::text = '' OR EXISTS (
            SELECT 1 FROM team_members tm2
            INNER JOIN users u2 ON tm2.user_id = u2.id
            WHERE tm2.team_id = t.id AND u2.church_id = $8::text
        ))
    GROUP BY t.id, t.name
),
ranked_scores AS (
    SELECT
        entity_id,
        name,
        image,
        score,
        last_score_at,
        DENSE_RANK() OVER (ORDER BY score DESC) AS rank
    FROM team_scores
)
SELECT entity_id, name, image, score, rank, last_score_at
FROM ranked_scores
WHERE
    score >= 1
    AND ($1::int IS NULL OR score >= $1::int)
    AND ($2::int IS NULL OR score <= $2::int)
    AND ($3::bigint IS NULL OR rank > $3::bigint)
    AND ($4::bigint IS NULL OR rank < $4::bigint)
ORDER BY rank ASC, last_score_at DESC NULLS LAST, name ASC
LIMIT $5::int
`

type GetProjectTeamLeaderboardParams struct {
	Minscore    int32  `json:"minscore"`
	Maxscore    int32  `json:"maxscore"`
	Afterrank   *int64 `json:"afterrank"`
	Beforerank  *int64 `json:"beforerank"`
	Querylimit  int32  `json:"querylimit"`
	Projectid   string `json:"projectid"`
	Superteamid string `json:"superteamid"`
	Churchid    string `json:"churchid"`
}

type GetProjectTeamLeaderboardRow struct {
	EntityID    string      `json:"entity_id"`
	Name        string      `json:"name"`
	Image       *string     `json:"image"`
	Score       int64       `json:"score"`
	Rank        int64       `json:"rank"`
	LastScoreAt interface{} `json:"last_score_at"`
}

// ==================== Project Team Leaderboard ====================
func (q *Queries) GetProjectTeamLeaderboard(ctx context.Context, arg GetProjectTeamLeaderboardParams) ([]*GetProjectTeamLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, GetProjectTeamLeaderboard,
		arg.Minscore,
		arg.Maxscore,
		arg.Afterrank,
		arg.Beforerank,
		arg.Querylimit,
		arg.Projectid,
		arg.Superteamid,
		arg.Churchid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetProjectTeamLeaderboardRow{}
	for rows.Next() {
		var i GetProjectTeamLeaderboardRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Image,
			&i.Score,
			&i.Rank,
			&i.LastScoreAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
