// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID                   string             `json:"id"`
	AchievementType      string             `json:"achievement_type"`
	ProjectID            string             `json:"project_id"`
	EventID              *string            `json:"event_id"`
	ChallengeID          *string            `json:"challenge_id"`
	Name                 string             `json:"name"`
	Points               int32              `json:"points"`
	Hidden               *bool              `json:"hidden"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DescriptionPending   string             `json:"description_pending"`
	DescriptionCompleted string             `json:"description_completed"`
	ImagePending         string             `json:"image_pending"`
	ImageCompleted       string             `json:"image_completed"`
	NotificationText     string             `json:"notification_text"`
	SortOrder            int32              `json:"sort_order"`
	// Earliest time the achievement can be awarded. NULL means always awardable.
	AwardableFrom pgtype.Timestamptz `json:"awardable_from"`
}

type AchievementTranslation struct {
	AchievementID        string             `json:"achievement_id"`
	LanguageCode         string             `json:"language_code"`
	Name                 *string            `json:"name"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DescriptionPending   *string            `json:"description_pending"`
	DescriptionCompleted *string            `json:"description_completed"`
	NotificationText     *string            `json:"notification_text"`
}

type Challenge struct {
	ID                          string             `json:"id"`
	ProjectID                   string             `json:"project_id"`
	EventID                     *string            `json:"event_id"`
	Name                        string             `json:"name"`
	Description                 string             `json:"description"`
	ImageUrl                    *string            `json:"image_url"`
	Url                         *string            `json:"url"`
	ButtonText                  string             `json:"button_text"`
	PublishedAt                 pgtype.Timestamptz `json:"published_at"`
	EndTime                     pgtype.Timestamptz `json:"end_time"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	VisibleAt                   pgtype.Timestamptz `json:"visible_at"`
	StartedAt                   pgtype.Timestamptz `json:"started_at"`
	RequiresTeamMembership      bool               `json:"requires_team_membership"`
	RequiresSuperTeamMembership bool               `json:"requires_super_team_membership"`
	ChallengeType               string             `json:"challenge_type"`
	AllowSelfCompletion         bool               `json:"allow_self_completion"`
}

type ChallengeTranslation struct {
	ChallengeID  string             `json:"challenge_id"`
	LanguageCode string             `json:"language_code"`
	Name         *string            `json:"name"`
	Description  *string            `json:"description"`
	ButtonText   *string            `json:"button_text"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Church struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Country    string             `json:"country"`
	Category   string             `json:"category"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ExternalID *int32             `json:"external_id"`
}

type Consent struct {
	ID          string             `json:"id"`
	Key         string             `json:"key"`
	Version     int32              `json:"version"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Url         *string            `json:"url"`
	ManagedBy   *string            `json:"managed_by"`
	IsRemote    bool               `json:"is_remote"`
	ShortText   string             `json:"short_text"`
}

type ConsentTranslation struct {
	ConsentID    string             `json:"consent_id"`
	LanguageCode string             `json:"language_code"`
	Title        *string            `json:"title"`
	Body         *string            `json:"body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ShortText    *string            `json:"short_text"`
}

type ContentAchievement struct {
	AchievementID string `json:"achievement_id"`
}

type ContentAchievementItem struct {
	ID                string `json:"id"`
	AchievementID     string `json:"achievement_id"`
	ExternalContentID string `json:"external_content_id"`
	SortOrder         int32  `json:"sort_order"`
}

type Event struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	EndDate     pgtype.Timestamptz `json:"end_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type EventTranslation struct {
	EventID      string             `json:"event_id"`
	LanguageCode string             `json:"language_code"`
	Name         *string            `json:"name"`
	Description  *string            `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Stores content items synced from external sources (SSF, etc.)
type ExternalContent struct {
	ID string `json:"id"`
	// External plan identifier
	PlanID string `json:"plan_id"`
	// External item ID (unique within plan)
	TaskID string `json:"task_id"`
	// Nested content ID (MediaEpisode, Song, BookChapter, etc.)
	ContentID *string `json:"content_id"`
	// Type of content: media_episode, song, book_chapter, periodical_article, bible_chapter, bible_verses
	ContentType string `json:"content_type"`
	// Content publication date
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	SyncedAt    pgtype.Timestamptz `json:"synced_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	// Content source identifier (e.g., ssf)
	Source string  `json:"source"`
	Url    *string `json:"url"`
	// Deadline for completing the content (calculated from completion_mode during SSF sync)
	CompleteBy pgtype.Timestamptz `json:"complete_by"`
}

// Stores content completion events from external systems
type ExternalContentEvent struct {
	ID string `json:"id"`
	// Brunstad TV person_id (UUID)
	PersonID pgtype.UUID `json:"person_id"`
	// External content identifier
	TaskID string `json:"task_id"`
	// External reading plan identifier (nullable)
	PlanID *string `json:"plan_id"`
	// API key identifier that submitted this event
	Source     string             `json:"source"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	// Content completion progress (0.01 to 1.1, where 1.0 = 100%)
	ContentProgress *float32           `json:"content_progress"`
	ConsumedAt      pgtype.Timestamptz `json:"consumed_at"`
}

type ExternalContentTranslation struct {
	ExternalContentID string             `json:"external_content_id"`
	LanguageCode      string             `json:"language_code"`
	Title             *string            `json:"title"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Stores metadata for files uploaded to S3 via /api/upload endpoint
type FileUpload struct {
	ID string `json:"id"`
	// Original filename as uploaded by user
	Filename string `json:"filename"`
	// ULID-based filename stored in S3
	StoredFilename string `json:"stored_filename"`
	// File size in bytes
	FileSize int32 `json:"file_size"`
	// MIME type detected from file header
	MimeType string `json:"mime_type"`
	// Full public URL to access the file
	PublicUrl string `json:"public_url"`
	// User ID of admin who uploaded the file
	UploadedBy string             `json:"uploaded_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	// Image width in pixels (null for non-images)
	Width *int32 `json:"width"`
	// Image height in pixels (null for non-images)
	Height *int32 `json:"height"`
	// Blurhash placeholder string (null for non-images)
	Blurhash *string `json:"blurhash"`
}

type LeaderboardEventChurch struct {
	EventID   string             `json:"event_id"`
	ChurchID  string             `json:"church_id"`
	Score     int64              `json:"score"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LeaderboardEventPerson struct {
	EventID   string             `json:"event_id"`
	UserID    string             `json:"user_id"`
	Score     int64              `json:"score"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LeaderboardEventSuperteam struct {
	EventID     string             `json:"event_id"`
	SuperTeamID string             `json:"super_team_id"`
	Score       int64              `json:"score"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type LeaderboardEventTeam struct {
	EventID   string             `json:"event_id"`
	TeamID    string             `json:"team_id"`
	Score     int64              `json:"score"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LeaderboardProjectChurch struct {
	ProjectID string             `json:"project_id"`
	ChurchID  string             `json:"church_id"`
	Score     int64              `json:"score"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LeaderboardProjectPerson struct {
	ProjectID string             `json:"project_id"`
	UserID    string             `json:"user_id"`
	Score     int64              `json:"score"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LeaderboardProjectSuperteam struct {
	ProjectID   string             `json:"project_id"`
	SuperTeamID string             `json:"super_team_id"`
	Score       int64              `json:"score"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type LeaderboardProjectTeam struct {
	ProjectID string             `json:"project_id"`
	TeamID    string             `json:"team_id"`
	Score     int64              `json:"score"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Stores consent events for users not yet registered in Wayfarer
type PendingConsentEvent struct {
	ID string `json:"id"`
	// BCC Members person_id (UUID) of the user
	MembersID string `json:"members_id"`
	// Key identifying the consent type
	ConsentKey string `json:"consent_key"`
	// ACCEPTED or REJECTED
	Action string `json:"action"`
	// When the consent action occurred (from external system)
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	// API key source that submitted this event
	Source    *string            `json:"source"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PhraseAsyncJob struct {
	AsyncRequestID string             `json:"async_request_id"`
	JobUid         string             `json:"job_uid"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID                          string             `json:"id"`
	Name                        string             `json:"name"`
	Description                 string             `json:"description"`
	StartDate                   pgtype.Timestamptz `json:"start_date"`
	EndDate                     pgtype.Timestamptz `json:"end_date"`
	LogoUrl                     *string            `json:"logo_url"`
	Archived                    *bool              `json:"archived"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	Rounding                    int32              `json:"rounding"`
	ColorLightAccent            string             `json:"color_light_accent"`
	ColorLightAccentContrast    string             `json:"color_light_accent_contrast"`
	ColorLightOnAccent          string             `json:"color_light_on_accent"`
	ColorLightBackgroundDefault string             `json:"color_light_background_default"`
	ColorLightBackgroundRaised  string             `json:"color_light_background_raised"`
	ColorLightBackgroundIndent  string             `json:"color_light_background_indent"`
	ColorLightTextDefault       string             `json:"color_light_text_default"`
	ColorLightTextMuted         string             `json:"color_light_text_muted"`
	ColorLightTextHint          string             `json:"color_light_text_hint"`
	ColorLightShadowDefault     string             `json:"color_light_shadow_default"`
	ColorLightShadowBlank       string             `json:"color_light_shadow_blank"`
	ColorLightBorderDefault     string             `json:"color_light_border_default"`
	ColorDarkAccent             string             `json:"color_dark_accent"`
	ColorDarkAccentContrast     string             `json:"color_dark_accent_contrast"`
	ColorDarkOnAccent           string             `json:"color_dark_on_accent"`
	ColorDarkBackgroundDefault  string             `json:"color_dark_background_default"`
	ColorDarkBackgroundRaised   string             `json:"color_dark_background_raised"`
	ColorDarkBackgroundIndent   string             `json:"color_dark_background_indent"`
	ColorDarkTextDefault        string             `json:"color_dark_text_default"`
	ColorDarkTextMuted          string             `json:"color_dark_text_muted"`
	ColorDarkTextHint           string             `json:"color_dark_text_hint"`
	ColorDarkShadowDefault      string             `json:"color_dark_shadow_default"`
	ColorDarkShadowBlank        string             `json:"color_dark_shadow_blank"`
	ColorDarkBorderDefault      string             `json:"color_dark_border_default"`
	Rules                       *string            `json:"rules"`
	BannerUrl                   *string            `json:"banner_url"`
}

type ProjectTranslation struct {
	ProjectID    string             `json:"project_id"`
	LanguageCode string             `json:"language_code"`
	Name         *string            `json:"name"`
	Description  *string            `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Rules        *string            `json:"rules"`
}

type PushNotificationLog struct {
	ID                   string             `json:"id"`
	NotificationType     string             `json:"notification_type"`
	Title                string             `json:"title"`
	Body                 string             `json:"body"`
	Url                  *string            `json:"url"`
	Data                 []byte             `json:"data"`
	TargetCriteria       []byte             `json:"target_criteria"`
	SentBy               *string            `json:"sent_by"`
	SentAt               pgtype.Timestamptz `json:"sent_at"`
	TotalRecipients      int32              `json:"total_recipients"`
	SuccessfulDeliveries int32              `json:"successful_deliveries"`
	FailedDeliveries     int32              `json:"failed_deliveries"`
}

type PushNotificationPreference struct {
	UserID           string             `json:"user_id"`
	NotificationType string             `json:"notification_type"`
	Enabled          bool               `json:"enabled"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PushSubscription struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Endpoint  string             `json:"endpoint"`
	P256dhKey string             `json:"p256dh_key"`
	AuthKey   string             `json:"auth_key"`
	UserAgent *string            `json:"user_agent"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Quiz struct {
	ID                   string             `json:"id"`
	ProjectID            string             `json:"project_id"`
	Name                 string             `json:"name"`
	Description          string             `json:"description"`
	ImageUrl             *string            `json:"image_url"`
	TimeoutSeconds       *int32             `json:"timeout_seconds"`
	RandomizeQuestions   bool               `json:"randomize_questions"`
	RevealCorrectAnswers bool               `json:"reveal_correct_answers"`
	AllowRetakes         bool               `json:"allow_retakes"`
	CompletionPoints     int32              `json:"completion_points"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	EndTime              pgtype.Timestamptz `json:"end_time"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ChallengeID          string             `json:"challenge_id"`
}

type QuizAchievement struct {
	AchievementID      string `json:"achievement_id"`
	QuizID             string `json:"quiz_id"`
	MinScorePercentage *int32 `json:"min_score_percentage"`
	RequireCompletion  bool   `json:"require_completion"`
}

type QuizAnswerTranslation struct {
	AnswerID     string             `json:"answer_id"`
	LanguageCode string             `json:"language_code"`
	AnswerText   *string            `json:"answer_text"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type QuizPredefinedAnswer struct {
	ID          string             `json:"id"`
	QuestionID  string             `json:"question_id"`
	AnswerText  string             `json:"answer_text"`
	IsCorrect   bool               `json:"is_correct"`
	AnswerOrder int32              `json:"answer_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type QuizQuestion struct {
	ID                     string             `json:"id"`
	QuizID                 string             `json:"quiz_id"`
	QuestionType           string             `json:"question_type"`
	QuestionText           string             `json:"question_text"`
	QuestionOrder          int32              `json:"question_order"`
	AllowMultipleSelection *bool              `json:"allow_multiple_selection"`
	MinValue               pgtype.Numeric     `json:"min_value"`
	MaxValue               pgtype.Numeric     `json:"max_value"`
	StepValue              pgtype.Numeric     `json:"step_value"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	TimeoutSeconds         *int32             `json:"timeout_seconds"`
	Points                 *int32             `json:"points"`
}

type QuizQuestionTranslation struct {
	QuestionID   string             `json:"question_id"`
	LanguageCode string             `json:"language_code"`
	QuestionText *string            `json:"question_text"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type QuizResponse struct {
	ID                string             `json:"id"`
	SubmissionID      string             `json:"submission_id"`
	QuestionID        string             `json:"question_id"`
	SelectedAnswerIds []byte             `json:"selected_answer_ids"`
	TextResponse      *string            `json:"text_response"`
	NumberResponse    pgtype.Numeric     `json:"number_response"`
	JsonResponse      []byte             `json:"json_response"`
	IsCorrect         *bool              `json:"is_correct"`
	AnsweredAt        pgtype.Timestamptz `json:"answered_at"`
	TimeSpentSeconds  *int32             `json:"time_spent_seconds"`
	PointsEarned      *int32             `json:"points_earned"`
}

type QuizSubmission struct {
	ID            string             `json:"id"`
	QuizID        string             `json:"quiz_id"`
	UserID        string             `json:"user_id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	QuestionOrder []byte             `json:"question_order"`
	Score         *int32             `json:"score"`
	MaxScore      *int32             `json:"max_score"`
	PointsAwarded *int32             `json:"points_awarded"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type QuizTranslation struct {
	QuizID       string             `json:"quiz_id"`
	LanguageCode string             `json:"language_code"`
	Name         *string            `json:"name"`
	Description  *string            `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ScoreJournal struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	UserID      string             `json:"user_id"`
	EventID     *string            `json:"event_id"`
	ChallengeID *string            `json:"challenge_id"`
	Points      int32              `json:"points"`
	SourceType  string             `json:"source_type"`
	SourceID    *string            `json:"source_id"`
	Reason      *string            `json:"reason"`
	AwardedBy   *string            `json:"awarded_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Runtime configuration key-value store
type Setting struct {
	// Unique setting identifier (e.g., current_project_id, log_level)
	Key        string   `json:"key"`
	ValueText  *string  `json:"value_text"`
	ValueInt   *int64   `json:"value_int"`
	ValueBool  *bool    `json:"value_bool"`
	ValueFloat *float64 `json:"value_float"`
	ValueJson  []byte   `json:"value_json"`
	// Indicates which value column to use: text, int, bool, float, or json
	ValueType string `json:"value_type"`
	// Human-readable description of the setting
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Streak struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type StreakAchievement struct {
	AchievementID string `json:"achievement_id"`
	StreakID      string `json:"streak_id"`
	NeededStreak  int32  `json:"needed_streak"`
}

type StreakRelevantDay struct {
	ID        string      `json:"id"`
	StreakID  string      `json:"streak_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type StreakTranslation struct {
	StreakID     string             `json:"streak_id"`
	LanguageCode string             `json:"language_code"`
	Name         *string            `json:"name"`
	Description  *string            `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SuperTeam struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SuperTeamTranslation struct {
	SuperTeamID  string             `json:"super_team_id"`
	LanguageCode string             `json:"language_code"`
	Name         *string            `json:"name"`
	Description  *string            `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Team struct {
	ID                  string             `json:"id"`
	ProjectID           string             `json:"project_id"`
	Name                string             `json:"name"`
	Description         *string            `json:"description"`
	JoinCode            string             `json:"join_code"`
	SuperTeamID         *string            `json:"super_team_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LeaderboardExcluded bool               `json:"leaderboard_excluded"`
}

type TeamMember struct {
	TeamID   string             `json:"team_id"`
	UserID   string             `json:"user_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type TeamTranslation struct {
	TeamID       string             `json:"team_id"`
	LanguageCode string             `json:"language_code"`
	Name         *string            `json:"name"`
	Description  *string            `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TranslationHash struct {
	Collection string             `json:"collection"`
	Hash       []byte             `json:"hash"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          string             `json:"id"`
	MembersID   string             `json:"members_id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	Gender      string             `json:"gender"`
	ChurchID    string             `json:"church_id"`
	AvatarUrl   *string            `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Birthdate   pgtype.Date        `json:"birthdate"`
	FirstName   *string            `json:"first_name"`
	LastName    *string            `json:"last_name"`
	MiddleName  *string            `json:"middle_name"`
	DisplayName *string            `json:"display_name"`
	PersonUuid  pgtype.UUID        `json:"person_uuid"`
	Language    string             `json:"language"`
}

type UserAchievement struct {
	UserID        string             `json:"user_id"`
	AchievementID string             `json:"achievement_id"`
	AchievedAt    pgtype.Timestamptz `json:"achieved_at"`
}

type UserChallengeCompletion struct {
	UserID      string             `json:"user_id"`
	ChallengeID string             `json:"challenge_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type UserChallengeEnrollment struct {
	UserID      string             `json:"user_id"`
	ChallengeID string             `json:"challenge_id"`
	EnrolledAt  pgtype.Timestamptz `json:"enrolled_at"`
}

type UserConsentHistory struct {
	ID                string             `json:"id"`
	UserID            string             `json:"user_id"`
	ConsentID         string             `json:"consent_id"`
	Action            string             `json:"action"`
	ConsentKey        string             `json:"consent_key"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	Source            *string            `json:"source"`
	ExternalConsentID *string            `json:"external_consent_id"`
	ExternalTimestamp pgtype.Timestamptz `json:"external_timestamp"`
}

type UserContentProgress struct {
	UserID            string             `json:"user_id"`
	AchievementID     string             `json:"achievement_id"`
	ExternalContentID string             `json:"external_content_id"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

type UserEvent struct {
	UserID   string             `json:"user_id"`
	EventID  string             `json:"event_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type UserFeedback struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	Message      string             `json:"message"`
	CanContactMe bool               `json:"can_contact_me"`
	UserAgent    *string            `json:"user_agent"`
	Platform     *string            `json:"platform"`
	ScreenWidth  *int32             `json:"screen_width"`
	ScreenHeight *int32             `json:"screen_height"`
	AppVersion   *string            `json:"app_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Locale       *string            `json:"locale"`
	ProjectID    *string            `json:"project_id"`
	Timezone     *string            `json:"timezone"`
	HandledAt    pgtype.Timestamptz `json:"handled_at"`
}

type UserProject struct {
	UserID    string             `json:"user_id"`
	ProjectID string             `json:"project_id"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

type UserRole struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Role       string             `json:"role"`
	ChurchID   *string            `json:"church_id"`
	ProjectID  *string            `json:"project_id"`
	TeamID     *string            `json:"team_id"`
	AssignedBy string             `json:"assigned_by"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type UserStreakActivity struct {
	UserID       string             `json:"user_id"`
	StreakID     string             `json:"streak_id"`
	ActivityDate pgtype.Date        `json:"activity_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Webhook struct {
	ID               string             `json:"id"`
	ProjectID        string             `json:"project_id"`
	Name             string             `json:"name"`
	Url              string             `json:"url"`
	EventType        string             `json:"event_type"`
	IncludeUserData  bool               `json:"include_user_data"`
	IncludeEventData bool               `json:"include_event_data"`
	Active           bool               `json:"active"`
	Secret           *string            `json:"secret"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type WebhookLog struct {
	ID                 string             `json:"id"`
	WebhookID          string             `json:"webhook_id"`
	EventType          string             `json:"event_type"`
	RequestPayload     []byte             `json:"request_payload"`
	ResponseStatusCode *int32             `json:"response_status_code"`
	ResponseBody       *string            `json:"response_body"`
	DurationMs         int32              `json:"duration_ms"`
	ErrorMessage       *string            `json:"error_message"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
