// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quiz_responses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CalculateSubmissionPointsFromResponses = `-- name: CalculateSubmissionPointsFromResponses :one
SELECT COALESCE(SUM(points_earned), 0)::int AS total_points
FROM quiz_responses
WHERE submission_id = $1::text
`

func (q *Queries) CalculateSubmissionPointsFromResponses(ctx context.Context, submissionid string) (int32, error) {
	row := q.db.QueryRow(ctx, CalculateSubmissionPointsFromResponses, submissionid)
	var total_points int32
	err := row.Scan(&total_points)
	return total_points, err
}

const CalculateSubmissionScore = `-- name: CalculateSubmissionScore :one
SELECT
    COUNT(*) FILTER (WHERE is_correct = true) AS score,
    COUNT(*) FILTER (WHERE is_correct IS NOT NULL) AS max_score
FROM quiz_responses
WHERE submission_id = $1::text
`

type CalculateSubmissionScoreRow struct {
	Score    int64 `json:"score"`
	MaxScore int64 `json:"max_score"`
}

func (q *Queries) CalculateSubmissionScore(ctx context.Context, submissionid string) (*CalculateSubmissionScoreRow, error) {
	row := q.db.QueryRow(ctx, CalculateSubmissionScore, submissionid)
	var i CalculateSubmissionScoreRow
	err := row.Scan(&i.Score, &i.MaxScore)
	return &i, err
}

const CreateQuizResponse = `-- name: CreateQuizResponse :one
INSERT INTO quiz_responses (
    id,
    submission_id,
    question_id,
    selected_answer_ids,
    text_response,
    number_response,
    json_response,
    is_correct,
    points_earned,
    time_spent_seconds
)
VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::jsonb,
    $5::text,
    $6::decimal,
    $7::jsonb,
    $8::bool,
    $9::int,
    $10::int
)
RETURNING id, submission_id, question_id, selected_answer_ids, text_response, number_response, json_response, is_correct, points_earned, answered_at, time_spent_seconds
`

type CreateQuizResponseParams struct {
	ID                string         `json:"id"`
	Submissionid      string         `json:"submissionid"`
	Questionid        string         `json:"questionid"`
	Selectedanswerids []byte         `json:"selectedanswerids"`
	Textresponse      *string        `json:"textresponse"`
	Numberresponse    pgtype.Numeric `json:"numberresponse"`
	Jsonresponse      []byte         `json:"jsonresponse"`
	Iscorrect         *bool          `json:"iscorrect"`
	Pointsearned      *int32         `json:"pointsearned"`
	Timespentseconds  *int32         `json:"timespentseconds"`
}

type CreateQuizResponseRow struct {
	ID                string             `json:"id"`
	SubmissionID      string             `json:"submission_id"`
	QuestionID        string             `json:"question_id"`
	SelectedAnswerIds []byte             `json:"selected_answer_ids"`
	TextResponse      *string            `json:"text_response"`
	NumberResponse    pgtype.Numeric     `json:"number_response"`
	JsonResponse      []byte             `json:"json_response"`
	IsCorrect         *bool              `json:"is_correct"`
	PointsEarned      *int32             `json:"points_earned"`
	AnsweredAt        pgtype.Timestamptz `json:"answered_at"`
	TimeSpentSeconds  *int32             `json:"time_spent_seconds"`
}

func (q *Queries) CreateQuizResponse(ctx context.Context, arg CreateQuizResponseParams) (*CreateQuizResponseRow, error) {
	row := q.db.QueryRow(ctx, CreateQuizResponse,
		arg.ID,
		arg.Submissionid,
		arg.Questionid,
		arg.Selectedanswerids,
		arg.Textresponse,
		arg.Numberresponse,
		arg.Jsonresponse,
		arg.Iscorrect,
		arg.Pointsearned,
		arg.Timespentseconds,
	)
	var i CreateQuizResponseRow
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.QuestionID,
		&i.SelectedAnswerIds,
		&i.TextResponse,
		&i.NumberResponse,
		&i.JsonResponse,
		&i.IsCorrect,
		&i.PointsEarned,
		&i.AnsweredAt,
		&i.TimeSpentSeconds,
	)
	return &i, err
}

const GetQuizResponseBySubmissionAndQuestion = `-- name: GetQuizResponseBySubmissionAndQuestion :one
SELECT id, submission_id, question_id, selected_answer_ids, text_response, number_response, json_response, is_correct, points_earned, answered_at, time_spent_seconds
FROM quiz_responses
WHERE submission_id = $1::text
    AND question_id = $2::text
`

type GetQuizResponseBySubmissionAndQuestionParams struct {
	Submissionid string `json:"submissionid"`
	Questionid   string `json:"questionid"`
}

type GetQuizResponseBySubmissionAndQuestionRow struct {
	ID                string             `json:"id"`
	SubmissionID      string             `json:"submission_id"`
	QuestionID        string             `json:"question_id"`
	SelectedAnswerIds []byte             `json:"selected_answer_ids"`
	TextResponse      *string            `json:"text_response"`
	NumberResponse    pgtype.Numeric     `json:"number_response"`
	JsonResponse      []byte             `json:"json_response"`
	IsCorrect         *bool              `json:"is_correct"`
	PointsEarned      *int32             `json:"points_earned"`
	AnsweredAt        pgtype.Timestamptz `json:"answered_at"`
	TimeSpentSeconds  *int32             `json:"time_spent_seconds"`
}

func (q *Queries) GetQuizResponseBySubmissionAndQuestion(ctx context.Context, arg GetQuizResponseBySubmissionAndQuestionParams) (*GetQuizResponseBySubmissionAndQuestionRow, error) {
	row := q.db.QueryRow(ctx, GetQuizResponseBySubmissionAndQuestion, arg.Submissionid, arg.Questionid)
	var i GetQuizResponseBySubmissionAndQuestionRow
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.QuestionID,
		&i.SelectedAnswerIds,
		&i.TextResponse,
		&i.NumberResponse,
		&i.JsonResponse,
		&i.IsCorrect,
		&i.PointsEarned,
		&i.AnsweredAt,
		&i.TimeSpentSeconds,
	)
	return &i, err
}

const GetQuizResponsesBySubmissionID = `-- name: GetQuizResponsesBySubmissionID :many
SELECT id, submission_id, question_id, selected_answer_ids, text_response, number_response, json_response, is_correct, points_earned, answered_at, time_spent_seconds
FROM quiz_responses
WHERE submission_id = $1::text
`

type GetQuizResponsesBySubmissionIDRow struct {
	ID                string             `json:"id"`
	SubmissionID      string             `json:"submission_id"`
	QuestionID        string             `json:"question_id"`
	SelectedAnswerIds []byte             `json:"selected_answer_ids"`
	TextResponse      *string            `json:"text_response"`
	NumberResponse    pgtype.Numeric     `json:"number_response"`
	JsonResponse      []byte             `json:"json_response"`
	IsCorrect         *bool              `json:"is_correct"`
	PointsEarned      *int32             `json:"points_earned"`
	AnsweredAt        pgtype.Timestamptz `json:"answered_at"`
	TimeSpentSeconds  *int32             `json:"time_spent_seconds"`
}

func (q *Queries) GetQuizResponsesBySubmissionID(ctx context.Context, submissionid string) ([]*GetQuizResponsesBySubmissionIDRow, error) {
	rows, err := q.db.Query(ctx, GetQuizResponsesBySubmissionID, submissionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetQuizResponsesBySubmissionIDRow{}
	for rows.Next() {
		var i GetQuizResponsesBySubmissionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.QuestionID,
			&i.SelectedAnswerIds,
			&i.TextResponse,
			&i.NumberResponse,
			&i.JsonResponse,
			&i.IsCorrect,
			&i.PointsEarned,
			&i.AnsweredAt,
			&i.TimeSpentSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetQuizResponsesBySubmissionIDs = `-- name: GetQuizResponsesBySubmissionIDs :many
SELECT
    r.id, r.submission_id, r.question_id, r.selected_answer_ids,
    r.text_response, r.number_response, r.json_response,
    r.is_correct, r.points_earned, r.answered_at, r.time_spent_seconds,
    q.question_type
FROM quiz_responses r
JOIN quiz_questions q ON r.question_id = q.id
WHERE r.submission_id = ANY($1::text[])
ORDER BY r.submission_id
`

type GetQuizResponsesBySubmissionIDsRow struct {
	ID                string             `json:"id"`
	SubmissionID      string             `json:"submission_id"`
	QuestionID        string             `json:"question_id"`
	SelectedAnswerIds []byte             `json:"selected_answer_ids"`
	TextResponse      *string            `json:"text_response"`
	NumberResponse    pgtype.Numeric     `json:"number_response"`
	JsonResponse      []byte             `json:"json_response"`
	IsCorrect         *bool              `json:"is_correct"`
	PointsEarned      *int32             `json:"points_earned"`
	AnsweredAt        pgtype.Timestamptz `json:"answered_at"`
	TimeSpentSeconds  *int32             `json:"time_spent_seconds"`
	QuestionType      string             `json:"question_type"`
}

func (q *Queries) GetQuizResponsesBySubmissionIDs(ctx context.Context, submissionIds []string) ([]*GetQuizResponsesBySubmissionIDsRow, error) {
	rows, err := q.db.Query(ctx, GetQuizResponsesBySubmissionIDs, submissionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetQuizResponsesBySubmissionIDsRow{}
	for rows.Next() {
		var i GetQuizResponsesBySubmissionIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.QuestionID,
			&i.SelectedAnswerIds,
			&i.TextResponse,
			&i.NumberResponse,
			&i.JsonResponse,
			&i.IsCorrect,
			&i.PointsEarned,
			&i.AnsweredAt,
			&i.TimeSpentSeconds,
			&i.QuestionType,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateQuizResponse = `-- name: UpdateQuizResponse :one
UPDATE quiz_responses
SET
    selected_answer_ids = COALESCE($1::jsonb, selected_answer_ids),
    text_response = COALESCE($2::text, text_response),
    number_response = COALESCE($3::decimal, number_response),
    json_response = COALESCE($4::jsonb, json_response),
    is_correct = COALESCE($5::bool, is_correct),
    points_earned = COALESCE($6::int, points_earned),
    time_spent_seconds = COALESCE($7::int, time_spent_seconds),
    answered_at = now()
WHERE id = $8::text
RETURNING id, submission_id, question_id, selected_answer_ids, text_response, number_response, json_response, is_correct, points_earned, answered_at, time_spent_seconds
`

type UpdateQuizResponseParams struct {
	Selectedanswerids []byte         `json:"selectedanswerids"`
	Textresponse      *string        `json:"textresponse"`
	Numberresponse    pgtype.Numeric `json:"numberresponse"`
	Jsonresponse      []byte         `json:"jsonresponse"`
	Iscorrect         *bool          `json:"iscorrect"`
	Pointsearned      *int32         `json:"pointsearned"`
	Timespentseconds  *int32         `json:"timespentseconds"`
	ID                string         `json:"id"`
}

type UpdateQuizResponseRow struct {
	ID                string             `json:"id"`
	SubmissionID      string             `json:"submission_id"`
	QuestionID        string             `json:"question_id"`
	SelectedAnswerIds []byte             `json:"selected_answer_ids"`
	TextResponse      *string            `json:"text_response"`
	NumberResponse    pgtype.Numeric     `json:"number_response"`
	JsonResponse      []byte             `json:"json_response"`
	IsCorrect         *bool              `json:"is_correct"`
	PointsEarned      *int32             `json:"points_earned"`
	AnsweredAt        pgtype.Timestamptz `json:"answered_at"`
	TimeSpentSeconds  *int32             `json:"time_spent_seconds"`
}

func (q *Queries) UpdateQuizResponse(ctx context.Context, arg UpdateQuizResponseParams) (*UpdateQuizResponseRow, error) {
	row := q.db.QueryRow(ctx, UpdateQuizResponse,
		arg.Selectedanswerids,
		arg.Textresponse,
		arg.Numberresponse,
		arg.Jsonresponse,
		arg.Iscorrect,
		arg.Pointsearned,
		arg.Timespentseconds,
		arg.ID,
	)
	var i UpdateQuizResponseRow
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.QuestionID,
		&i.SelectedAnswerIds,
		&i.TextResponse,
		&i.NumberResponse,
		&i.JsonResponse,
		&i.IsCorrect,
		&i.PointsEarned,
		&i.AnsweredAt,
		&i.TimeSpentSeconds,
	)
	return &i, err
}
