// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: quizzes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountQuizzesFiltered = `-- name: CountQuizzesFiltered :one
SELECT COUNT(DISTINCT id)
FROM quizzes
WHERE
    ($1::text[] IS NULL OR id = ANY($1::text[]))
    AND ($2::text = '' OR project_id = $2::text)
    AND ($3::text = '' OR challenge_id = $3::text)
    AND ($4::timestamptz IS NULL OR published_at >= $4::timestamptz)
    AND ($5::timestamptz IS NULL OR published_at <= $5::timestamptz)
`

type CountQuizzesFilteredParams struct {
	Ids             []string           `json:"ids"`
	Projectid       string             `json:"projectid"`
	Challengeid     string             `json:"challengeid"`
	Publishedafter  pgtype.Timestamptz `json:"publishedafter"`
	Publishedbefore pgtype.Timestamptz `json:"publishedbefore"`
}

func (q *Queries) CountQuizzesFiltered(ctx context.Context, arg CountQuizzesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountQuizzesFiltered,
		arg.Ids,
		arg.Projectid,
		arg.Challengeid,
		arg.Publishedafter,
		arg.Publishedbefore,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (
    id,
    project_id,
    challenge_id,
    name,
    description,
    image_url,
    timeout_seconds,
    question_timeout_seconds,
    randomize_questions,
    reveal_correct_answers,
    allow_retakes,
    completion_points,
    published_at,
    end_time
)
VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::text,
    $7::int,
    $8::int,
    $9::bool,
    $10::bool,
    $11::bool,
    $12::int,
    $13::timestamptz,
    $14::timestamptz
)
RETURNING id, project_id, challenge_id, name, description, image_url, timeout_seconds, question_timeout_seconds, randomize_questions, reveal_correct_answers, allow_retakes, completion_points, published_at, end_time, created_at, updated_at
`

type CreateQuizParams struct {
	ID                     string             `json:"id"`
	Projectid              string             `json:"projectid"`
	Challengeid            string             `json:"challengeid"`
	Name                   string             `json:"name"`
	Description            string             `json:"description"`
	Imageurl               *string            `json:"imageurl"`
	Timeoutseconds         *int32             `json:"timeoutseconds"`
	Questiontimeoutseconds *int32             `json:"questiontimeoutseconds"`
	Randomizequestions     bool               `json:"randomizequestions"`
	Revealcorrectanswers   bool               `json:"revealcorrectanswers"`
	Allowretakes           bool               `json:"allowretakes"`
	Completionpoints       int32              `json:"completionpoints"`
	Publishedat            pgtype.Timestamptz `json:"publishedat"`
	Endtime                pgtype.Timestamptz `json:"endtime"`
}

type CreateQuizRow struct {
	ID                     string             `json:"id"`
	ProjectID              string             `json:"project_id"`
	ChallengeID            string             `json:"challenge_id"`
	Name                   string             `json:"name"`
	Description            string             `json:"description"`
	ImageUrl               *string            `json:"image_url"`
	TimeoutSeconds         *int32             `json:"timeout_seconds"`
	QuestionTimeoutSeconds *int32             `json:"question_timeout_seconds"`
	RandomizeQuestions     bool               `json:"randomize_questions"`
	RevealCorrectAnswers   bool               `json:"reveal_correct_answers"`
	AllowRetakes           bool               `json:"allow_retakes"`
	CompletionPoints       int32              `json:"completion_points"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (*CreateQuizRow, error) {
	row := q.db.QueryRow(ctx, CreateQuiz,
		arg.ID,
		arg.Projectid,
		arg.Challengeid,
		arg.Name,
		arg.Description,
		arg.Imageurl,
		arg.Timeoutseconds,
		arg.Questiontimeoutseconds,
		arg.Randomizequestions,
		arg.Revealcorrectanswers,
		arg.Allowretakes,
		arg.Completionpoints,
		arg.Publishedat,
		arg.Endtime,
	)
	var i CreateQuizRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChallengeID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.TimeoutSeconds,
		&i.QuestionTimeoutSeconds,
		&i.RandomizeQuestions,
		&i.RevealCorrectAnswers,
		&i.AllowRetakes,
		&i.CompletionPoints,
		&i.PublishedAt,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeleteQuiz = `-- name: DeleteQuiz :exec
DELETE FROM quizzes
WHERE id = $1::text
`

func (q *Queries) DeleteQuiz(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, DeleteQuiz, id)
	return err
}

const DeleteQuizTranslations = `-- name: DeleteQuizTranslations :exec
DELETE FROM quiz_translations
WHERE quiz_id = $1::text
`

func (q *Queries) DeleteQuizTranslations(ctx context.Context, quizid string) error {
	_, err := q.db.Exec(ctx, DeleteQuizTranslations, quizid)
	return err
}

const GetQuizByID = `-- name: GetQuizByID :one
SELECT id, project_id, challenge_id, name, description, image_url, timeout_seconds, question_timeout_seconds, randomize_questions, reveal_correct_answers, allow_retakes, completion_points, published_at, end_time, created_at, updated_at
FROM quizzes
WHERE id = $1::text
`

type GetQuizByIDRow struct {
	ID                     string             `json:"id"`
	ProjectID              string             `json:"project_id"`
	ChallengeID            string             `json:"challenge_id"`
	Name                   string             `json:"name"`
	Description            string             `json:"description"`
	ImageUrl               *string            `json:"image_url"`
	TimeoutSeconds         *int32             `json:"timeout_seconds"`
	QuestionTimeoutSeconds *int32             `json:"question_timeout_seconds"`
	RandomizeQuestions     bool               `json:"randomize_questions"`
	RevealCorrectAnswers   bool               `json:"reveal_correct_answers"`
	AllowRetakes           bool               `json:"allow_retakes"`
	CompletionPoints       int32              `json:"completion_points"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetQuizByID(ctx context.Context, id string) (*GetQuizByIDRow, error) {
	row := q.db.QueryRow(ctx, GetQuizByID, id)
	var i GetQuizByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChallengeID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.TimeoutSeconds,
		&i.QuestionTimeoutSeconds,
		&i.RandomizeQuestions,
		&i.RevealCorrectAnswers,
		&i.AllowRetakes,
		&i.CompletionPoints,
		&i.PublishedAt,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetQuizzesByChallengeIDs = `-- name: GetQuizzesByChallengeIDs :many
SELECT id, project_id, challenge_id, name, description, image_url, timeout_seconds, question_timeout_seconds, randomize_questions, reveal_correct_answers, allow_retakes, completion_points, published_at, end_time, created_at, updated_at
FROM quizzes
WHERE challenge_id = ANY($1::text[])
    AND published_at IS NOT NULL
    AND published_at <= NOW()
ORDER BY challenge_id, published_at DESC
`

type GetQuizzesByChallengeIDsRow struct {
	ID                     string             `json:"id"`
	ProjectID              string             `json:"project_id"`
	ChallengeID            string             `json:"challenge_id"`
	Name                   string             `json:"name"`
	Description            string             `json:"description"`
	ImageUrl               *string            `json:"image_url"`
	TimeoutSeconds         *int32             `json:"timeout_seconds"`
	QuestionTimeoutSeconds *int32             `json:"question_timeout_seconds"`
	RandomizeQuestions     bool               `json:"randomize_questions"`
	RevealCorrectAnswers   bool               `json:"reveal_correct_answers"`
	AllowRetakes           bool               `json:"allow_retakes"`
	CompletionPoints       int32              `json:"completion_points"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetQuizzesByChallengeIDs(ctx context.Context, challengeIds []string) ([]*GetQuizzesByChallengeIDsRow, error) {
	rows, err := q.db.Query(ctx, GetQuizzesByChallengeIDs, challengeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetQuizzesByChallengeIDsRow{}
	for rows.Next() {
		var i GetQuizzesByChallengeIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChallengeID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.TimeoutSeconds,
			&i.QuestionTimeoutSeconds,
			&i.RandomizeQuestions,
			&i.RevealCorrectAnswers,
			&i.AllowRetakes,
			&i.CompletionPoints,
			&i.PublishedAt,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetQuizzesByIDs = `-- name: GetQuizzesByIDs :many
SELECT id, project_id, challenge_id, name, description, image_url, timeout_seconds, question_timeout_seconds, randomize_questions, reveal_correct_answers, allow_retakes, completion_points, published_at, end_time, created_at, updated_at
FROM quizzes
WHERE id = ANY($1::text[])
`

type GetQuizzesByIDsRow struct {
	ID                     string             `json:"id"`
	ProjectID              string             `json:"project_id"`
	ChallengeID            string             `json:"challenge_id"`
	Name                   string             `json:"name"`
	Description            string             `json:"description"`
	ImageUrl               *string            `json:"image_url"`
	TimeoutSeconds         *int32             `json:"timeout_seconds"`
	QuestionTimeoutSeconds *int32             `json:"question_timeout_seconds"`
	RandomizeQuestions     bool               `json:"randomize_questions"`
	RevealCorrectAnswers   bool               `json:"reveal_correct_answers"`
	AllowRetakes           bool               `json:"allow_retakes"`
	CompletionPoints       int32              `json:"completion_points"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetQuizzesByIDs(ctx context.Context, ids []string) ([]*GetQuizzesByIDsRow, error) {
	rows, err := q.db.Query(ctx, GetQuizzesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetQuizzesByIDsRow{}
	for rows.Next() {
		var i GetQuizzesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChallengeID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.TimeoutSeconds,
			&i.QuestionTimeoutSeconds,
			&i.RandomizeQuestions,
			&i.RevealCorrectAnswers,
			&i.AllowRetakes,
			&i.CompletionPoints,
			&i.PublishedAt,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetQuizzesByProjectIDs = `-- name: GetQuizzesByProjectIDs :many
SELECT id, project_id, challenge_id, name, description, image_url, timeout_seconds, question_timeout_seconds, randomize_questions, reveal_correct_answers, allow_retakes, completion_points, published_at, end_time, created_at, updated_at
FROM quizzes
WHERE project_id = ANY($1::text[])
    AND published_at IS NOT NULL
    AND published_at <= NOW()
ORDER BY project_id, published_at DESC
`

type GetQuizzesByProjectIDsRow struct {
	ID                     string             `json:"id"`
	ProjectID              string             `json:"project_id"`
	ChallengeID            string             `json:"challenge_id"`
	Name                   string             `json:"name"`
	Description            string             `json:"description"`
	ImageUrl               *string            `json:"image_url"`
	TimeoutSeconds         *int32             `json:"timeout_seconds"`
	QuestionTimeoutSeconds *int32             `json:"question_timeout_seconds"`
	RandomizeQuestions     bool               `json:"randomize_questions"`
	RevealCorrectAnswers   bool               `json:"reveal_correct_answers"`
	AllowRetakes           bool               `json:"allow_retakes"`
	CompletionPoints       int32              `json:"completion_points"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetQuizzesByProjectIDs(ctx context.Context, projectIds []string) ([]*GetQuizzesByProjectIDsRow, error) {
	rows, err := q.db.Query(ctx, GetQuizzesByProjectIDs, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetQuizzesByProjectIDsRow{}
	for rows.Next() {
		var i GetQuizzesByProjectIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChallengeID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.TimeoutSeconds,
			&i.QuestionTimeoutSeconds,
			&i.RandomizeQuestions,
			&i.RevealCorrectAnswers,
			&i.AllowRetakes,
			&i.CompletionPoints,
			&i.PublishedAt,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetQuizzesFilteredCursor = `-- name: GetQuizzesFilteredCursor :many
SELECT id, project_id, challenge_id, name, description, image_url, timeout_seconds, question_timeout_seconds, randomize_questions, reveal_correct_answers, allow_retakes, completion_points, published_at, end_time, created_at, updated_at
FROM quizzes
WHERE
    ($1::text[] IS NULL OR id = ANY($1::text[]))
    AND ($2::text = '' OR project_id = $2::text)
    AND ($3::text = '' OR challenge_id = $3::text)
    AND ($4::timestamptz IS NULL OR published_at >= $4::timestamptz)
    AND ($5::timestamptz IS NULL OR published_at <= $5::timestamptz)
    AND ($6::text = '' OR id > $6::text)
    AND ($7::text = '' OR id < $7::text)
ORDER BY
    CASE WHEN $8::bool = true THEN id END DESC,
    CASE WHEN $8::bool = false OR $8::bool IS NULL THEN id END ASC
LIMIT CASE WHEN $9::int IS NULL THEN NULL ELSE $9::int END
`

type GetQuizzesFilteredCursorParams struct {
	Ids             []string           `json:"ids"`
	Projectid       string             `json:"projectid"`
	Challengeid     string             `json:"challengeid"`
	Publishedafter  pgtype.Timestamptz `json:"publishedafter"`
	Publishedbefore pgtype.Timestamptz `json:"publishedbefore"`
	Aftercursor     string             `json:"aftercursor"`
	Beforecursor    string             `json:"beforecursor"`
	Isbackward      bool               `json:"isbackward"`
	Querylimit      int32              `json:"querylimit"`
}

type GetQuizzesFilteredCursorRow struct {
	ID                     string             `json:"id"`
	ProjectID              string             `json:"project_id"`
	ChallengeID            string             `json:"challenge_id"`
	Name                   string             `json:"name"`
	Description            string             `json:"description"`
	ImageUrl               *string            `json:"image_url"`
	TimeoutSeconds         *int32             `json:"timeout_seconds"`
	QuestionTimeoutSeconds *int32             `json:"question_timeout_seconds"`
	RandomizeQuestions     bool               `json:"randomize_questions"`
	RevealCorrectAnswers   bool               `json:"reveal_correct_answers"`
	AllowRetakes           bool               `json:"allow_retakes"`
	CompletionPoints       int32              `json:"completion_points"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetQuizzesFilteredCursor(ctx context.Context, arg GetQuizzesFilteredCursorParams) ([]*GetQuizzesFilteredCursorRow, error) {
	rows, err := q.db.Query(ctx, GetQuizzesFilteredCursor,
		arg.Ids,
		arg.Projectid,
		arg.Challengeid,
		arg.Publishedafter,
		arg.Publishedbefore,
		arg.Aftercursor,
		arg.Beforecursor,
		arg.Isbackward,
		arg.Querylimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetQuizzesFilteredCursorRow{}
	for rows.Next() {
		var i GetQuizzesFilteredCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChallengeID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.TimeoutSeconds,
			&i.QuestionTimeoutSeconds,
			&i.RandomizeQuestions,
			&i.RevealCorrectAnswers,
			&i.AllowRetakes,
			&i.CompletionPoints,
			&i.PublishedAt,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const PublishQuiz = `-- name: PublishQuiz :one
UPDATE quizzes
SET
    published_at = $1::timestamptz,
    updated_at = now()
WHERE id = $2::text
RETURNING id, project_id, challenge_id, name, description, image_url, timeout_seconds, question_timeout_seconds, randomize_questions, reveal_correct_answers, allow_retakes, completion_points, published_at, end_time, created_at, updated_at
`

type PublishQuizParams struct {
	Publishedat pgtype.Timestamptz `json:"publishedat"`
	ID          string             `json:"id"`
}

type PublishQuizRow struct {
	ID                     string             `json:"id"`
	ProjectID              string             `json:"project_id"`
	ChallengeID            string             `json:"challenge_id"`
	Name                   string             `json:"name"`
	Description            string             `json:"description"`
	ImageUrl               *string            `json:"image_url"`
	TimeoutSeconds         *int32             `json:"timeout_seconds"`
	QuestionTimeoutSeconds *int32             `json:"question_timeout_seconds"`
	RandomizeQuestions     bool               `json:"randomize_questions"`
	RevealCorrectAnswers   bool               `json:"reveal_correct_answers"`
	AllowRetakes           bool               `json:"allow_retakes"`
	CompletionPoints       int32              `json:"completion_points"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) PublishQuiz(ctx context.Context, arg PublishQuizParams) (*PublishQuizRow, error) {
	row := q.db.QueryRow(ctx, PublishQuiz, arg.Publishedat, arg.ID)
	var i PublishQuizRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChallengeID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.TimeoutSeconds,
		&i.QuestionTimeoutSeconds,
		&i.RandomizeQuestions,
		&i.RevealCorrectAnswers,
		&i.AllowRetakes,
		&i.CompletionPoints,
		&i.PublishedAt,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const UpdateQuiz = `-- name: UpdateQuiz :one
UPDATE quizzes
SET
    name = COALESCE($1::text, name),
    description = COALESCE($2::text, description),
    image_url = COALESCE($3::text, image_url),
    timeout_seconds = COALESCE($4::int, timeout_seconds),
    question_timeout_seconds = COALESCE($5::int, question_timeout_seconds),
    randomize_questions = COALESCE($6::bool, randomize_questions),
    reveal_correct_answers = COALESCE($7::bool, reveal_correct_answers),
    allow_retakes = COALESCE($8::bool, allow_retakes),
    completion_points = COALESCE($9::int, completion_points),
    end_time = COALESCE($10::timestamptz, end_time),
    updated_at = now()
WHERE id = $11::text
RETURNING id, project_id, challenge_id, name, description, image_url, timeout_seconds, question_timeout_seconds, randomize_questions, reveal_correct_answers, allow_retakes, completion_points, published_at, end_time, created_at, updated_at
`

type UpdateQuizParams struct {
	Name                   *string            `json:"name"`
	Description            *string            `json:"description"`
	Imageurl               *string            `json:"imageurl"`
	Timeoutseconds         *int32             `json:"timeoutseconds"`
	Questiontimeoutseconds *int32             `json:"questiontimeoutseconds"`
	Randomizequestions     *bool              `json:"randomizequestions"`
	Revealcorrectanswers   *bool              `json:"revealcorrectanswers"`
	Allowretakes           *bool              `json:"allowretakes"`
	Completionpoints       *int32             `json:"completionpoints"`
	Endtime                pgtype.Timestamptz `json:"endtime"`
	ID                     string             `json:"id"`
}

type UpdateQuizRow struct {
	ID                     string             `json:"id"`
	ProjectID              string             `json:"project_id"`
	ChallengeID            string             `json:"challenge_id"`
	Name                   string             `json:"name"`
	Description            string             `json:"description"`
	ImageUrl               *string            `json:"image_url"`
	TimeoutSeconds         *int32             `json:"timeout_seconds"`
	QuestionTimeoutSeconds *int32             `json:"question_timeout_seconds"`
	RandomizeQuestions     bool               `json:"randomize_questions"`
	RevealCorrectAnswers   bool               `json:"reveal_correct_answers"`
	AllowRetakes           bool               `json:"allow_retakes"`
	CompletionPoints       int32              `json:"completion_points"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (*UpdateQuizRow, error) {
	row := q.db.QueryRow(ctx, UpdateQuiz,
		arg.Name,
		arg.Description,
		arg.Imageurl,
		arg.Timeoutseconds,
		arg.Questiontimeoutseconds,
		arg.Randomizequestions,
		arg.Revealcorrectanswers,
		arg.Allowretakes,
		arg.Completionpoints,
		arg.Endtime,
		arg.ID,
	)
	var i UpdateQuizRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChallengeID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.TimeoutSeconds,
		&i.QuestionTimeoutSeconds,
		&i.RandomizeQuestions,
		&i.RevealCorrectAnswers,
		&i.AllowRetakes,
		&i.CompletionPoints,
		&i.PublishedAt,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
