// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: score_journal.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CheckScoreJournalEntryExists = `-- name: CheckScoreJournalEntryExists :one
SELECT EXISTS(
    SELECT 1 FROM score_journal
    WHERE user_id = $1::text
      AND source_type = $2::text
      AND source_id = $3::text
) AS exists
`

type CheckScoreJournalEntryExistsParams struct {
	UserID     string `json:"user_id"`
	SourceType string `json:"source_type"`
	SourceID   string `json:"source_id"`
}

// Check if a score journal entry already exists for a specific source (e.g., achievement)
func (q *Queries) CheckScoreJournalEntryExists(ctx context.Context, arg CheckScoreJournalEntryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, CheckScoreJournalEntryExists, arg.UserID, arg.SourceType, arg.SourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const CountScoreJournalFiltered = `-- name: CountScoreJournalFiltered :one
SELECT COUNT(*)
FROM score_journal
WHERE
    ($1::text = '' OR project_id = $1::text)
    AND ($2::text = '' OR user_id = $2::text)
    AND ($3::text = '' OR event_id = $3::text)
    AND ($4::text = '' OR challenge_id = $4::text)
    AND ($5::text = '' OR source_type = $5::text)
`

type CountScoreJournalFilteredParams struct {
	ProjectID   string `json:"project_id"`
	UserID      string `json:"user_id"`
	EventID     string `json:"event_id"`
	ChallengeID string `json:"challenge_id"`
	SourceType  string `json:"source_type"`
}

func (q *Queries) CountScoreJournalFiltered(ctx context.Context, arg CountScoreJournalFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountScoreJournalFiltered,
		arg.ProjectID,
		arg.UserID,
		arg.EventID,
		arg.ChallengeID,
		arg.SourceType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateScoreJournalEntry = `-- name: CreateScoreJournalEntry :one
INSERT INTO score_journal (
    id,
    project_id,
    user_id,
    event_id,
    challenge_id,
    points,
    source_type,
    source_id,
    reason,
    awarded_by,
    created_at
) VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::int,
    $7::text,
    $8::text,
    $9::text,
    $10::text,
    COALESCE($11::timestamptz, now())
) RETURNING id, project_id, user_id, event_id, challenge_id, points, source_type, source_id, reason, awarded_by, created_at
`

type CreateScoreJournalEntryParams struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	UserID      string             `json:"user_id"`
	EventID     *string            `json:"event_id"`
	ChallengeID *string            `json:"challenge_id"`
	Points      int32              `json:"points"`
	SourceType  string             `json:"source_type"`
	SourceID    *string            `json:"source_id"`
	Reason      *string            `json:"reason"`
	AwardedBy   *string            `json:"awarded_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateScoreJournalEntry(ctx context.Context, arg CreateScoreJournalEntryParams) (*ScoreJournal, error) {
	row := q.db.QueryRow(ctx, CreateScoreJournalEntry,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.EventID,
		arg.ChallengeID,
		arg.Points,
		arg.SourceType,
		arg.SourceID,
		arg.Reason,
		arg.AwardedBy,
		arg.CreatedAt,
	)
	var i ScoreJournal
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.EventID,
		&i.ChallengeID,
		&i.Points,
		&i.SourceType,
		&i.SourceID,
		&i.Reason,
		&i.AwardedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const DeleteScoreJournalByAchievement = `-- name: DeleteScoreJournalByAchievement :exec
DELETE FROM score_journal
WHERE user_id = $1::text
    AND source_type = 'ACHIEVEMENT'
    AND source_id = $2::text
`

type DeleteScoreJournalByAchievementParams struct {
	UserID        string `json:"user_id"`
	AchievementID string `json:"achievement_id"`
}

func (q *Queries) DeleteScoreJournalByAchievement(ctx context.Context, arg DeleteScoreJournalByAchievementParams) error {
	_, err := q.db.Exec(ctx, DeleteScoreJournalByAchievement, arg.UserID, arg.AchievementID)
	return err
}

const DeleteScoreJournalEntry = `-- name: DeleteScoreJournalEntry :exec
DELETE FROM score_journal
WHERE id = $1::text
`

func (q *Queries) DeleteScoreJournalEntry(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, DeleteScoreJournalEntry, id)
	return err
}

const GetScoreJournalByIDs = `-- name: GetScoreJournalByIDs :many
SELECT
    id,
    project_id,
    user_id,
    event_id,
    challenge_id,
    points,
    source_type,
    source_id,
    reason,
    awarded_by,
    created_at
FROM score_journal
WHERE id = ANY($1::text[])
ORDER BY created_at DESC
`

func (q *Queries) GetScoreJournalByIDs(ctx context.Context, ids []string) ([]*ScoreJournal, error) {
	rows, err := q.db.Query(ctx, GetScoreJournalByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ScoreJournal{}
	for rows.Next() {
		var i ScoreJournal
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.EventID,
			&i.ChallengeID,
			&i.Points,
			&i.SourceType,
			&i.SourceID,
			&i.Reason,
			&i.AwardedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetScoreJournalFiltered = `-- name: GetScoreJournalFiltered :many
SELECT
    id,
    project_id,
    user_id,
    event_id,
    challenge_id,
    points,
    source_type,
    source_id,
    reason,
    awarded_by,
    created_at
FROM score_journal
WHERE
    ($1::text = '' OR project_id = $1::text)
    AND ($2::text = '' OR user_id = $2::text)
    AND ($3::text = '' OR event_id = $3::text)
    AND ($4::text = '' OR challenge_id = $4::text)
    AND ($5::text = '' OR source_type = $5::text)
    AND ($6::text = '' OR id > $6::text)
    AND ($7::text = '' OR id < $7::text)
ORDER BY
    CASE WHEN $8::bool = true THEN created_at END DESC,
    CASE WHEN $8::bool = false OR $8::bool IS NULL THEN created_at END ASC
LIMIT CASE WHEN $9::int IS NULL THEN NULL ELSE $9::int END
`

type GetScoreJournalFilteredParams struct {
	ProjectID    string `json:"project_id"`
	UserID       string `json:"user_id"`
	EventID      string `json:"event_id"`
	ChallengeID  string `json:"challenge_id"`
	SourceType   string `json:"source_type"`
	Aftercursor  string `json:"aftercursor"`
	Beforecursor string `json:"beforecursor"`
	Isbackward   bool   `json:"isbackward"`
	Querylimit   int32  `json:"querylimit"`
}

func (q *Queries) GetScoreJournalFiltered(ctx context.Context, arg GetScoreJournalFilteredParams) ([]*ScoreJournal, error) {
	rows, err := q.db.Query(ctx, GetScoreJournalFiltered,
		arg.ProjectID,
		arg.UserID,
		arg.EventID,
		arg.ChallengeID,
		arg.SourceType,
		arg.Aftercursor,
		arg.Beforecursor,
		arg.Isbackward,
		arg.Querylimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ScoreJournal{}
	for rows.Next() {
		var i ScoreJournal
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.EventID,
			&i.ChallengeID,
			&i.Points,
			&i.SourceType,
			&i.SourceID,
			&i.Reason,
			&i.AwardedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserScore = `-- name: GetUserScore :one
SELECT COALESCE(SUM(points), 0)::bigint AS total_score
FROM score_journal
WHERE user_id = $1::text
    AND project_id = $2::text
    AND ($3::text = '' OR event_id = $3::text)
`

type GetUserScoreParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
	EventID   string `json:"event_id"`
}

func (q *Queries) GetUserScore(ctx context.Context, arg GetUserScoreParams) (int64, error) {
	row := q.db.QueryRow(ctx, GetUserScore, arg.UserID, arg.ProjectID, arg.EventID)
	var total_score int64
	err := row.Scan(&total_score)
	return total_score, err
}
