// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: translations.sql

package sqlc

import (
	"context"
)

const DeleteAchievementTranslations = `-- name: DeleteAchievementTranslations :exec
DELETE FROM achievement_translations WHERE achievement_id = $1::text
`

func (q *Queries) DeleteAchievementTranslations(ctx context.Context, achievementID string) error {
	_, err := q.db.Exec(ctx, DeleteAchievementTranslations, achievementID)
	return err
}

const DeleteChallengeTranslations = `-- name: DeleteChallengeTranslations :exec
DELETE FROM challenge_translations WHERE challenge_id = $1::text
`

func (q *Queries) DeleteChallengeTranslations(ctx context.Context, challengeID string) error {
	_, err := q.db.Exec(ctx, DeleteChallengeTranslations, challengeID)
	return err
}

const DeleteEventTranslations = `-- name: DeleteEventTranslations :exec
DELETE FROM event_translations WHERE event_id = $1::text
`

func (q *Queries) DeleteEventTranslations(ctx context.Context, eventID string) error {
	_, err := q.db.Exec(ctx, DeleteEventTranslations, eventID)
	return err
}

const DeleteProjectTranslations = `-- name: DeleteProjectTranslations :exec

DELETE FROM project_translations WHERE project_id = $1::text
`

// Delete queries for translation invalidation when base content changes
func (q *Queries) DeleteProjectTranslations(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, DeleteProjectTranslations, projectID)
	return err
}

const DeleteStreakTranslations = `-- name: DeleteStreakTranslations :exec
DELETE FROM streak_translations WHERE streak_id = $1::text
`

func (q *Queries) DeleteStreakTranslations(ctx context.Context, streakID string) error {
	_, err := q.db.Exec(ctx, DeleteStreakTranslations, streakID)
	return err
}

const DeleteSuperTeamTranslations = `-- name: DeleteSuperTeamTranslations :exec
DELETE FROM super_team_translations WHERE super_team_id = $1::text
`

func (q *Queries) DeleteSuperTeamTranslations(ctx context.Context, superTeamID string) error {
	_, err := q.db.Exec(ctx, DeleteSuperTeamTranslations, superTeamID)
	return err
}

const DeleteTeamTranslations = `-- name: DeleteTeamTranslations :exec
DELETE FROM team_translations WHERE team_id = $1::text
`

func (q *Queries) DeleteTeamTranslations(ctx context.Context, teamID string) error {
	_, err := q.db.Exec(ctx, DeleteTeamTranslations, teamID)
	return err
}

const GetAchievementTranslationsByIDs = `-- name: GetAchievementTranslationsByIDs :many
SELECT achievement_id, language_code, name, description_pending, description_completed, notification_text
FROM achievement_translations
WHERE achievement_id = ANY($1::text[])
  AND language_code = $2::text
`

type GetAchievementTranslationsByIDsParams struct {
	EntityIds    []string `json:"entity_ids"`
	LanguageCode string   `json:"language_code"`
}

type GetAchievementTranslationsByIDsRow struct {
	AchievementID        string  `json:"achievement_id"`
	LanguageCode         string  `json:"language_code"`
	Name                 *string `json:"name"`
	DescriptionPending   *string `json:"description_pending"`
	DescriptionCompleted *string `json:"description_completed"`
	NotificationText     *string `json:"notification_text"`
}

func (q *Queries) GetAchievementTranslationsByIDs(ctx context.Context, arg GetAchievementTranslationsByIDsParams) ([]*GetAchievementTranslationsByIDsRow, error) {
	rows, err := q.db.Query(ctx, GetAchievementTranslationsByIDs, arg.EntityIds, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetAchievementTranslationsByIDsRow{}
	for rows.Next() {
		var i GetAchievementTranslationsByIDsRow
		if err := rows.Scan(
			&i.AchievementID,
			&i.LanguageCode,
			&i.Name,
			&i.DescriptionPending,
			&i.DescriptionCompleted,
			&i.NotificationText,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetChallengeTranslationsByIDs = `-- name: GetChallengeTranslationsByIDs :many
SELECT challenge_id, language_code, name, description, button_text
FROM challenge_translations
WHERE challenge_id = ANY($1::text[])
  AND language_code = $2::text
`

type GetChallengeTranslationsByIDsParams struct {
	EntityIds    []string `json:"entity_ids"`
	LanguageCode string   `json:"language_code"`
}

type GetChallengeTranslationsByIDsRow struct {
	ChallengeID  string  `json:"challenge_id"`
	LanguageCode string  `json:"language_code"`
	Name         *string `json:"name"`
	Description  *string `json:"description"`
	ButtonText   *string `json:"button_text"`
}

func (q *Queries) GetChallengeTranslationsByIDs(ctx context.Context, arg GetChallengeTranslationsByIDsParams) ([]*GetChallengeTranslationsByIDsRow, error) {
	rows, err := q.db.Query(ctx, GetChallengeTranslationsByIDs, arg.EntityIds, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetChallengeTranslationsByIDsRow{}
	for rows.Next() {
		var i GetChallengeTranslationsByIDsRow
		if err := rows.Scan(
			&i.ChallengeID,
			&i.LanguageCode,
			&i.Name,
			&i.Description,
			&i.ButtonText,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEventTranslationsByIDs = `-- name: GetEventTranslationsByIDs :many
SELECT event_id, language_code, name, description
FROM event_translations
WHERE event_id = ANY($1::text[])
  AND language_code = $2::text
`

type GetEventTranslationsByIDsParams struct {
	EntityIds    []string `json:"entity_ids"`
	LanguageCode string   `json:"language_code"`
}

type GetEventTranslationsByIDsRow struct {
	EventID      string  `json:"event_id"`
	LanguageCode string  `json:"language_code"`
	Name         *string `json:"name"`
	Description  *string `json:"description"`
}

func (q *Queries) GetEventTranslationsByIDs(ctx context.Context, arg GetEventTranslationsByIDsParams) ([]*GetEventTranslationsByIDsRow, error) {
	rows, err := q.db.Query(ctx, GetEventTranslationsByIDs, arg.EntityIds, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetEventTranslationsByIDsRow{}
	for rows.Next() {
		var i GetEventTranslationsByIDsRow
		if err := rows.Scan(
			&i.EventID,
			&i.LanguageCode,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetProjectTranslationsByIDs = `-- name: GetProjectTranslationsByIDs :many

SELECT project_id, language_code, name, description, rules, info_message
FROM project_translations
WHERE project_id = ANY($1::text[])
  AND language_code = $2::text
`

type GetProjectTranslationsByIDsParams struct {
	EntityIds    []string `json:"entity_ids"`
	LanguageCode string   `json:"language_code"`
}

type GetProjectTranslationsByIDsRow struct {
	ProjectID    string  `json:"project_id"`
	LanguageCode string  `json:"language_code"`
	Name         *string `json:"name"`
	Description  *string `json:"description"`
	Rules        *string `json:"rules"`
	InfoMessage  *string `json:"info_message"`
}

// Translation queries for i18n support
// Each query fetches translations for multiple entity IDs with a specific language code
func (q *Queries) GetProjectTranslationsByIDs(ctx context.Context, arg GetProjectTranslationsByIDsParams) ([]*GetProjectTranslationsByIDsRow, error) {
	rows, err := q.db.Query(ctx, GetProjectTranslationsByIDs, arg.EntityIds, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetProjectTranslationsByIDsRow{}
	for rows.Next() {
		var i GetProjectTranslationsByIDsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.LanguageCode,
			&i.Name,
			&i.Description,
			&i.Rules,
			&i.InfoMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetQuizAnswerTranslationsByIDs = `-- name: GetQuizAnswerTranslationsByIDs :many
SELECT answer_id, language_code, answer_text
FROM quiz_answer_translations
WHERE answer_id = ANY($1::text[])
  AND language_code = $2::text
`

type GetQuizAnswerTranslationsByIDsParams struct {
	EntityIds    []string `json:"entity_ids"`
	LanguageCode string   `json:"language_code"`
}

type GetQuizAnswerTranslationsByIDsRow struct {
	AnswerID     string  `json:"answer_id"`
	LanguageCode string  `json:"language_code"`
	AnswerText   *string `json:"answer_text"`
}

func (q *Queries) GetQuizAnswerTranslationsByIDs(ctx context.Context, arg GetQuizAnswerTranslationsByIDsParams) ([]*GetQuizAnswerTranslationsByIDsRow, error) {
	rows, err := q.db.Query(ctx, GetQuizAnswerTranslationsByIDs, arg.EntityIds, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetQuizAnswerTranslationsByIDsRow{}
	for rows.Next() {
		var i GetQuizAnswerTranslationsByIDsRow
		if err := rows.Scan(&i.AnswerID, &i.LanguageCode, &i.AnswerText); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetQuizQuestionTranslationsByIDs = `-- name: GetQuizQuestionTranslationsByIDs :many
SELECT question_id, language_code, question_text
FROM quiz_question_translations
WHERE question_id = ANY($1::text[])
  AND language_code = $2::text
`

type GetQuizQuestionTranslationsByIDsParams struct {
	EntityIds    []string `json:"entity_ids"`
	LanguageCode string   `json:"language_code"`
}

type GetQuizQuestionTranslationsByIDsRow struct {
	QuestionID   string  `json:"question_id"`
	LanguageCode string  `json:"language_code"`
	QuestionText *string `json:"question_text"`
}

func (q *Queries) GetQuizQuestionTranslationsByIDs(ctx context.Context, arg GetQuizQuestionTranslationsByIDsParams) ([]*GetQuizQuestionTranslationsByIDsRow, error) {
	rows, err := q.db.Query(ctx, GetQuizQuestionTranslationsByIDs, arg.EntityIds, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetQuizQuestionTranslationsByIDsRow{}
	for rows.Next() {
		var i GetQuizQuestionTranslationsByIDsRow
		if err := rows.Scan(&i.QuestionID, &i.LanguageCode, &i.QuestionText); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetQuizTranslationsByIDs = `-- name: GetQuizTranslationsByIDs :many
SELECT quiz_id, language_code, name, description
FROM quiz_translations
WHERE quiz_id = ANY($1::text[])
  AND language_code = $2::text
`

type GetQuizTranslationsByIDsParams struct {
	EntityIds    []string `json:"entity_ids"`
	LanguageCode string   `json:"language_code"`
}

type GetQuizTranslationsByIDsRow struct {
	QuizID       string  `json:"quiz_id"`
	LanguageCode string  `json:"language_code"`
	Name         *string `json:"name"`
	Description  *string `json:"description"`
}

func (q *Queries) GetQuizTranslationsByIDs(ctx context.Context, arg GetQuizTranslationsByIDsParams) ([]*GetQuizTranslationsByIDsRow, error) {
	rows, err := q.db.Query(ctx, GetQuizTranslationsByIDs, arg.EntityIds, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetQuizTranslationsByIDsRow{}
	for rows.Next() {
		var i GetQuizTranslationsByIDsRow
		if err := rows.Scan(
			&i.QuizID,
			&i.LanguageCode,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetStreakTranslationsByIDs = `-- name: GetStreakTranslationsByIDs :many
SELECT streak_id, language_code, name, description
FROM streak_translations
WHERE streak_id = ANY($1::text[])
  AND language_code = $2::text
`

type GetStreakTranslationsByIDsParams struct {
	EntityIds    []string `json:"entity_ids"`
	LanguageCode string   `json:"language_code"`
}

type GetStreakTranslationsByIDsRow struct {
	StreakID     string  `json:"streak_id"`
	LanguageCode string  `json:"language_code"`
	Name         *string `json:"name"`
	Description  *string `json:"description"`
}

func (q *Queries) GetStreakTranslationsByIDs(ctx context.Context, arg GetStreakTranslationsByIDsParams) ([]*GetStreakTranslationsByIDsRow, error) {
	rows, err := q.db.Query(ctx, GetStreakTranslationsByIDs, arg.EntityIds, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetStreakTranslationsByIDsRow{}
	for rows.Next() {
		var i GetStreakTranslationsByIDsRow
		if err := rows.Scan(
			&i.StreakID,
			&i.LanguageCode,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetSuperTeamTranslationsByIDs = `-- name: GetSuperTeamTranslationsByIDs :many
SELECT super_team_id, language_code, name, description
FROM super_team_translations
WHERE super_team_id = ANY($1::text[])
  AND language_code = $2::text
`

type GetSuperTeamTranslationsByIDsParams struct {
	EntityIds    []string `json:"entity_ids"`
	LanguageCode string   `json:"language_code"`
}

type GetSuperTeamTranslationsByIDsRow struct {
	SuperTeamID  string  `json:"super_team_id"`
	LanguageCode string  `json:"language_code"`
	Name         *string `json:"name"`
	Description  *string `json:"description"`
}

func (q *Queries) GetSuperTeamTranslationsByIDs(ctx context.Context, arg GetSuperTeamTranslationsByIDsParams) ([]*GetSuperTeamTranslationsByIDsRow, error) {
	rows, err := q.db.Query(ctx, GetSuperTeamTranslationsByIDs, arg.EntityIds, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetSuperTeamTranslationsByIDsRow{}
	for rows.Next() {
		var i GetSuperTeamTranslationsByIDsRow
		if err := rows.Scan(
			&i.SuperTeamID,
			&i.LanguageCode,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTeamTranslationsByIDs = `-- name: GetTeamTranslationsByIDs :many
SELECT team_id, language_code, name, description
FROM team_translations
WHERE team_id = ANY($1::text[])
  AND language_code = $2::text
`

type GetTeamTranslationsByIDsParams struct {
	EntityIds    []string `json:"entity_ids"`
	LanguageCode string   `json:"language_code"`
}

type GetTeamTranslationsByIDsRow struct {
	TeamID       string  `json:"team_id"`
	LanguageCode string  `json:"language_code"`
	Name         *string `json:"name"`
	Description  *string `json:"description"`
}

func (q *Queries) GetTeamTranslationsByIDs(ctx context.Context, arg GetTeamTranslationsByIDsParams) ([]*GetTeamTranslationsByIDsRow, error) {
	rows, err := q.db.Query(ctx, GetTeamTranslationsByIDs, arg.EntityIds, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetTeamTranslationsByIDsRow{}
	for rows.Next() {
		var i GetTeamTranslationsByIDsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.LanguageCode,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
