// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_feedback.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountAllFeedback = `-- name: CountAllFeedback :one
SELECT COUNT(*) FROM user_feedback
WHERE
    ($1::char(28) = '' OR user_id = $1::char(28))
    AND (cardinality($2::text[]) = 0 OR tags && $2::text[])
    AND ($3::text = '' OR ($3::text = 'true' AND handled_at IS NOT NULL) OR ($3::text = 'false' AND handled_at IS NULL))
    AND ($4::text = '' OR platform = $4::text)
`

type CountAllFeedbackParams struct {
	Filteruserid   string   `json:"filteruserid"`
	Filtertags     []string `json:"filtertags"`
	Filterhandled  string   `json:"filterhandled"`
	Filterplatform string   `json:"filterplatform"`
}

func (q *Queries) CountAllFeedback(ctx context.Context, arg CountAllFeedbackParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountAllFeedback,
		arg.Filteruserid,
		arg.Filtertags,
		arg.Filterhandled,
		arg.Filterplatform,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateUserFeedback = `-- name: CreateUserFeedback :one

INSERT INTO user_feedback (
    id,
    user_id,
    message,
    can_contact_me,
    user_agent,
    platform,
    screen_width,
    screen_height,
    app_version,
    locale,
    project_id,
    timezone,
    context_url,
    tags
) VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::bool,
    $5::text,
    $6::text,
    $7::int,
    $8::int,
    $9::text,
    $10::text,
    NULLIF($11::text, ''),
    $12::text,
    $13::text,
    $14::text[]
) RETURNING id, user_id, message, can_contact_me, user_agent, platform, screen_width, screen_height, app_version, created_at, locale, project_id, timezone, handled_at, context_url, tags
`

type CreateUserFeedbackParams struct {
	ID           string   `json:"id"`
	Userid       string   `json:"userid"`
	Message      string   `json:"message"`
	Cancontactme bool     `json:"cancontactme"`
	Useragent    string   `json:"useragent"`
	Platform     string   `json:"platform"`
	Screenwidth  int32    `json:"screenwidth"`
	Screenheight int32    `json:"screenheight"`
	Appversion   string   `json:"appversion"`
	Locale       string   `json:"locale"`
	Projectid    string   `json:"projectid"`
	Timezone     string   `json:"timezone"`
	Contexturl   string   `json:"contexturl"`
	Tags         []string `json:"tags"`
}

// User Feedback
func (q *Queries) CreateUserFeedback(ctx context.Context, arg CreateUserFeedbackParams) (*UserFeedback, error) {
	row := q.db.QueryRow(ctx, CreateUserFeedback,
		arg.ID,
		arg.Userid,
		arg.Message,
		arg.Cancontactme,
		arg.Useragent,
		arg.Platform,
		arg.Screenwidth,
		arg.Screenheight,
		arg.Appversion,
		arg.Locale,
		arg.Projectid,
		arg.Timezone,
		arg.Contexturl,
		arg.Tags,
	)
	var i UserFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.CanContactMe,
		&i.UserAgent,
		&i.Platform,
		&i.ScreenWidth,
		&i.ScreenHeight,
		&i.AppVersion,
		&i.CreatedAt,
		&i.Locale,
		&i.ProjectID,
		&i.Timezone,
		&i.HandledAt,
		&i.ContextUrl,
		&i.Tags,
	)
	return &i, err
}

const DeleteFeedback = `-- name: DeleteFeedback :exec
DELETE FROM user_feedback WHERE id = $1::char(28)
`

func (q *Queries) DeleteFeedback(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, DeleteFeedback, id)
	return err
}

const GetAllFeedback = `-- name: GetAllFeedback :many
SELECT id, user_id, message, can_contact_me, user_agent, platform, screen_width, screen_height, app_version, created_at, locale, project_id, timezone, handled_at, context_url, tags FROM user_feedback
ORDER BY created_at DESC
LIMIT $2::int
OFFSET $1::int
`

type GetAllFeedbackParams struct {
	Offsetcount int32 `json:"offsetcount"`
	Limitcount  int32 `json:"limitcount"`
}

func (q *Queries) GetAllFeedback(ctx context.Context, arg GetAllFeedbackParams) ([]*UserFeedback, error) {
	rows, err := q.db.Query(ctx, GetAllFeedback, arg.Offsetcount, arg.Limitcount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserFeedback{}
	for rows.Next() {
		var i UserFeedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.CanContactMe,
			&i.UserAgent,
			&i.Platform,
			&i.ScreenWidth,
			&i.ScreenHeight,
			&i.AppVersion,
			&i.CreatedAt,
			&i.Locale,
			&i.ProjectID,
			&i.Timezone,
			&i.HandledAt,
			&i.ContextUrl,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetDistinctFeedbackPlatforms = `-- name: GetDistinctFeedbackPlatforms :many
SELECT DISTINCT platform FROM user_feedback WHERE platform IS NOT NULL ORDER BY platform
`

func (q *Queries) GetDistinctFeedbackPlatforms(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, GetDistinctFeedbackPlatforms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var platform *string
		if err := rows.Scan(&platform); err != nil {
			return nil, err
		}
		items = append(items, platform)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetDistinctFeedbackTags = `-- name: GetDistinctFeedbackTags :many
SELECT DISTINCT unnest(tags)::text AS tag FROM user_feedback ORDER BY tag
`

func (q *Queries) GetDistinctFeedbackTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, GetDistinctFeedbackTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFeedbackByID = `-- name: GetFeedbackByID :one
SELECT id, user_id, message, can_contact_me, user_agent, platform, screen_width, screen_height, app_version, created_at, locale, project_id, timezone, handled_at, context_url, tags FROM user_feedback WHERE id = $1::char(28)
`

func (q *Queries) GetFeedbackByID(ctx context.Context, id string) (*UserFeedback, error) {
	row := q.db.QueryRow(ctx, GetFeedbackByID, id)
	var i UserFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.CanContactMe,
		&i.UserAgent,
		&i.Platform,
		&i.ScreenWidth,
		&i.ScreenHeight,
		&i.AppVersion,
		&i.CreatedAt,
		&i.Locale,
		&i.ProjectID,
		&i.Timezone,
		&i.HandledAt,
		&i.ContextUrl,
		&i.Tags,
	)
	return &i, err
}

const GetFeedbackCursor = `-- name: GetFeedbackCursor :many
SELECT id, user_id, message, can_contact_me, user_agent, platform, screen_width, screen_height, app_version, created_at, locale, project_id, timezone, handled_at, context_url, tags FROM user_feedback
WHERE
    ($1::char(28) = '' OR id < $1::char(28))
    AND ($2::char(28) = '' OR id > $2::char(28))
    AND ($3::char(28) = '' OR user_id = $3::char(28))
    AND (cardinality($4::text[]) = 0 OR tags && $4::text[])
    AND ($5::text = '' OR ($5::text = 'true' AND handled_at IS NOT NULL) OR ($5::text = 'false' AND handled_at IS NULL))
    AND ($6::text = '' OR platform = $6::text)
ORDER BY
    CASE WHEN $7::bool = true THEN id END ASC,
    CASE WHEN $7::bool = false OR $7::bool IS NULL THEN id END DESC
LIMIT $8::int
`

type GetFeedbackCursorParams struct {
	Aftercursor    string   `json:"aftercursor"`
	Beforecursor   string   `json:"beforecursor"`
	Filteruserid   string   `json:"filteruserid"`
	Filtertags     []string `json:"filtertags"`
	Filterhandled  string   `json:"filterhandled"`
	Filterplatform string   `json:"filterplatform"`
	Isbackward     bool     `json:"isbackward"`
	Querylimit     int32    `json:"querylimit"`
}

func (q *Queries) GetFeedbackCursor(ctx context.Context, arg GetFeedbackCursorParams) ([]*UserFeedback, error) {
	rows, err := q.db.Query(ctx, GetFeedbackCursor,
		arg.Aftercursor,
		arg.Beforecursor,
		arg.Filteruserid,
		arg.Filtertags,
		arg.Filterhandled,
		arg.Filterplatform,
		arg.Isbackward,
		arg.Querylimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserFeedback{}
	for rows.Next() {
		var i UserFeedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.CanContactMe,
			&i.UserAgent,
			&i.Platform,
			&i.ScreenWidth,
			&i.ScreenHeight,
			&i.AppVersion,
			&i.CreatedAt,
			&i.Locale,
			&i.ProjectID,
			&i.Timezone,
			&i.HandledAt,
			&i.ContextUrl,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRecentFeedbackCount = `-- name: GetRecentFeedbackCount :one
SELECT COUNT(*) FROM user_feedback
WHERE user_id = $1::char(28)
  AND created_at > $2::timestamptz
`

type GetRecentFeedbackCountParams struct {
	Userid string             `json:"userid"`
	Since  pgtype.Timestamptz `json:"since"`
}

func (q *Queries) GetRecentFeedbackCount(ctx context.Context, arg GetRecentFeedbackCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, GetRecentFeedbackCount, arg.Userid, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetUserFeedback = `-- name: GetUserFeedback :many
SELECT id, user_id, message, can_contact_me, user_agent, platform, screen_width, screen_height, app_version, created_at, locale, project_id, timezone, handled_at, context_url, tags FROM user_feedback
WHERE user_id = $1::char(28)
ORDER BY created_at DESC
`

func (q *Queries) GetUserFeedback(ctx context.Context, userid string) ([]*UserFeedback, error) {
	rows, err := q.db.Query(ctx, GetUserFeedback, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserFeedback{}
	for rows.Next() {
		var i UserFeedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.CanContactMe,
			&i.UserAgent,
			&i.Platform,
			&i.ScreenWidth,
			&i.ScreenHeight,
			&i.AppVersion,
			&i.CreatedAt,
			&i.Locale,
			&i.ProjectID,
			&i.Timezone,
			&i.HandledAt,
			&i.ContextUrl,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetFeedbackHandledAt = `-- name: SetFeedbackHandledAt :one
UPDATE user_feedback
SET handled_at = $1::timestamptz
WHERE id = $2::char(28)
RETURNING id, user_id, message, can_contact_me, user_agent, platform, screen_width, screen_height, app_version, created_at, locale, project_id, timezone, handled_at, context_url, tags
`

type SetFeedbackHandledAtParams struct {
	HandledAt pgtype.Timestamptz `json:"handled_at"`
	ID        string             `json:"id"`
}

func (q *Queries) SetFeedbackHandledAt(ctx context.Context, arg SetFeedbackHandledAtParams) (*UserFeedback, error) {
	row := q.db.QueryRow(ctx, SetFeedbackHandledAt, arg.HandledAt, arg.ID)
	var i UserFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.CanContactMe,
		&i.UserAgent,
		&i.Platform,
		&i.ScreenWidth,
		&i.ScreenHeight,
		&i.AppVersion,
		&i.CreatedAt,
		&i.Locale,
		&i.ProjectID,
		&i.Timezone,
		&i.HandledAt,
		&i.ContextUrl,
		&i.Tags,
	)
	return &i, err
}

const UpdateFeedbackTags = `-- name: UpdateFeedbackTags :one
UPDATE user_feedback
SET tags = $1::text[]
WHERE id = $2::char(28)
RETURNING id, user_id, message, can_contact_me, user_agent, platform, screen_width, screen_height, app_version, created_at, locale, project_id, timezone, handled_at, context_url, tags
`

type UpdateFeedbackTagsParams struct {
	Tags []string `json:"tags"`
	ID   string   `json:"id"`
}

func (q *Queries) UpdateFeedbackTags(ctx context.Context, arg UpdateFeedbackTagsParams) (*UserFeedback, error) {
	row := q.db.QueryRow(ctx, UpdateFeedbackTags, arg.Tags, arg.ID)
	var i UserFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.CanContactMe,
		&i.UserAgent,
		&i.Platform,
		&i.ScreenWidth,
		&i.ScreenHeight,
		&i.AppVersion,
		&i.CreatedAt,
		&i.Locale,
		&i.ProjectID,
		&i.Timezone,
		&i.HandledAt,
		&i.ContextUrl,
		&i.Tags,
	)
	return &i, err
}
