// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountUsersFiltered = `-- name: CountUsersFiltered :one
SELECT COUNT(u.id)
FROM users u
WHERE
    ($1::text = '' OR u.church_id = $1::text)
    AND ($2::text = '' OR u.gender = $2::text)
    AND ($3::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) >= $3::int)
    AND ($4::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) <= $4::int)
    AND ($5::text = '' OR EXISTS (
        SELECT 1 FROM user_projects up WHERE up.user_id = u.id AND up.project_id = $5::text
    ))
    AND ($6::text = '' OR EXISTS (
        SELECT 1 FROM user_events ue WHERE ue.user_id = u.id AND ue.event_id = $6::text
    ))
    AND ($7::text = '' OR EXISTS (
        SELECT 1 FROM team_members tm WHERE tm.user_id = u.id AND tm.team_id = $7::text
    ))
    AND ($8::text[] IS NULL OR u.id = ANY($8::text[]))
`

type CountUsersFilteredParams struct {
	Churchid  string   `json:"churchid"`
	Gender    string   `json:"gender"`
	Minage    int32    `json:"minage"`
	Maxage    int32    `json:"maxage"`
	Projectid string   `json:"projectid"`
	Eventid   string   `json:"eventid"`
	Teamid    string   `json:"teamid"`
	Ids       []string `json:"ids"`
}

func (q *Queries) CountUsersFiltered(ctx context.Context, arg CountUsersFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountUsersFiltered,
		arg.Churchid,
		arg.Gender,
		arg.Minage,
		arg.Maxage,
		arg.Projectid,
		arg.Eventid,
		arg.Teamid,
		arg.Ids,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (id, members_id, email, name, gender, birthdate, church_id, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, members_id, gender, church_id, birthdate, email, name, avatar_url
`

type CreateUserParams struct {
	ID        string      `json:"id"`
	MembersID string      `json:"members_id"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	Gender    string      `json:"gender"`
	Birthdate pgtype.Date `json:"birthdate"`
	ChurchID  string      `json:"church_id"`
	AvatarUrl *string     `json:"avatar_url"`
}

type CreateUserRow struct {
	ID        string      `json:"id"`
	MembersID string      `json:"members_id"`
	Gender    string      `json:"gender"`
	ChurchID  string      `json:"church_id"`
	Birthdate pgtype.Date `json:"birthdate"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	AvatarUrl *string     `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, CreateUser,
		arg.ID,
		arg.MembersID,
		arg.Email,
		arg.Name,
		arg.Gender,
		arg.Birthdate,
		arg.ChurchID,
		arg.AvatarUrl,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.MembersID,
		&i.Gender,
		&i.ChurchID,
		&i.Birthdate,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
	)
	return &i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, members_id, gender, church_id, birthdate, email, name, avatar_url
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        string      `json:"id"`
	MembersID string      `json:"members_id"`
	Gender    string      `json:"gender"`
	ChurchID  string      `json:"church_id"`
	Birthdate pgtype.Date `json:"birthdate"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	AvatarUrl *string     `json:"avatar_url"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (*GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, GetUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.MembersID,
		&i.Gender,
		&i.ChurchID,
		&i.Birthdate,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
	)
	return &i, err
}

const GetUserByMembersID = `-- name: GetUserByMembersID :one
SELECT id, members_id, gender, church_id, birthdate, email, name, avatar_url
FROM users
WHERE members_id = $1
`

type GetUserByMembersIDRow struct {
	ID        string      `json:"id"`
	MembersID string      `json:"members_id"`
	Gender    string      `json:"gender"`
	ChurchID  string      `json:"church_id"`
	Birthdate pgtype.Date `json:"birthdate"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	AvatarUrl *string     `json:"avatar_url"`
}

func (q *Queries) GetUserByMembersID(ctx context.Context, membersID string) (*GetUserByMembersIDRow, error) {
	row := q.db.QueryRow(ctx, GetUserByMembersID, membersID)
	var i GetUserByMembersIDRow
	err := row.Scan(
		&i.ID,
		&i.MembersID,
		&i.Gender,
		&i.ChurchID,
		&i.Birthdate,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
	)
	return &i, err
}

const GetUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, members_id, gender, church_id, birthdate, email, name, avatar_url
FROM users
WHERE id = ANY($1::text[])
`

type GetUsersByIDsRow struct {
	ID        string      `json:"id"`
	MembersID string      `json:"members_id"`
	Gender    string      `json:"gender"`
	ChurchID  string      `json:"church_id"`
	Birthdate pgtype.Date `json:"birthdate"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	AvatarUrl *string     `json:"avatar_url"`
}

func (q *Queries) GetUsersByIDs(ctx context.Context, ids []string) ([]*GetUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, GetUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUsersByIDsRow{}
	for rows.Next() {
		var i GetUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.MembersID,
			&i.Gender,
			&i.ChurchID,
			&i.Birthdate,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUsersFiltered = `-- name: GetUsersFiltered :many
SELECT DISTINCT u.id, u.members_id, u.gender, u.church_id, u.birthdate, u.email, u.name, u.avatar_url
FROM users u
LEFT JOIN user_projects up ON u.id = up.user_id AND $1::text IS NOT NULL
LEFT JOIN user_events ue ON u.id = ue.user_id AND $2::text IS NOT NULL
LEFT JOIN team_members tm ON u.id = tm.user_id AND $3::text IS NOT NULL
WHERE
    ($4::text IS NULL OR u.church_id = $4::text)
    AND ($5::text IS NULL OR u.gender = $5::text)
    AND ($6::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) >= $6::int)
    AND ($7::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) <= $7::int)
    AND ($1::text IS NULL OR up.project_id = $1::text)
    AND ($2::text IS NULL OR ue.event_id = $2::text)
    AND ($3::text IS NULL OR tm.team_id = $3::text)
    AND ($8::text[] IS NULL OR u.id = ANY($8::text[]))
ORDER BY u.id
LIMIT CASE WHEN $10::int IS NULL THEN NULL ELSE $10::int END
OFFSET CASE WHEN $9::int IS NULL THEN 0 ELSE $9::int END
`

type GetUsersFilteredParams struct {
	Projectid   string   `json:"projectid"`
	Eventid     string   `json:"eventid"`
	Teamid      string   `json:"teamid"`
	Churchid    string   `json:"churchid"`
	Gender      string   `json:"gender"`
	Minage      int32    `json:"minage"`
	Maxage      int32    `json:"maxage"`
	Ids         []string `json:"ids"`
	Queryoffset int32    `json:"queryoffset"`
	Querylimit  int32    `json:"querylimit"`
}

type GetUsersFilteredRow struct {
	ID        string      `json:"id"`
	MembersID string      `json:"members_id"`
	Gender    string      `json:"gender"`
	ChurchID  string      `json:"church_id"`
	Birthdate pgtype.Date `json:"birthdate"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	AvatarUrl *string     `json:"avatar_url"`
}

func (q *Queries) GetUsersFiltered(ctx context.Context, arg GetUsersFilteredParams) ([]*GetUsersFilteredRow, error) {
	rows, err := q.db.Query(ctx, GetUsersFiltered,
		arg.Projectid,
		arg.Eventid,
		arg.Teamid,
		arg.Churchid,
		arg.Gender,
		arg.Minage,
		arg.Maxage,
		arg.Ids,
		arg.Queryoffset,
		arg.Querylimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUsersFilteredRow{}
	for rows.Next() {
		var i GetUsersFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.MembersID,
			&i.Gender,
			&i.ChurchID,
			&i.Birthdate,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUsersFilteredCursor = `-- name: GetUsersFilteredCursor :many
SELECT u.id, u.members_id, u.gender, u.church_id, u.birthdate, u.email, u.name, u.avatar_url
FROM users u
WHERE
    ($1::text = '' OR u.church_id = $1::text)
    AND ($2::text = '' OR u.gender = $2::text)
    AND ($3::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) >= $3::int)
    AND ($4::int IS NULL OR (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.birthdate)) <= $4::int)
    AND ($5::text = '' OR EXISTS (
        SELECT 1 FROM user_projects up WHERE up.user_id = u.id AND up.project_id = $5::text
    ))
    AND ($6::text = '' OR EXISTS (
        SELECT 1 FROM user_events ue WHERE ue.user_id = u.id AND ue.event_id = $6::text
    ))
    AND ($7::text = '' OR EXISTS (
        SELECT 1 FROM team_members tm WHERE tm.user_id = u.id AND tm.team_id = $7::text
    ))
    AND ($8::text[] IS NULL OR u.id = ANY($8::text[]))
    AND ($9::text = '' OR u.id > $9::text)
    AND ($10::text = '' OR u.id < $10::text)
ORDER BY
    CASE WHEN $11::bool = true THEN u.id END DESC,
    CASE WHEN $11::bool = false OR $11::bool IS NULL THEN u.id END ASC
LIMIT CASE WHEN $12::int IS NULL THEN NULL ELSE $12::int END
`

type GetUsersFilteredCursorParams struct {
	Churchid     string   `json:"churchid"`
	Gender       string   `json:"gender"`
	Minage       int32    `json:"minage"`
	Maxage       int32    `json:"maxage"`
	Projectid    string   `json:"projectid"`
	Eventid      string   `json:"eventid"`
	Teamid       string   `json:"teamid"`
	Ids          []string `json:"ids"`
	Aftercursor  string   `json:"aftercursor"`
	Beforecursor string   `json:"beforecursor"`
	Isbackward   bool     `json:"isbackward"`
	Querylimit   int32    `json:"querylimit"`
}

type GetUsersFilteredCursorRow struct {
	ID        string      `json:"id"`
	MembersID string      `json:"members_id"`
	Gender    string      `json:"gender"`
	ChurchID  string      `json:"church_id"`
	Birthdate pgtype.Date `json:"birthdate"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	AvatarUrl *string     `json:"avatar_url"`
}

func (q *Queries) GetUsersFilteredCursor(ctx context.Context, arg GetUsersFilteredCursorParams) ([]*GetUsersFilteredCursorRow, error) {
	rows, err := q.db.Query(ctx, GetUsersFilteredCursor,
		arg.Churchid,
		arg.Gender,
		arg.Minage,
		arg.Maxage,
		arg.Projectid,
		arg.Eventid,
		arg.Teamid,
		arg.Ids,
		arg.Aftercursor,
		arg.Beforecursor,
		arg.Isbackward,
		arg.Querylimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetUsersFilteredCursorRow{}
	for rows.Next() {
		var i GetUsersFilteredCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.MembersID,
			&i.Gender,
			&i.ChurchID,
			&i.Birthdate,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
